src/buffer.rs

This follows the rename of `slice::MutChunks` into `slice::ChunksMut` (and fixes the compile error due to that rename) to adhere to naming conventions.

Rename MutPixels to PixelsMut

---

src/gif/bits.rs
src/jpeg/encoder.rs
src/jpeg/entropy.rs
src/png/deflate.rs
src/webp/vp8.rs

Rust's [9c3e608](https://github.com/rust-lang/rust/commit/9c3e608) broke code of the form `x as y << z`, which now has to be written `(x as y) << z`.

Upgrade to latest Rust

---

src/buffer.rs
src/color.rs
src/imageops/colorops.rs
src/imageops/mod.rs
src/imageops/sample.rs

This fixes build errors with rustc nightly, now that boxed closures have been removed.

Use unboxed closures.

---

src/buffer.rs
src/color.rs
src/imageops/sample.rs
src/lib.rs

This makes the crate compile again with the `ea6f65c5f 2015-01-06` Rust snapshot.

Upgrade to latest Rust nightly

---

examples/opening.rs
src/animation.rs
src/buffer.rs
src/color.rs
src/dynimage.rs
src/gif/bits.rs
src/gif/decoder.rs
src/gif/lzw.rs
src/image.rs
src/imageops/mod.rs
src/imageops/sample.rs
src/jpeg/decoder.rs
src/jpeg/encoder.rs
src/jpeg/entropy.rs
src/jpeg/transform.rs
src/lib.rs
src/png/decoder.rs
src/png/deflate.rs
src/png/encoder.rs
src/png/filter.rs
src/png/hash.rs
src/png/zlib.rs
src/ppm/encoder.rs
src/tga/decoder.rs
src/tiff/decoder.rs
src/tiff/ifd.rs
src/traits.rs
src/webp/decoder.rs
src/webp/transform.rs
src/webp/vp8.rs

Mostly around macro syntax and the {:?} format specifier. Also had to add old_impl_check to some of the impls until that can be reviewed in more detail.
Also did a sweeping change from int/uint to isize/usize. No consideration was given to whether fixed sized integers would be more appropriate in some contexts; that would take a more thorough audit. This is just a blanket change to the new names.

Fixes for 1.0 alpha

---

README.md
src/gif/decoder.rs
src/gif/lzw.rs
src/imageops/affine.rs
src/imageops/colorops.rs
src/imageops/mod.rs
src/imageops/sample.rs
src/jpeg/decoder.rs
src/jpeg/encoder.rs
src/jpeg/entropy.rs
src/jpeg/transform.rs
src/png/deflate.rs
src/png/filter.rs
src/ppm/encoder.rs
src/tga/decoder.rs
src/tiff/decoder.rs
src/tiff/ifd.rs
src/webp/transform.rs
src/webp/vp8.rs

Fixes warnings of the form:
warning: use of unstable item: will be replaced by range notation, #[warn(unstable)] on by default
From rust 1.0.0-alpha update.

Update range syntax

---

examples/fractal.rs
examples/opening.rs
src/color.rs
src/dynimage.rs
src/gif/bits.rs
src/gif/decoder.rs
src/gif/lzw.rs
src/image.rs
src/jpeg/decoder.rs
src/jpeg/encoder.rs
src/jpeg/entropy.rs
src/png/decoder.rs
src/png/deflate.rs
src/png/encoder.rs
src/png/filter.rs
src/png/zlib.rs
src/ppm/encoder.rs
src/tga/decoder.rs
src/tiff/decoder.rs
src/tiff/ifd.rs
src/webp/decoder.rs
src/webp/vp8.rs

A work in progress at the moment, but this fixes some of the `use of unstable item: will be replaced by slice syntax` warnings.
Some of the slicing in `src/jpeg/encoder.rs` looks odd. They can probably be exact indexes into the quantisation tables, but I don't want to muck them up (if I haven't already).
Also in `src/buffer.rs` I'm not sure what the `Container` trait implies, so that is not touched yet.

Slice notation

---

src/lib.rs

Since rust is no in alpha and a stable alternative does not always exists this lint is not helpful.
Should possibly be removed before Rust 1.0 release.

Allow unstable code

---

src/buffer.rs

TypeId now lives in 'any', rather than 'intrinsics' - this simple PR fixes it.

TypeId has moved to 'any' module

---

README.md
src/buffer.rs
src/color.rs
src/dynimage.rs
src/gif/decoder.rs
src/image.rs
src/imageops/affine.rs
src/imageops/colorops.rs
src/imageops/mod.rs
src/imageops/sample.rs
src/lib.rs

This still needs some cleanup, but this is going to be quite a big change, so I’m posting it here for early feedback. This resolves #240. There are a lot of breaking changes, so we might want to bump the version number when this can be merged.
- This uses associated types where appropriate. The most important changes are that the type parameters of `Pixel` and `GenericImage` are now associated types. `ImageBuffer` requires less type params.
- This resolves the `old_orphan_check` and `old_impl_check` warnings.
Associated types feel like the “right” way to go. In many places it simplifies the API, but naming the subpixel type has become uglier: for `I: GenericImage`, the subpixel type is `<I::Pixel as Pixel>::Subpixel`, instead of a `T` param that was often used before. However, the `T` …

Use associated types

---

src/color.rs

[`rustc` 0b6dbbc9cfb747df1db646bba16561c022704056](https://github.com/rust-lang/rust/commit/0b6dbbc9cfb747df1db646bba16561c022704056) changed how `IndexMut` works; the `type Output = ..` bit is now redundant and can be removed from implementations.
With this change in place, `cargo build && cargo test` work again for:
```
$ rustc --version
rustc 1.0.0-nightly (74b874071 2015-02-08 00:24:03 +0000)
```

Fix IndexMut implementation for rustc 0b6dbbc

---

src/dynimage.rs
src/gif/encoder.rs
src/imageops/colorops.rs
src/imageops/mod.rs
src/math/mod.rs
src/math/nq.rs

Ported the NeuQuant color quantizer to Rust. As expected, better results than gimp. It is the default for gif now.
Full support for alpha channel. Just our png encoder doesn’t write indexed colors yet so we don’t save any space.
Us:
GIMP:

Add color quantizer

---

src/buffer.rs

This also managed to fix some really weird lifetime errors I was suddenly getting due to a Rust upgrade.

ImageBuffer::from_fn doesn't need a Box

---

src/imageops/colorops.rs
src/imageops/sample.rs

The syntax was obsolete and generated a compiler error on the latest nightly. Also, in a few places a closure was not even required.

Infer closure kinds

---

src/png/decoder.rs
src/png/deflate.rs
src/png/filter.rs

Fixes https://github.com/PistonDevelopers/image/issues/314. Overflow triggers panics in `rustc 1.0.0-nightly (fed12499e 2015-03-03) (built 2015-03-04)`, need to use `std::num::wrapping::Wrapping` when overflow is expected/intentional. See https://github.com/rust-lang/rand/commit/929ea771f2bd505bf4ce872bd43e3afc098241ae for a related fix.
Not sure how complete test coverage is in this lib, there could be more places this might blow up, but it's working for me now.

Fixed panics from arithmetic overflow

---

src/png/encoder.rs

Don't try to create the stride binding when you would be subtracting 1 from an unsigned 0 value.
Trying to write a PNG image panics with integer overflow here otherwise.

Fix integer overflow

---

src/buffer.rs
src/gif/encoder.rs

The image buffer can now directly be dereferenced into a slice (&*image_buffer). More importantly the image buffer can now be created from a slice.

Remove ArrayLike trait and remove ad_slice/_mut

---

.travis.yml
Cargo.toml
src/dynimage.rs
src/imageops/sample.rs
src/lib.rs
tests/tga.rs

The default continues to have all codecs activated, but a user can
opt-in to only supporting specific ones, via features, e.g. depending on
`image`, while only supporting JPEG and GIF:
[dependencies.image]
version = "0.2"
default-features = false
features = ["jpeg", "gif"]
On my computer `cargo build` takes ~95s, while `cargo build --features
jpeg --no-default-features` (only JPEG) takes ~28s.
This patch also updates the travis file to also compile the library with
each feature, to ensure they continue to compile. These codec features
are all independent, so testing each one individually is sufficient.
Closes #311.

Use cargo features to conditionally compile codecs.

---

README.md

The fractal example doesn’t compile without the old_path.

use std::old_path::Path for the fractal example

---

Cargo.toml
examples/fractal.rs
examples/opening.rs
src/buffer.rs
src/dynimage.rs
src/gif/decoder.rs
src/gif/encoder.rs
src/image.rs
src/imageops/sample.rs
src/jpeg/decoder.rs
src/jpeg/encoder.rs
src/jpeg/entropy.rs
src/lib.rs
src/png/decoder.rs
src/png/deflate.rs
src/png/encoder.rs
src/png/zlib.rs
src/ppm/encoder.rs
src/tga/decoder.rs
src/tiff/decoder.rs
src/tiff/ifd.rs
src/tiff/stream.rs
src/utils/bitstream.rs
src/utils/lzw.rs
src/webp/decoder.rs
src/webp/vp8.rs
tests/tga.rs

Three and a half hour of work, but it's there!
I started from scratch, as this approach was probably easier than rebasing #321 
It adds a dependency to the `byteorder` crate, which provides equivalents to `read_le_u16` and similar.

Switch to new I/O

---

src/buffer.rs
src/gif/encoder.rs
src/jpeg/decoder.rs
src/jpeg/entropy.rs
src/jpeg/transform.rs
src/lib.rs
src/math/nq.rs
src/png/filter.rs
src/ppm/encoder.rs
src/tiff/decoder.rs
tests/reference_images.rs

The crate now compiles without warnings again. For the most part, this deals with `num::Int` et al. being deprecated.

Resolve warnings for latest nightly

---

src/color.rs
src/gif/encoder.rs
src/imageops/colorops.rs
src/jpeg/decoder.rs
src/lib.rs
src/math/nq.rs
src/tga/decoder.rs
src/tiff/decoder.rs

Remaining features:
- `core`: 154 compilation errors when I remove this one. Probably fixable, but that's a lot of work.
- `std_misc`: several small things. Probably fixable too but I don't have time right now.
- `step_by`: feature-gated function because added recently. Need to check what the plan is for this one. If it's not getting stable, it is possible to write a replacement.
- `rustc_private`: used for the `flate` library. There is a replacement `flate2` on crates.io, however it's just bindings for miniz.c, which would force users to have a C compiler installed. I don't like this. Probably the most problematic feature.
- `test`: not sure how to have access to the bencher without this one.

Remove some feature gates

---

src/color.rs
src/gif/encoder.rs
src/imageops/colorops.rs

Rust does not make any guarantees about how tuple structs are layed out in memory. Using C-type-structs mediates this potential future problem.

Stop relying on implementation defined structure layout.

---

src/png/deflate.rs

Doesn't fix neither #376 nor #300 
Reviewing required, but for me it seems wrong, as `receive` already calls `consume`.

Fix inflate with uncompressed blocks

---

src/png/deflate.rs
src/png/inflate.rs

Follow-up of #379 
Stupid me didn't realize this was just a typo, and replacing `bits` by `num_bits` is the correct behavior.

Fix PNG decoder with uncompressed blocks

---

Cargo.toml
src/gif/decoder.rs
src/gif/mod.rs
src/lib.rs
src/png/decoder.rs
src/png/encoder.rs
src/png/filter.rs
src/tiff/decoder.rs
src/tiff/ifd.rs

The built-in `#[derive(FromPrimitive)]` only works with `std::num::FromPrimitive`, which is still unstable.  This significantly reduces our reliance on `#![feature(core)]`.

Replace #[derive(FromPrimitive)] with the enum_primitive crate

---

.travis.yml
src/image.rs
src/jpeg/decoder.rs
src/lib.rs
src/png/decoder.rs
src/png/encoder.rs
src/webp/decoder.rs

I copy-pasted the body of `std::slice::bytes::copy_memory`, the last unstable function that was still in use by "image".
I also added travis testing for the beta (in addition to the nightly). However `cargo test` isn't run for the beta since it uses the unstable bencher.

Finish making "image" compatible with beta

---

src/image.rs

The exact purpose of the `description` string isn't entirely clear to me, but this seems to be roughly appropriate based on the documentation.

Impl std::error::Error for ImageError

---

.travis.yml

The reason for this change is that byteorder is now broken on beta 1.
Ultimately this should be changed to `stable` after 1.0 is released, but this doesn't work yet.

Update the tested version on travis

---

src/jpeg/decoder.rs
src/jpeg/entropy.rs

On release builds overflows are not checked, on debug builds they are causing Image to panic on certain JPGs. "wrapping_shl" is unstable and not available in Rust Beta so instead this checks if the shift is too large and just sets the value to 0 if it is.

JPG overflow fix. Fixes #409

---

Cargo.toml

It'd be great to have a new version published now that #410 is fixed and the JPEG decoder doesn't overflow so much.

Bump to 0.3.10.

---

src/tga/decoder.rs

This struct never seems to be used in a way that requires being packed.
The removal is good because there's some correctness issues with it, so
there may be breaking changes to it in future and removing it now will
avoid them all together. See
https://github.com/rust-lang/rust/issues/27060.

Remove unnecessary use of `#[repr(packed)]`.

---

README.md

I updated the opening and fractal examples in README.md to match examples/opening.rs (except that opening.rs uses a command line argument) and examples/fractal.rs.  I have confirmed that both examples work on stable rust (1.1.0).

Fix issue #436: Update examples in README.md

---

src/jpeg/decoder.rs

The major change is replacing `repeat(x).take(y).collect()` with `vec![x; y]` which seems to give a 5-10% speed-up for decoding a local file.

Minor tweaks to the JPEG decoding code

---

src/imageops/affine.rs

This is the first rust I've written, so please let me know if I'm doing anything stupid or unidiomatic.
I'd like to eventually add some quickcheck-y tests so that we can cover all small image sizes (probably more use for the filtering stuff than here). This tiny set of manual examples picked up a bug though, so they're already better than nothing.

Fix flip_horizontal bug. Add tests for all affine.rs functions

---

src/bmp/mod.rs

Leaving off the https:// prefix means that it doesn't get auto-linkified
in the docs, which seems unfortunate.

fix BMP wikipedia URL

---

src/animation.rs
src/buffer.rs
src/color.rs
src/dynimage.rs
src/image.rs
src/imageops/colorops.rs
src/imageops/sample.rs
src/jpeg/encoder.rs
src/tiff/decoder.rs
src/traits.rs
src/utils/lzw.rs
src/webp/vp8.rs

Some doc comments were formatted like this:
/// This is a sentence
/// This is another sentence
When rendered to HTML, the above produces this:
> This is a sentence This is another sentence
I fixed these problems either by adding a blank line in between sentences or by adding a period.

Fix some inaccuracies and spelling/grammar/formatting errors in doc comments

---

src/bmp/decoder.rs

I guess we could really use `zip` here, but getting rid of the explicit multiplications in the pixel data indexing is nice.

use chunks_mut iteration in bmp's read_palletized_pixel_data

---

src/buffer.rs
src/image.rs
src/jpeg/entropy.rs
src/webp/vp8.rs

Change ImageBuffer default constructor (for Vec container) to use vec! macro.
```
before:
test buffer::test::bench_conversion        ... bench:   7,130,486 ns/iter (+/- 106,108) = 420 MB/s
test dynimage::bench::bench_conversion     ... bench:   7,123,419 ns/iter (+/- 34,759) = 420 MB/s
test imageops::sample::tests::bench_resize ... bench:   8,605,023 ns/iter (+/- 50,953) = 236 MB/s
after:
test buffer::test::bench_conversion        ... bench:   5,204,968 ns/iter (+/- 25,449) = 576 MB/s
test dynimage::bench::bench_conversion     ... bench:   5,204,117 ns/iter (+/- 20,338) = 576 MB/s
test imageops::sample::tests::bench_resize ... bench:   7,673,833 ns/iter (+/- 99,008) = 265 MB/s
```
Changes impact impageproc too:
```before
test affine::test::bench_rotate_bilinear …
```

use vec! macro for ImageBuffer::new

---

src/buffer.rs

Adds unsafe impl from GenericImage to ImageBuffer.
This leads to some speedups in imageproc.

impl unsafe_get/put_pixel to ImageBuffer

---

Cargo.toml
src/buffer.rs

DO NOT MERGE YET!
- Bumped to 0.6.1

Updated crates.io

---

src/buffer.rs

As [suggested by @bvssvni](https://github.com/PistonDevelopers/image/commit/64d94e54491db2e1cdc6c53f77d544540296a3d2#commitcomment-15292443)
imageproc 
```
before
test affine::test::bench_translate                                    ... bench:   1,120,290 ns/iter (+/- 25,158)
after
test affine::test::bench_translate                                    ... bench:     298,141 ns/iter (+/- 5,832)
```

inline unsafe_get_pixel and unsafe_put_pixel

---

src/dynimage.rs

This makes the inner parts of these functions non-inlinable. It also
makes open_impl and save_buffer_impl be compiled once, as part of
compiling the crate, instead of having to compile them each time their
*uses* are compiled.
This was prompted by http://stackoverflow.com/questions/36317461/
Modifying the user library and recompiling took more than 20 seconds,
with this change, only < 0.3 s. This means that `open`'s implementation
may no longer be inlined, but it shouldn't matter.

Make de-generics wrappers for open and save_buffer

---

src/color.rs

Rec. 709 forms luma using RGB coefficients 0.2126, 0.7152, and 0.0722.

Correct luma coefficients

---

src/tga/decoder.rs

The TGA decoder wasn't including the +1 when updating num_read for raw
byte sequences. Fix by using the length of pixel_data instead.

tga/decoder: fix RLE read length

---

src/lib.rs

Really minor update. Had no impact on performance when last tested, but I figured it's always better to keep current with Rust.

Removed use of deprecated function. Replaced with std::io::Write

---

Cargo.toml

I believe this can be a minor change because image does not expose any types from png in its public API.

Update to png 0.5

---

README.md
src/dynimage.rs
src/ico/encoder.rs
src/ico/mod.rs

This change adds an `ICOEncoder` struct, and uses it in `DynamicImage` to support encoding ICO files.  The implementation is very simple, since `PNGEncoder` does all the heavy lifting.
If desired, `ICOEncoder` could be expanded in the future to support storing multiple images in the same ICO file, but for now it just encodes a single image (with the same API as `PNGEncoder`).

Add support for encoding ICO files

---

src/bmp/decoder.rs
src/tga/decoder.rs
tests/truncate_images.rs

This is a minimal fix for #477.
I'm not sure this is the best fix though. What's the general philosophy regarding corrupt files? Should we fail if we detect corruption, or proceed as best as possible? A related concern is whether there should there be a limit on image width, height, palette size etc; we don't want to use gigabytes of memory due to a corrupt or malicious file.
Should I convert the test case into a file and add it under tests? This would be different from the existing tests, because I don't think there are any test cases for invalid files yet.
I also plan to audit other uses of read_to_end().

bmp/decoder: ensure palette has correct length

---

src/bmp/decoder.rs

I've added some benchmarks for reading 1/4/8 bit bmp images, and improved the performance a bit.
After this, I plan to see if I can avoid the bounds checks for setting pixels, but I want to fix the alpha support before attempting that.

bmp/decoder: 1/4/8 bit benchmarks and performance improvements

---

src/dynimage.rs

Currently, access to the `hdr` module is attempted when building the array of magic bytes even when the feature is disabled. This change inserts the bytes directly without accessing the module.

Fix build failure when HDR feature is disabled

---

src/dynimage.rs
src/lib.rs

I was missing this functionality as I would like to keep the original format from a file on files uploaded by users.

Add Format from Memory

---

src/dynimage.rs

This uses less `write` syscalls.

Use a buffered writer for writing images

---

src/lib.rs

I was trying to compile a simple example using a jpeg decoder and noticed the `DecodingResult` enum is not public.
Example code I mentioned above: https://github.com/srdqty/rust-practice/blob/57cbc9e72d2429d6600c7adbdfc73bc6d027e1b5/image-hello-world/src/main.rs

Make decoding result enum public

---

Cargo.toml
benches/load.rs
src/buffer.rs
src/dynimage.rs
src/imageops/sample.rs
src/lib.rs

I tried out moving all of the testing code for benchmarking, which uses unstable features out into it's own feature.  This should allow the rest of the tests to run on stable and beta, and then the specialized tests can still be run on nightly.

move benchmarking to a 'benchmarks' feature

---

src/imageops/mod.rs

These methods will no longer throw an unimplemented error when you try to use them.

Updated overlay() and replace() to stop using deprecated and unimplemented get_pixel_mut method

---

src/jpeg/encoder.rs

This splits the writing methods into a separate struct so they can be passed borrowed data from the encoder, instead of cloned data, to eliminate unnecessary allocations in the inner loop of `encode`. Credit goes to vfs on IRC for noticing the extra allocations.

Avoid unnecessary allocations and copies in JPEG encoder

---

src/dynimage.rs

minor fix to make the method name consistent with the imageops/colorops.rs huerotate function

dynimage: fix typo in huerotate method name

---

benches/load.rs
src/buffer.rs
src/dynimage.rs
src/imageops/sample.rs
src/lib.rs

When `benchmarks` feature is enabled in cargo, it be passed to rustc as `feature="benchmarks"` configuration option, not just `benchmarks`.

Fix building of benchmarks.

---

.travis.yml
Cargo.toml
README.md

`image` now uses docs.rs for hosting the documentation. Bump to 0.11.1 to make this change visible on crates.io.

Use docs.rs for documentation

---

Cargo.toml

In particular, this removes the dependency on num-bigint.

Disable default features on num-rational.

---

src/jpeg/encoder.rs

Fixes issue #618. It looks like commit 2c06a405ac7e3a04d139c1de16d07263c4a13573
stopped emitting the DC table by accident, resulting in JPEG files missing
huffman table 0.

Make JPEG encoder output valid images again.

---

src/dynimage.rs

When built without all of the features enabled, this arm is required.
---
Fixes the build following #617.

dynimage: uncomment the catch-all arm

---

README.md
src/bmp/encoder.rs
src/bmp/mod.rs
src/dynimage.rs

Using the [Wikipedia page on BMP files](https://en.wikipedia.org/wiki/BMP_file_format) and the `JPEGEncoder` as a guide, I've implemented simple RGB BMP encoding.  RGBA images are simply stripped of their alpha channel as transparent bitmaps aren't widely supported.
In addition to the two unit tests, I've also manually validated the fractal example from the `README` works when `Luma` -> `Rgb`, `".png"` -> `".bmp"`, and `image::PNG` -> `image::BMP`.

Add simple BMP encoder.

---

README.md
src/bmp/encoder.rs
src/bmp/mod.rs

As a follow-up to #646, this adds the ability to encode grayscale BMP images.  Alpha channel handling is the same as for RGB BMP files; that is the alpha is stripped off because it's not a widely supported feature.
In addition to the unit tests, I've also manually verified the fractal example from the README works with luma-encoded BMP images.

Enable encoding grayscale BMP images.

---

src/imageops/sample.rs

This fixes some problems I noticed with resizing images. I'll present some examples of images resized by this library prior to these changes, then show how they look after these changes. To make pixels visible, I've scaled each image up to 256x256 with no interpolation.
We'll start with this 16x16 image:
Double it's size using `FilterType::Nearest`:
```
let scaled = original.resize(32, 32, FilterType::Nearest);
```
Prior to this change, the output image was translated up and to the left by 1 pixel:
After this change it no longer translates:
```
let scaled = original.resize(16, 16, FilterType::Nearest);
```
Prior to this change, each pixel's colour was influenced by its neighbour:
After this change it looks like the original image:
```
let scaled = original.resize(8, 8, …
```

Resize fixes

---

src/tga/decoder.rs

The bit in position 5 of the image descriptor byte is the screen origin bit. If it's 1, the origin is in the top left corner, and if it's 0, the origin is in the bottom left corner. This pull request adds a function to the TGA decoder that checks the bit, and if it's 0, flips the image vertically.
This fixes the following issue, where you can also find code and images to test the commit with: https://github.com/PistonDevelopers/image/issues/663
This is my first pull request in like 5 years, so please let me know if I'm not doing something right. :)

TGA decoder taking screen origin bit into consideration

---

src/tiff/decoder/mod.rs

Currently, `image` produces the (incorrect) error message somewhere along the lines of "Grey(16) is not supported for tiff". This is because of a wacky artifact of code - a DecodingResult::U8 is produced (due to the code edited in this PR), but Grey(16) is the image type, so a [match block falls through](https://github.com/khyperia/image/blob/f23fef81cf92325f1e793b7343f540bf8eaeb94e/src/tiff/decoder/mod.rs#L434) and an error is produced.
U8 is selected because of some strange logic to divide by 8 - I'm guessing that 16 bit images were always broken, and "n" is actually 1 in the case of 8 bit images - 2 in the case of 16 bit images (which is less than 8, so U8 is selected).
Tested manually. Seems like #545 or something similar should be implemented to make sure 16 bit tiffs aren't …

Fix tiff Grey(16) support

---

src/buffer.rs
src/color.rs
src/hdr/hdr_decoder.rs
src/utils/mod.rs

Note, I'm quite new to rust, so this should be checked carefully by someone that knows what they're doing.  This is probably my 4th day playing with it (non consecutive).
I wanted to mutate a vector accumulating some other results while building an image buffer, and ran into `ImageBuffer::from_fn` wanting a `Fn` which does not allow mutation of the captured environment.  I believe this is the correct change by analogy to https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.map .
There are now just two occurrences of `Fn`:
* In `imageops::sample::Filter.kernel` (is this a reasonable way to identify that?), seems reasonable to have it be a `Fn` since the kernel should be as close to "pure" as possible.
* In `hdr_decoder::HDRDecoder.read_image_transform`, since it's using …

Use FnMut not Fn in most places

---

src/bmp/mod.rs
src/dynimage.rs
src/gif.rs
src/hdr/hdr_decoder.rs
src/hdr/mod.rs
src/ico/mod.rs
src/imageops/mod.rs
src/imageops/sample.rs
src/jpeg/mod.rs
src/math/nq.rs
src/png.rs
src/tga/mod.rs
src/tiff/mod.rs

This makes documentation work correctly with the new pulldown-cmark Markdown parser (rust-lang/rust#44229).

Fix formatting warnings with commonmark enabled

---

Cargo.toml

I noticed this crate didn't have any categories on crates.io. I figured at least `Multimedia::Images` and `Multimedia::Encoding` would be relevant. I'm not sure if `Multimedia` itself is automatically implied if these categories are present.

Add crates.io categories

---

src/ppm/decoder.rs
src/ppm/mod.rs

This fixes the following issues:
- Whitespace now includes all six character in the specification
- Comments are now handled correctly (fully ignored)
- Diagnostics when trying to read supported formats
- Wrong magic value
- `maxval` header parameter too large
- Custom messages for several format issues  of the header
- Add a bunch of tests to PPMDecoder
Basically whatever is mentioned in #691

Improve support for ppm

---

README.md
examples/fractal.rs

I'm sorry I was a bit quick opening #693, the docs are in fact not as outdated as I made it sound in that issue, I just ended up combining the wrong code snippets without realizing there is a difference between `DynamicImage:save()` and `ImageBuffer::save()` but this should be clear when reading the docs more carefully.
So these are mostly cosmetic fixes, not particularily important.

Update code samples.

---

Cargo.toml
src/dynimage.rs
src/image.rs
src/lib.rs
src/pnm/decoder.rs
src/pnm/mod.rs
src/ppm/decoder.rs

Adds decoders and format recognition for the following formats from the netbpm package:
[Portable Bit Map][pbm], [Portable Gray Map][pgm] and [Portable Arbitrary Map][pam]
[pbm]: http://netpbm.sourceforge.net/doc/pbm.html
[pgm]: http://netpbm.sourceforge.net/doc/pgm.html
[pam]: http://netpbm.sourceforge.net/doc/pam.html
Details
---------
The pam format decoder recognizes the tuple types `BLACKANDWHITE`, `GRAYSCALE` and `RGB` and explicitely recognizes but rejects their `_ALPHA` variants (support for these might come in another patch).
Tests for the new formats are not yet included but will arrive in the next week, this should stay open until then.
This should deprecate the pam module, not yet part of this pull request. In case it is desired to explicitely test for the `ppm` format …

Add other pnm (pbm, pgm, pam) decoders

---

Cargo.toml

Build failes because BigEndian::read_u16_into is used in pnm/decoder,
and is not available in byteorder 1.0.0.

bump byteorder requirement to 1.2.1

---

src/dynimage.rs
src/lib.rs
src/pnm/decoder.rs
src/ppm/mod.rs

Fix some annoying compiler warnings.
I want to improve on image scaling, but got too annoyed by compiler warnings (mainly about deprecated ppm support) while experimenting (I hope to be able to submit a PR for image scaling soonish).

Fix some compiler warnings

---

src/tiff/decoder/mod.rs

TIFF files contain only a single header. In multi image TIFFs, the header should not be read for each image (because it's not there!), only the IFD.

Fix multi image TIFF

---

src/jpeg/encoder.rs

Will push a regression test for this tomorrow, since it looks like JPEG grayscale encoding may not be covered by tests.
Closes #735.

Fix off-by-one grayscale JPEG encoding

---

Cargo.toml
src/dxt.rs
src/lib.rs

This pull requests adds an Encoder and Decoder for the DXT1/3/5 lossy compression formats. It however does not implement any file format that uses DXT compression, like DDS at the moment. Due to this there is currently not a nice way of integrating testing of the decoding/encoding with the current testing infrastructure. I plan to add support for at least one container format to solve this, but since I'm not really familiar with the way the project works I've made the pull request now already to ask for advice on how to proceed with this.
Notes on the encoder/decoder
--------
The encoder is probably not the most performant possible implementation as it brute-forces the best fitting color table per block, but it does result in reasonably high-quality encoding. It's still reasonably fast, …

DXT encoding support

---

src/dynimage.rs
src/image.rs
src/lib.rs
tests/save_jpeg.rs

Provide a way to provide format-specific options (with default values) when saving an image.  Jpeg quality is used as an example.
This closes #581 in a different way than #584.

A way to expose options when saving files

---

src/color.rs

I don't think `apply_with_alpha` is working correctly because it is not applying `g` to the alpha subpixel. The problem is that if `$alphas != 0` then it's `1`(as of now) and therefore the alpha index would be `$channels - 1` which is the correct index while now the alpha index would be `$channels - 1 - 1` which is `B` for `RGB` for example.

fix apply_with_alpha off by 1 error

---

Cargo.toml
src/dynimage.rs
src/image.rs
src/lib.rs

Also refactors out common resizing logic from `resize` and `resize_to_fill`
It seems that this was due to insufficient precision in the `f32` type which was causing rounding errors in some cases. `f64` seems to have enough precision to handle this accurately, at least in the cases I tested.
Closes #667

Fix issue where resizing an image doesn't always give an exact width/height

---

src/tga/decoder.rs

Implemented back unimplemeted TGADecoder::read_scanline.

Implmented TGADecoder::read_scanline

---

.travis.yml
tests/reference_images.rs
tests/save_jpeg.rs

The problem is discovered and discussed in #753.
The way each build was make in three steps hid failures in the two earlier steps behind success in the last step.  Use shell `&&` rather than `;` in `.travis.yml` to break the build directly if one step fails.
I believe this is working properly now.

Let broken builds be marked as failures

---

src/dynimage.rs

This PR makes the two `save` functions for `DynamicImage` and `ImageBuffer` the same and renames the old `DynamicImage` `save` to be ~`write`~ `write_to` instead.
This fixes #742.

Make save() function consistant 

---

src/buffer.rs

`Pixels`, `PixelsMut`, `EnumeratePixels` and `EnumeratePixelsMut` are
all elligible to have `ExactsizeIterator` implementations added because
the underlying iterator (a `Chunks`) implements `ExactSizeIterator`.
I wasn't sure if I needed to do anything because of how many channels there are per pixel, but this is a first stab.

Add `ExactSizeIterator` implementations to buffer structs.

---

examples/opening.rs
src/buffer.rs
src/dynimage.rs
src/image.rs
src/imageops/affine.rs
src/imageops/colorops.rs
src/imageops/mod.rs
src/imageops/sample.rs
src/lib.rs

This PR mainly involves 3 changes:
1. remove the `'static` requirement for `Self` in `sub_image` and `view`. This allows to call `sub_image` and `view` not only on an image but also on `SubImage`s;
2. add a new associated type `InnerImage` to `GenericImage` which allows to specify the return type of `sub_image` and `view`. This allows to avoid some layers of indirections in the case of `SubImages` because we can reference the original image directly. Previously nested calls to `sub_image` would result in a type like `SubImage<SubImage<SubImage<&mut I>>>` while with this PR the type would always be `SubImage<&mut I>`. On top of this,  this also makes it easy to work with `SubImage`s recursively.
3. move non mutating methods from `GenericImage` to `GenericImageView`. This allows multiple …

Improve subimages

---

src/tiff/decoder/mod.rs

Currently, the ordering of the parameters in the error string mean you get a result like this:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedError("[8] with RGBPalette bits per sample is unsupported")', libcore/result.rs:945:5
```
When really, it should look like this:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedError("RGBPalette with [8] bits per sample is unsupported")', libcore/result.rs:945:5
```
(Technically, the 'fixed' error message is still wrong, as that was actually a CIELab image with [8, 8, 8] encoding. However, since that's not supported yet, getting the error response to be less confusing is a step forward.)

Fix ordering of interpolated parameters in TIFF decode error string

---

README.md
examples/fractal.rs

Several steps are now more idiomatic
- Uses `.save`, which automatically deduces the format
- Indicates the color directly with `GrayImage`, removing a second
explicit annotation later
- Directly stores the `ImageBuffer` instead of converting to a
`DynamicImage` first
Fixes #775

Update the fractal example

---

README.md

Remove the fs::File import and fout instance.
image.save() now handles the saving and only needs 1 argument

Closes #781

---

src/image.rs

The doc comment for get_pixel_mut describes
the put_pixel method instead of the get_pixel_mut
method. This commit copies the get_pixel_mut doc
comment from buffer.rs and replaces the doc comment
in image.rs.

Fix the doc comment for get_pixel_mut

---

src/pnm/decoder.rs

Addresses the issues found in #799 
* Io errors can no longer lead to infinite loops but will instead break early
* `pbm` decoding now works properly without separators, which are optional in contrast to the formats

Fix and improve pbm decoding

---

Cargo.toml

The ecosystem seems to be moving to v2, and I'd like to avoid duplication of this crate.
(Would be nice if this could be accompanied by a version bump / publish)
r? @bvssvni

Update num-rational dependency

---

src/bmp/decoder.rs
src/bmp/encoder.rs
src/dxt.rs
src/gif.rs
src/image.rs
src/imageops/colorops.rs
src/jpeg/encoder.rs
src/webp/vp8.rs

I've implemented some suggestions from clippy-preview. There were two issues I had to ignore:
* `too_many_arguments` in `jpeg/encoder` since factoring out variables wouldn't improve this code clarity much.
* `while_let_loop` in `gif` since this would borrow the `reader` for the entire loop body. I'm not sure if this is something Clippy ought to be aware of or not.
Either way - this makes Image clean with Clippy on Rust stable.

Clippy lint pass

---

src/dynimage.rs

The docstring says RGBA when it should say BGRA, this PR corrects it.

Correct to_bgra docstring for DynamicImage

---

Cargo.toml
src/hdr/hdr_decoder.rs
src/hdr/hdr_encoder.rs
src/lib.rs
src/tiff.rs

These changes should have negligible performance impact, but reduce the amount of unsafe code in the crate.

Remove several instances of unsafe

---

src/buffer.rs

Fixes #836 (and by extension addresses one of the issues in https://github.com/PistonDevelopers/imageproc/issues/281). I'll leave this open for a few more days or hours in case an additional idea for a performance improvement comes up (thanks @fintelia for the current calculation). Right now:
```
Before: test … bench:   1,541,207 ns/iter (+/- 224,258) = 1946 MB/s
After: test … bench:   1,759,194 ns/iter (+/- 62,646) = 1705 MB/s
```
That seems acceptable but maybe not yet optimal.

Unifies, fixes, checks and benchmarks `ImageBuffer` index calculation

---

src/png.rs

This adds an incremental reader to the png type. The reader uses `png::Reader::next_row` to try to decode the png one row at a time.
This is a small breaking api change as `PNGDecoder::Reader` now becomes `PNGReader`.
There should probably be some new tests to check the reader with different buffers ect... but I am not entirely sure where they should go?
Related to #858

Implemented incremental png loading

---

src/bmp/encoder.rs

bmp/encoder: encode RGBA using bitfields with alpha mask

---

README.md

Hi :), seems like the compiler cannot infer the type so I added a concrete type for Pixel in the ImageBuffer and * to deref as the function signature states. `pub fn put_pixel(&mut self, x: u32, y: u32, pixel: P)`

README minor: adding type for the compiler and deref for pixel

---

src/imageops/mod.rs

This commit allows the `bottom` and `top` parameters of `imageops::overlay` and `imageops::replace` to have different types.

allow different image types in overlay and replace

---

Cargo.toml
README.md

Complement the move to [`image-rs`](https://github.com/image-rs) by updating the references to the repository in `Readme` and `Cargo.toml`.

[Don't merge yet] Update url references to image-rs group

---

src/dynimage.rs
src/lib.rs

This is way faster than loading a full image, and is useful if one needs to, for instance, check that all images in a folder have the same resolution, or if one needs to know the dimensions of all the images to compute some layout.
I've been using a variant of this function in [a photo album generator](https://github.com/vbarrielle/phototex/blob/master/src/main.rs#L81-L119) but I thought this might be useful for other users of the image crate.

Add function to retrieve image dimensions without loading full image

---

src/buffer.rs
src/imageops/affine.rs
src/imageops/sample.rs

We only require the pixel itself to be static, probably as the
`ImageBuffer` will allocate it into a vector and never mention any
lifetime bounds in its interface? The complete removal of the static
bound is left to another set of patches since it requires modifying the
implementation of `ImageBuffer`.

Remove unecessary 'static bounds on affine operations

---

src/dxt.rs

Removing the Power of two check for DXT Decoder.
This is only necessary for DDS files which support mipmaps, but not for individual textures.

remove power of two check

---

src/buffer.rs
src/hdr/hdr_decoder.rs
src/image.rs
src/utils/mod.rs

This is a less extreme version of #887. It leaves the public interface intact but removes a couple of unsafe blocks. 
Fixes #908

Remove nearly all instances of unsafe

---

examples/fractal.rs
src/color.rs
src/hdr/hdr_decoder.rs
src/hdr/hdr_encoder.rs
src/imageops/colorops.rs

Right now we have both structs and functions named Rgb, Rgba, etc. There is no reason for this duplication, and it clutters up the crate documentation page.  This is a breaking change, though I'm not sure how much code will be broken in practice.

Make Pixel structs more idiomatic

---

README.md
src/lib.rs

Uses a clever hack found during implementation of the standard library and popularized in this crate: https://github.com/GuillaumeGomez/doc-comment
Since this actually compiles the `README` now, we also needed to fix some of the tests.

Adds the readme as a doctest

---

README.md

This was missed by CI integration since both PRs were open in the same
timespan but the build job was not restarted after the merge of the
struct rework. This would have to be done manually.

Fix README example to updated color tuple struct

---

.travis.yml

We don't gain any interesting insight with feature flag combinations
other than 'all features' (the default). Still builds on stable and
nightly, but not beta, and 1.24.1 so that we are (somewhat) warned when
a dependency requires updating the minimum compiler version.

Reduce builds on windows and osx to full check

---

src/bmp/decoder.rs
src/dxt.rs
src/dynimage.rs
src/gif.rs
src/hdr/hdr_decoder.rs
src/ico/decoder.rs
src/image.rs
src/jpeg/decoder.rs
src/png.rs
src/pnm/decoder.rs
src/tga/decoder.rs
src/tiff.rs
src/webp/decoder.rs

This was overlooked in the initial overhaul of the trait, but is necessary for writing certain sorts of generic code over decoders.

Add lifetime bound on ImageDecoder trait

---

src/dxt.rs

I think someone made an accidental typo while doing cargo fmt and clippy fixing. This error would occasionally cause 2 pixels in a DXT block to be encoded wrong.
This commit simply restores the line of code to how it was before.
If necessary: I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

Fix a regression in the DXT encoder.

---

docs/ISSUE_TEMPLATE/bug-template.md
docs/PULL_REQUEST_TEMPLATE/pull-request.md

Github documentation makes it harder than necessary to create this
outside the webinterface but hopefully this is correct.

Add templates for issues and pull request

---

src/bmp/decoder.rs
src/gif.rs
src/hdr/decoder.rs
src/ico/decoder.rs
src/jpeg/decoder.rs
src/pnm/decoder.rs
src/tiff.rs
src/webp/decoder.rs

As @HeroicKatora pointed out, changing the Reader type of a Decoder is a breaking change. Thus have all Decoders use an opaque struct as their Reader type instead of `Cursor<Vec<u8>>`. This way we can trigger all the breakage now and be able to add incremental decoding without breaking downstream users.
Side note: In this PR I made all newly added types follow the current Rust naming convention of capitalizing only the first letter of an acronym (i.e. GifReader rather than GIFReader). I can change this if desired.

Always use custom struct for ImageDecoder::Reader

---

Cargo.toml
src/dynimage.rs
src/tiff.rs

Updated `tiff` version to 0.3.0, which supports
tiff encoding and implemented a basic tiff encoder.

Implement support for tiff encoding

---

README.md

Trivial change, but this feature is important to note.
I've contributed before, but it was awhile ago, so:

Note TIFF encoding support in README (minor)

---

src/flat.rs
src/image.rs
src/lib.rs

This is a continuation of the effort to purge unsafe code from the image crate.

Remove pixels_mut and deprecate unsafe_get_pixel/unsafe_set_pixel

---

.travis.yml

The version supports edition=2018 and several `const` improvements. It
is also the one shipped with current Debian stable (Buster, released one
day ago).
Since the oldest version supporting the new edition is not 18 weeks
older than the chosen one. But the stabilization of TryFrom, several
integer const functions, integer atomics and NonZero_ types are not
unlikely to get used eventually.
This PR is provided independent from the release PR to get last-minute
fixes the opportunity of good CI support. Does not affect the `0.21` branch.

Bump compiler requirements to 1.34.2

---

src/hdr/decoder.rs

Third part of the effort of removing `unsafe` from the library, the hdr
decoder actually required an interface change. Several other instances
had been removed in earlier commits. The method would use `Vec::set_len`
even though it did not have full control over the type parameter, as it
was a public interface.
Now simply requires the memory into which to emplace the result to be
provided and allocated externally. This makes the callers responsible
for correct optimization.
Removes the optimization for the library internal structures; it is
expected that the compiler picks up on the pattern well enough for it to
not be the main bottleneck.
Leaves the instances that are deprecated methods, they should enjoy some
deprecation period afterall and are not inherently bad as they are
correctly …

Remove actual unsafety in hdr

---

src/buffer.rs
src/dynimage.rs
src/lib.rs

Ran into the use case where I wanted to save an image without specifying the file extension in the filename. This PR lets you do just that:
```rust
img.save_with_format(&"path/to/img_file", ImageFormat::PNG);
```
I'm not sure if this is a wanted addition or not, so I'm mostly looking for feedback.
I used the `image::ImageFormat` enum for accepting formats. This enum doesn't include `pbm`, `pgm`, `ppm`, and `pam`, so I left those out as I'm not familiar enough with the library to make changes to the enum. Alternatively we can just make another enum.
------

Save image with specified format

---

src/animation.rs
src/bmp/decoder.rs
src/bmp/encoder.rs
src/dynimage.rs
src/gif.rs
src/hdr/decoder.rs
src/hdr/encoder.rs
src/ico/decoder.rs
src/ico/encoder.rs
src/image.rs
src/imageops/sample.rs
src/jpeg/encoder.rs
src/png.rs
src/pnm/decoder.rs
src/pnm/encoder.rs
src/pnm/header.rs
src/pnm/mod.rs
src/tga/decoder.rs
src/webp/decoder.rs
src/webp/vp8.rs

Replace `try!` with `?`-operator (finally!) and preemptively applies some future deprecations for trait dynamically sized trait-objects without `dyn`, which is forbidden in Rust edition 2018 and thus helps transition if wanted.

Style fixes

---

src/image.rs

Fixes #901
Returning a Result instead of a boolean should simplify error handling, and prevent accidentally ignoring errors.

[API Change] Make copy_from return an ImageResult

---

src/dxt.rs
src/dynimage.rs
src/flat.rs
src/gif.rs
src/hdr/encoder.rs
src/ico/decoder.rs
src/image.rs
src/jpeg/decoder.rs
src/jpeg/encoder.rs
src/lib.rs
src/png.rs
src/pnm/decoder.rs
src/pnm/mod.rs
src/tga/decoder.rs
src/tiff.rs
src/utils/mod.rs
src/webp/decoder.rs
src/webp/vp8.rs

Fix some clippy warnings:
* use `from` for lossless cast
* remove redundant code
* replace deprecated attributes
etc.

Fix some clippy warnings

---

src/image.rs

Resolution: Are not expected to be removed before specialization is
available in Rust (some time away).
cc: @fintelia 
Closes: #999

Undeprecate unsafe pixel accessors

---

src/dynimage.rs
src/image.rs

This was originally inlined as part of `open`'s implementation, however, I
have a usecase where I want to open a file handle and extract metadata
about the image (exif) then turn the file into an image for doing things
such as creating thumbnails, etc.
This seems like the best way to achieve this, is to expose a function
like this (I'm open to a different API FWIW). My code would then be something like:
```rust
let mut file = File::open(path);
let metadata = extract_image_metadata(&file);
let image = image::load(BufReader::new(file), image::ImageFormat::from_path(path)?)?;
image.thumbnail(256, 256).save(thumbnail_path)?;
```
Is there a better way to do something like this using this library?
Otherwise I'm inclined to believe this patch is useful for my usecase
and (hopefully) in general …

Add a function to derive a ImageFormat from a path

---

CHANGES.md
Cargo.toml
src/hdr/decoder.rs

Must initialize all memory of Vec<T> (according to valid T) prior to
calling set_len, even for zeroed memory. Furthermore, we can leak some
type instances-since they should not have a Drop implementation as per
documentation-which is safe. This allows us to complete all read
operations prior to setting the vector length, ensuring initialization
of all elements without default values.
This is a backport that avoids the interface changes made in the change
that fixed in in `0.22`, #985. It may look scary since it involves even *more* 
unsafe blocks but each has reasoning attached, that's how `unsafe` is 
supposed to be used and the reason why it is available. Please review the
reasoning carefully.
Backport feels somewhat necessary since ~50% of usage is still on `0.21` 
(as predicted from …

Backport fix for unsafety in hdr decoder

---

.travis.yml
src/hdr/decoder.rs

The known build issues (with rayon) masked that the actual backport was not compatible. This should fix the `.travis.yml` file to not run tests with `jpeg_rayon` on `1.24.1`. The less convenient 
conversion features and pointer offsetting in that version prompted me to include even more 
assertions and length checks, to be less dependent on thoroughness of my judgement.

Fixes backport for 1.24.1

---

src/image.rs

Make copy_from return an ImageResult instead of a boolean

---

src/bmp/decoder.rs
src/bmp/encoder.rs
src/dynimage.rs
src/hdr/decoder.rs
src/ico/encoder.rs
src/tga/decoder.rs

Nightly build says `try!` macro is now deprecated and use `?` operators.
This PR replaces `try!` macros with `?` operators.
Note that, this may contain formatting issue but I leave it because the diff will be large when I run `cargo fmt`. I'm happy to send a PR to run `cargo fmt` later.

Replace try! macros with ? operators

---

.travis.yml

Noted that notifications were still sent to piston related irc. The webhook configuration is already done in the Gitter channel, that's where the url comes from.

Move travis notifications to gitter

---

Cargo.toml
src/lib.rs

Remove unused lzw dependency

---

src/color.rs
src/ico/encoder.rs
src/jpeg/encoder.rs
src/pnm/encoder.rs

It is possible to get `ColorType` by calling `.color()` on `DynamicImage` but `bits_per_pixel()` nor `num_components()` function are available because they are not exported.
This PR exports them so they are available to use with `ColorType` structs returned from `DynamicImage`.
@nwin, @ccgn @HeroicKatora 
--------

Provide bits_per_pixel and num_components as ColorType methods

---

src/bmp/decoder.rs
src/buffer.rs
src/color.rs
src/dynimage.rs
src/image.rs
src/imageops/sample.rs
src/jpeg/encoder.rs
src/jpeg/entropy.rs
src/jpeg/transform.rs
src/lib.rs
src/pnm/autobreak.rs
src/tga/decoder.rs
src/utils/mod.rs
src/webp/transform.rs
src/webp/vp8.rs

Also adds `#![deny(unreachable_pub)]` to enforce more clarity in visibility qualifiers. This was maybe the root cause why this function was not added in the first place.
Closes: #978

Dynimage from decoder

---

src/dynimage.rs

Split from #933 as it doesn't require any interface design. It should really be 'authored-by martinlindhe' but that way the commit gets signed and it was what `cherry-pick` did automatically.
Co-authored-by: martinlindhe

Fix tiff magic bytes

---

CHANGES.md
Cargo.toml

Includes release notes for `0.22.1` which was a simple quickfix but nevertheless.
@fintelia

Update crate metadata for release 0.22.2

---

README.md

Fix the WebP spelling in README

---

src/dynimage.rs
src/image.rs
src/io/free_functions.rs
src/io/mod.rs
src/io/reader.rs
src/lib.rs

Replace free reader functions with `Reader` structure as sketched [in this comment of #1007](https://github.com/image-rs/image/issues/1007#issuecomment-521040748). This provides an api for reading image metadata and pixels without coupling to format guessing instead of adding all possible combinations of methods.
Also makes the interface for directly turning an `ImageDecoder` into a `DynamicImage` public.
Closes: #1007 
Closes: #716
Closes: #577
Unresolved questions:

Image reader

---

.travis.yml
src/lib.rs

Failure that occurs only on nightly seems to be more often due to Rust
breakage than a bug. Take deprecation warnings more serious by actively
denying them which warns us of incompatible future versions as nightly
would.
Note: May remove this again in the future if it doesn't help. We've
already had the case where the rustc version commitment left us
without a proper replacement for a while since that had only been
introduce shortly before deprecation.
Also ensures that tests are ran on all relevant builds instead of only
on nightly.
Closes: #1043

Align travis build to actions

---

.gitignore

---
I've contributed before, but don't remember this, so while I'm at it:

gitignore: ignore target as a symlink

---

src/color.rs

An array is indexed with constants that exceed its size. This is
inopportune even in a branch that never gets executed. This changes it
so that the indexing happens on a slice. This is a potential forward 
compatibility hazard that isn't too hard to fix.
Also removes a bunch of annotations by avoiding primitive casts with
explicit type annotations in constants.

Fix strict const_err

---

src/io/free_functions.rs
src/tga/decoder.rs

explicit `'static` lifetime on static variable and `to_string` to `format!` are redundant.

Remove redundant code

---

src/bmp/decoder.rs
src/bmp/encoder.rs
src/bmp/mod.rs
src/dxt.rs
src/gif.rs
src/hdr/decoder.rs
src/ico/decoder.rs
src/ico/mod.rs
src/io/free_functions.rs
src/jpeg/decoder.rs
src/jpeg/encoder.rs
src/jpeg/mod.rs
src/png.rs
src/pnm/decoder.rs
src/pnm/mod.rs
src/tga/decoder.rs
src/tga/mod.rs
src/tiff.rs
src/webp/decoder.rs
src/webp/mod.rs
src/webp/vp8.rs
tests/reference_images.rs

Also rename gif::Decoder to be consistent with the other decoder names.

Proper capitalization for decoder struct names

---

src/bmp/decoder.rs
src/bmp/encoder.rs
src/dxt.rs
src/dynimage.rs
src/gif.rs
src/hdr/decoder.rs
src/ico/decoder.rs
src/image.rs
src/io/free_functions.rs
src/jpeg/decoder.rs
src/jpeg/encoder.rs
src/png.rs
src/pnm/decoder.rs
src/pnm/mod.rs
src/tga/decoder.rs
src/tiff.rs
src/webp/decoder.rs

This PR makes breaking changes to the ImageDecoder trait. Now is a good time to do these because the next branch already has a bunch of breaking changes queued and the longer we wait the more code will be written against the current interfaces.
Alignment issues make returning a Vec awkward, and this seems like the simplest way of avoiding that. If the interface proves annoying to use we can always add helper functions or higher level abstractions. One possible future path would be to have image-canvas be an optional dependency of image-core so that there could be a function like `ImageDecoder::read_to_canvas(self) -> ImageResult<Canvas>` or similar.
I initially picked u64's for consistency with the *__bytes_ functions + forward compatibility. However I've since realized that image formats …

Opinionated changes to ImageDecoder

---

src/bmp/decoder.rs
src/dxt.rs
src/hdr/decoder.rs
src/image.rs

Make read_rect take u32 for {x, y, width, height}

---

src/io/free_functions.rs

WIP for issue #927 
I have the basics down for `gif` and `dxt` in `save_buffer`, and `gif` for `save_buffer_with_format_impl`. I just would to check a few things:

Adding  gif format to `save_buffer`

---

src/png.rs

Simple change to avoid silently writing PNG images in the wrong channel order. It would be slightly nicer to change the return type to ImageResult, but that would be a breaking change so let's hold off on that for now.
Fixes #826

PNG encoding should return error on unsupported color type

---

examples/scaledown/main.rs
examples/scaleup/main.rs
src/flat.rs
src/lib.rs

There are a bunch of types are structs that are exported from the crate root but don't need to be. Not having them makes the documentation less cluttered.

Less in root

---

src/jpeg/encoder.rs
src/jpeg/mod.rs

This pull request allows setting a custom DPI value for JPEG images (the encoder used to hardcode a pixel aspect ratio of 1x1 for all images).
Fixes #1077

Allow setting a custom pixel density in the JPEG encoder

---

src/color.rs
src/image.rs
src/lib.rs

Of note, these were previously hidden despite `#[deny(unreachable_pub)]` because they were no completely unreachable, just unnamable. Note that the `ImageDecoder` utilizes them both in function signatures and through some trait trickery it was theoretically possible to type-def them (or so I think).
Also, `Progress` was completely opaque and missing any accessors, contrary to its use in the callback since it could not be inspected. Sorry :cry: .

Document and expose all new pub structures

---

.travis.yml
Cargo.toml
src/dynimage.rs
src/image.rs
src/imageops/sample.rs
src/io/free_functions.rs
src/jpeg/decoder.rs
src/lib.rs
tests/reference_images.rs

This series of patches makes the Cargo.toml more concise, updates it in a few places, and removes the "gif_codec" and "png_codec" features in favor of just referring to them via "gif" and "png" respectively.
The first two items should have no end user impact, but renaming features represents a breaking change.

Simplify cargo toml

---

src/dynimage.rs

This PR adds `into_*` functions to `DynamicImage`. These are like `to_*`, but they avoid a copy in case the image was already in the correct format.
Interesting future work could be to reuse the existing buffer when possible.

Add DynamicImage::into_* functions.

---

src/hdr/decoder.rs
src/image.rs
src/jpeg/decoder.rs

Rust is about to hard-deprecate Error::description, which has been soft deprecated for over a year.
Also switches `cause` to the newer `source` (requires 1.30.0).

Remove deprecated Error::description

---

src/animation.rs
src/gif.rs

Fixes: #877 
That issue was caused by an overflow in the "frame delay" field between individual frames of the GIF frames when expressed in milliseconds. This translates to highly unrealistic frame rates of greater than 65 seconds per frame (i.e. over 1000x slower than a normal monitor refresh rate), but ideally should still not result in panics. This PR switches to using u32's to prevent the possibility of overflow while still allowing all delay values expressible by GIF images.
At the same time I noticed that there was some confusion about the actual units used to store frame delays in various places. I've renamed a bunch of places to "delay_ms" to be clear when milliseconds are in use.
**Open questions**: Is num_rational::Ratio<u32> really the right type to express the delay in …

Fix potential overflow in GIF decoding

---

src/imageops/affine.rs
src/imageops/mod.rs

This PR implements the rotate{90, 180, 270} (and flip_{vertical,horizontal}) functions with a destination buffer argument as described in #1082 as new functions with an `_in` suffix. It also implements an `in_place` version for the flip functions as well as for `rotate180` since implementing those was rather straightforward. The previous functions have been reimplemented by using the new `_in` version to avoid code duplication.

add flip and rotate in destination operations

---

src/animation.rs
src/bmp/decoder.rs
src/bmp/encoder.rs
src/buffer.rs
src/dxt.rs
src/dynimage.rs
src/error.rs
src/flat.rs
src/gif.rs
src/hdr/decoder.rs
src/hdr/encoder.rs
src/ico/decoder.rs
src/ico/encoder.rs
src/image.rs
src/io/free_functions.rs
src/jpeg/decoder.rs
src/jpeg/encoder.rs
src/lib.rs
src/png.rs
src/pnm/decoder.rs
src/pnm/encoder.rs
src/tga/decoder.rs
src/tiff.rs
src/webp/decoder.rs

This resolves a few rebasing issues that came up while rebasing #928.
At least it is supposed to. I'm expecting a few pushes.

Move error types to seperate module

---

src/buffer.rs
src/image.rs
src/math/mod.rs
src/math/rect.rs

Attempts to implement #987 with a specialized version for `ImageBuffer`
I unfortunately couldn't come up with a way of implementing this without basically copy pasting the copy logic 4 times while still using static dispatch due to there being 4 different cases to handle that determine in what order to copy the pixels. Hence I wrote a small macro to make the implementation more readable(even though macro normally does the opposite). If you got any ideas for how to improve this I'd be happy to change this.
Regarding the the function signature I currently chose to use a tuple for the two corners of the source and destination rectangles with a width and height parameter, this should obviously thought about a bit more. The other alternatives being two tuples one describing the source …

Implement copy_within for GenericImage

---

.travis.yml
Cargo.toml
src/dds.rs
src/image.rs
src/io/free_functions.rs
src/lib.rs

Basically, the DDS decoder parses the DDS header to create a DXT decoder. `ImageDecoder` is implemented by forwarding calls to this inner DXT decoder.
The DDS header (which includes pixel format) is parsed, even if only few fields are used by the current code.
Full support would require to handle all kinds of DDS formats and provide an alternate `ImageDecoder` implementation for non-DXT formats.
This is a first step towards closing #621.

Add support for DDS files using DXT1, DXT3 or DXT5 compression

---

src/color.rs
src/dynimage.rs
src/image.rs
src/pnm/encoder.rs
src/utils/mod.rs

Future compatibility change to allow PRs such as #1121 without a 
breaking change.
Also note the curious and complicated but clever way of statically
eliminating the actual branch in matchings, and avoid the need for
unreachable markers within the crate. This has been ported to the other
uses of non-exhaustive enumerations.

Make ImageFormat related enums non-exhaustive

---

Cargo.toml

Missed that since the PR build of #1121 didn't trigger after a rebase. Fairly straightforward as the feature depends on the dxt decoder internally.

Add missing feature requirement dxt for dds

---

src/error.rs
src/image.rs
src/io/free_functions.rs
src/lib.rs
src/png.rs
src/pnm/decoder.rs
tests/reference_images.rs

Moves away from a single, open representation of errors to an extensible and precise one. This considers a previously identified few issues (in #928):
* The new variants are somewhat actionable since they at least identify the
cause more closely.
* They are extensible as most state is opaque to some degree and key
enumerations are marked as non-exhaustive which allows us to extend
it later, for example to capture the difference between dimension 
mismatch errors.
* They are more precise as the opaque state allows storing specialized
variants for supported formats while still maintaining a uniform
interface and permitting extension formats outside the library.
* Handling of 'stringification' is more principled as error values can
be stored as-is instead of converting them on the spot. This …

Error rework

---

src/dynimage.rs
src/gif.rs
src/io/free_functions.rs
src/jpeg/decoder.rs
src/png.rs

Hide some public interface dependencies on gif and jpeg. Note that frame
oriented functions are now unused and will likely be brought back in a
(slightly less generic) manner that is more uniform over other multi
frame formats as well.

Interface restrictions for gif and jpeg

---

.travis.yml
Cargo.toml.public-private-dependencies

See the nightly feature [`public-dependency`](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#public-dependency), tracking issue: [#44663](https://github.com/rust-lang/rust/issues/44663). Very cool to check if we actually depend on anything publicly.
Based on local tests, this should currently fail with a dependency on `num-rational`. This is insofar suboptimal as they might bump version to `0.3` soon (last updated was a year ago, #809, also see #1036 where we had to manually adjust that public type).

Add travis script and public dependency reference

---

Cargo.toml
examples/scaledown/main.rs
examples/scaleup/main.rs

The tiff dependency update is especially nice for compilation times because it removes the syn 0.15 dependency.

Fix a warning

---

src/animation.rs
src/gif.rs
src/lib.rs

Two major reasons:
* This avoids the public dependency on `num_ratio`.
* The internal representation can be changed. This already proved
necessary once (from u16 rational) and in this manner we are free to
do it again by adding an inner enum representation.
Note that we already have rounding semantics for the meaning of Delay as
gif rounds to the nearest 10ms when writing frames. Any more or less
precise representation can be made to round to the closest u32 ratio.

Encapsulate the delay ratio

---

src/webp/decoder.rs
src/webp/vp8.rs

This is part of #1134, rework for `webp` module.

Use detailed errors for WebP decoder

---

src/dxt.rs

This is part of #1134, rework for `dxt` module.

Use detailed errors for DXT encoder and decoder

---

src/webp/vp8.rs

This uses slices to index into the relevant portions of the array for top_pixels and edge_pixels, which helps decrease runtime by ~100%, as seen below:
```
test webp::vp8::bench::bench_edge_pixels                       ... bench:           8 ns/iter (+/- 0)
test webp::vp8::bench::bench_edge_pixels_new                   ... bench:           0 ns/iter (+/- 0)
test webp::vp8::bench::bench_top_pixels                        ... bench:           5 ns/iter (+/- 0)
test webp::vp8::bench::bench_top_pixels_new                    ... bench:           0 ns/iter (+/- 0)
```
I also tweaked avg2 to avoid u16 conversions. 
I added tests to cover all changes made, (including tests which fully cover the output of avg2 and avg3 to ensure that they remain consistent). The tests for edge_pixels and top_pixels …

Optimize some functions in vp8.rs

---

src/error.rs
src/gif.rs
src/hdr/decoder.rs
src/ico/decoder.rs

This constructor has previously been used for at least three different purposes:
* To signal that an image has already been read from a stream.
* As a decoding error when some provided data was shorter than expected.
* An non-recoverable error has been produced already in a stream of images.

Deprecate and remove ImageEnd error constructor

---

src/jpeg/decoder.rs
src/jpeg/encoder.rs

This is part of #1134, rework for `jpeg` module.
[`jpeg_decoder::UnsupportedFeature`](https://docs.rs/jpeg-decoder/0.1.18/jpeg_decoder/enum.UnsupportedFeature.html) is mapped to `UnsupportedErrorKind::GenericFeature(format!("{:?}", desc))`.

Use detailed errors for JPEG encoder and decoder

---

Cargo.toml
benches/encode_bmp.rs

Since I'm currently trying to optimize BMPEncoder, I decided to add benchmarks for it in `bench/`, using Criterion, which also targets #1143.

Add criterion benchmarks for BMPEncoder

---

src/pnm/decoder.rs
src/pnm/encoder.rs

This is part of #1134, rework for `pnm` module.

Use detailed errors for PNM encoder and decoder

---

src/jpeg/encoder.rs

This isn't intended to optimize the code in jpeg/encoder.rs, but is intended to make it more idiomatic and hopefully, clearer.

Minor optimizations / refactoring of jpeg/encoder.rs

---

src/bmp/encoder.rs

Original:
```
test bmp::encoder::tests::bench_encode_rgb    ... bench:   5,782,530 ns/iter (+/- 218,122)
test bmp::encoder::tests::bench_encode_rgba   ... bench:   8,998,140 ns/iter (+/- 16,662,076)
```
New:
```
test bmp::encoder::tests::bench_encode_rgb    ... bench:   3,316,475 ns/iter (+/- 209,397)
test bmp::encoder::tests::bench_encode_rgba   ... bench:   4,440,780 ns/iter (+/- 436,233)
```
For some reason, the rgba benchmark seems to have a large +/- of ~17M ns, but the actual timings are always ~9M ns.
I've included benchmarks, and I've tested against the BMP tests, which seem to work fine.

Double performance of rgb / rgba encode methods in BMPEncode

---

Cargo.toml

#1144 (image 0.23.1) requires https://github.com/image-rs/jpeg-decoder/pull/119 (jpeg-decoder 0.1.17) to compile, so clarify that in Cargo.toml.

Require jpeg-decoder >= 0.1.17 for Send + Sync error

---

README.md

TGA is missing from the list of supported image formats

Add TGA to list of Supported Image Formats in README.md

---

src/color.rs

Since the enumeration is non-exhaustive, implementing this method might
be more brittle than necessary. This commits to having such a judgement
available for all future color types but that should not be problematic.
Closes: #1167

Implement ColorType::has_alpha

---

.travis.yml
src/bmp/encoder.rs
src/webp/vp8.rs

Removes bmp benchmarks that have been implemented as integration
benchmarks. Fixes the compilation of vp8 benchmarks that test some
implementation methods.

Cleanup internal benchmarks

---

src/io/reader.rs
src/lib.rs

Per discussion on #1180 most of the documentation will remain in `README.md` for now. However, the first search engine hit when searching for "rust image" is the docs.rs version of `src/lib.rs`, so having a link through to `README.md` significantly helps with documentation discoverability.

Add crosslink to github docs.

---

Cargo.toml
src/bmp/decoder.rs
src/dxt.rs
src/dynimage.rs
src/farbfeld.rs
src/hdr/decoder.rs
src/image.rs

Marked as draft since I can't get `load_rect()` to stop panicking in code I don't understand; see commit marked [WIP], particularly the diff with `read_scanline()`.
`cargo test --features farbfeld farbfeld`:
```
running 1 test
test farbfeld::tests::read_rect ... FAILED
failures:
---- farbfeld::tests::read_rect stdout ----
inner
magic = [102, 97, 114, 98, 102, 101, 108, 100]
magic ok
[src\farbfeld.rs:66] read_dimm(&mut inner) = Ok(
2,
)
[src\farbfeld.rs:67] read_dimm(&mut inner) = Ok(
3,
)
rrwp(1, 1, 1, 2)
start = 16
we in this
Progress { current: 0, total: 16 }
|s, scanline=12|
[src\image.rs:244] bytes_read = 0
[src\image.rs:244] &mut buf[(dbg!(bytes_read) as usize)..] = [
0,
64,
]
[src\image.rs:244] &mut dbg!(& mut buf
[(dbg ! (bytes_read) as usize) ..])[..(scanline_bytes as usize)] = [ …
```

farbfeld followup

---

src/animation.rs
src/buffer.rs
src/color.rs
src/dynimage.rs
src/flat.rs
src/gif.rs
src/image.rs
src/imageops/affine.rs
src/imageops/colorops.rs
src/imageops/mod.rs
src/imageops/sample.rs
src/lib.rs
src/traits.rs

Moves `Pixel` into the trait module. Exposes a public `buffer` module where iterators and other auxiliary definitions relating to the `ImageBuffer` are exported. The main `ImageBuffer` is _not_ re-exported within that module, for now. At some point we might want to make the type less special and then change the structure further and deprecate old export points.
Closes: #1069 
Closes: #549 (which apparently was either re-broken or never fixed)

(Internally) restructure the buffer module

---

src/buffer.rs
src/lib.rs

Adds more documentation that addresses some of #1182. This does not yet remove those sections from the Readme, it's also a slight rewrite of the relevant sections or purely new documentation especially on how and when to use the different decoders.

Add more crate documentation

---

benches/decode.rs

Covers all formats except pnm and png as they do not have a lot of test
images. For the latter, these are mostly in the `png` crate itself.

Add decoding benchmarks based on test images

---

src/dynimage.rs
src/error.rs
src/flat.rs
src/gif.rs
src/image.rs
src/imageops/affine.rs
src/jpeg/encoder.rs

Removal of the DimensionError constructor listed in #1134.
There is one instance where I don't think the error is fitting though I wasn't sure what to replace it with either which is in the gif module where it is being used for erroring on the `frame_delay` being bigger than a `u16`.

Remove DimensionError constructor

---

src/bmp/decoder.rs
src/dds.rs
src/error.rs
src/ico/decoder.rs
src/png.rs
src/pnm/decoder.rs
src/webp/decoder.rs
src/webp/vp8.rs

Also fixes a formatting bug in what is now `ImageEntryDimensionMismatch` with `format: Bmp`.
This knocks off `ico` from the list in #1134 and gets rid of one simple inline TODO item

Replace legacy error constructors in ICO decoder. Make DecodingError::message a Cow to reduce allocations

---

src/dds.rs
src/dynimage.rs
src/image.rs
src/io/reader.rs
src/jpeg/decoder.rs
src/png.rs

Along with #1196 and #1145 this gets us to zero (ish) `ImageError::UnsupportedError` uses
Part of: #1134, #1195

Remove most ImageError::UnsupportedError usages. Destringrypify DDS decoder

---

src/dynimage.rs
src/imageops/mod.rs
src/lib.rs

The links, as [seen](https://docs.rs/image/0.23.3/image/#fn.open.html) on docs.rs don't actually go anywhere right now.
Ref: #1199

Add _imm versions of  DynImage:: and imageops::crop(). Fix function links in toplevel doc

---

src/bmp/decoder.rs
src/dds.rs
src/dynimage.rs
src/error.rs
src/farbfeld.rs
src/flat.rs
src/hdr/decoder.rs
src/ico/decoder.rs
src/png.rs

Remove `ImageError::UnsupportedColor` usage from DynImage, farbfeld, flat, PNG and the constructor. Add `.into() -> ImageError` for the rest of *private* DecoderErrors.
Only TGA left, with #1145.
Part of #1134
Ref: #1203

Remove `ImageError::UnsupportedColor`, improve readability of DecoderErrors

---

src/tga/decoder.rs

This is part of #1134, rework for `tga` module.
All errors that can be emitted from the decoder is "unsupported pixel format", so I used `UnsupportedErrorKind::Color` variant, but I'm not sure it is good.
It erases detailed error info such as number of alpha bits.

Use detailed errors for TGA decoder

---

src/color.rs
src/dynimage.rs
src/image.rs
src/io/free_functions.rs
src/jpeg/decoder.rs
src/utils/mod.rs

Mainly the vomit from `ExtendedColorType` in each and every build, but tested with no features, one feature at a time, and all features, all of which have just the two warnings fixed by #1205.

Berid of most (all?) warnings

---

src/gif.rs

I believe this fixes #1227 
---

Fix bug in gif encoding of rgba8 frames

---

src/buffer.rs
src/image.rs

As discussed in #1223.
The intention here is to help the optimizer. For methods where access
out-of-bounds is not fatal the bounds checking code appears to be
repeated unnecessarily in many cases—once for a manual check to avoid
the panic and once in the impl in the path that would lead to such
panic.
This is backwards compatible in that the new methods are default
implemented on the traits. In the long term it seems nevertheless
advisable to flip this around and default implement the panicking method
instead. This would also improve possibilities for indexing and
adherence to the API guidelines.

Introduce bounds check pixel get/get_mut

---

.travis.yml

Addresses the CI portion of #1240, until we have either reached a definitive decision or the next MSRV bump.

Disable test execution on old Rust version in CI

---

.travis.yml

This was visible after trying to manually trigger a build which redirected to the otherwise invisible tab on travis: https://travis-ci.com/github/image-rs/image/requests This finally shows the error message that it is unable to parse the file. (Edit: Travis show the request for this PR as received).

Remove comment, which might mess up the travis parser

---

src/buffer.rs

Just like the `Pixels` iterator we do not yield any rows when the rows
of the image are empty (even if height is not 0), as otherwise we would
have to ensure that `height` can be represented as a `usize` to satisfy
the requirements of `ExactSizeIterator`. (Not literally, we could always
panic or return an incorrect results without causing unsoundness.
However that would be a suboptimal solution when we can already be
consistent with prior art).
Closes: #994

Fix rows iterator for zero width images

---

src/buffer.rs
src/image.rs

Reverts image-rs/image#1229
I was a bit too quick here. Specifically the name is not universally agreed on and the implementation is not sure to actually _guarantee_ an advantage for the optimizer. Let's back off on this since it introduces new API surface, to ensure that we can do a non-breaking minor version release on the weekend with many other fixes and featuers.

Revert "Introduce bounds check pixel get/get_mut"

---

src/color.rs
src/dynimage.rs
src/jpeg/encoder.rs

Change the JPEG encoder to work on a GenericImageView instead of a byte slice
This change allows users to encode jpeg images from other sources
than memory, thus finally allowing the encoding of images that
do not fit in memory.
This also allows users to make the encoder work in a streaming fashion.
(see #1219)
This also finally allows encoding images from other pixel formats than
8-bit RGB. The conversion to 8bit YCbCr (used in JPEG) is done on the fly
during encoding.
I need this change for [dezoomify-rs](https://lovasoa.github.io/dezoomify-rs/).

make the jpeg encoder work with non-memory and non RGB8 images

---

src/io/reader.rs

The previous documentation links to a method that was ultimately made
private in a decision to make `Reader` behave like a builder style
struct, and prioritize chaining with `self` over `&mut self` as it
handles the non-Clone reader.
Fixes: #1231

Fix the method reference to with_guessed_format

---

src/buffer.rs

The motivation for this change is to make iteration with a larger buffer easy. Consider construction an image from the prefix of a buffer. `ImageBuffer::from_raw(_, _, buf)` does not complain if the buffer is in fact larger than required. In such a case one still expects pixels, especially the ones yielded by the `enumerate_*` iterators, to be in-bounds. In particular, these two loops should be more or less equivalent:
```rust
for x in 0..image.width() {
for y in 0..image.height() {
let p = image.get_pixel(x, y);
}
}
```
```rust
for (x, y, p) in image.enumerate_pixels() {
}
```
But previously the second loop would yield _more_ pixels including ones that are out of bounds beyond the height of the image.

Ensure that pixels iterator stays in-bounds

---

src/buffer.rs

This provides a (very trivial) implementation for #697 but is also meant to encourage discussion about this Issue or make private decisions about it public.

Add derives for `Hash`, `PartialEq` and `Eq`.

---

src/buffer.rs

Attempts to address the documentation suggestion in #1252
A lot of the methods for modifying an image are found in the `ImageBuffer` so that is where I was looking when trying to convert an image to a different Pixel type.

Direct user to DynamicImage for converting

---

src/buffer.rs

The methods were updated in 86af214b but the doc string was not missed.

Minor doc fix to into_flat_samples

---

Cargo.toml
Cargo.toml.public-private-dependencies
src/tiff.rs
src/utils/mod.rs

We don't support 32-bit and 64-bit samples in the `ColorType` yet but still introduce code to handle their conversion. This also modernizes the interface by switching `NativeEndian` to a more direct byte cast based method.

Update tiff to v0.5

---

Cargo.toml

Update num-rational/num-complex dependency to 0.3

---

src/buffer.rs
src/flat.rs
src/image.rs

Closes: #616 (with a true helper)

Some helper and interop for FlatSamples

---

src/buffer.rs

Was sort of surprised that they don't already.

Derive Clone for iterators

---

src/lib.rs

Fix a few minor grammar issues in docs

---

src/imageops/colorops.rs
src/math/nq.rs

This change allows users to expand the indexed `Luma<u8>` returned by `imageops::colorops::index_colors` back into a true color image.
I also added type level documentation for `imageops::colorops::BiLevel`
and `math::nq::NeuQuant` showing how to use `ColorMap`.

imageops/colorops: add `lookup` to `trait ColorMap`.

---

src/dxt.rs
src/farbfeld.rs
src/gif.rs
src/ico/encoder.rs
src/jpeg/encoder.rs

Particularly for new contributors, who might be looking at other modules
for reference, it is quite confusing to copy some functionality and get
told in review to change it. This also serves as a reference in case
someone wants to tackle updating code.
As discussed in review of #1270

Add some TODO to mark unidiomatic code

---

src/lib.rs

This trait is used to bound the `save` method on ImageBuffer and
DynamicImage which avoids leaking the implementation detail of using
bytemuck for casting particular channel slices to bytes. This trait is
sealed so there are little breakage risks, this allows downstream crates
to name it as a bound.

Export the EncodableLayout trait

---

src/imageops/colorops.rs

This makes the generated documentation slightly clearer

ColorMap::lookup() argument shouldn't start with an underscore

---

src/flat.rs

Implement std::error::Error for flat::Error

---

src/buffer.rs

- main change is the doc string for the enumerator, because I always get confused about the iteration order is it first rows then columns or the other way around. Maybe that helps other for confused people like me.
- the other stuff is just apply cargo fmt

describe the pixel enumeration order in the doc comment to avoid confusion

---

src/imageops/colorops.rs

This allows unsized types like those returned by `Box<dyn ColorMap<_>>>.as_ref()` to be passed into these functions.

imageops: Add `?Sized` bound to generic type `Map`.

---

examples/tile/main.rs
src/imageops/mod.rs

Example usage:
```rust
pub fn example_tile() {
let mut img = RgbaImage::new(300, 170);
let background_color = Rgba::from_slice(&[20, 20, 20, 255]);
for p in img.pixels_mut() {
*p = *background_color;
}
let tile = image::open("spinner.png").unwrap();
image::imageops::tile(&mut img, &tile);
img.save("test.png").unwrap();
}
```
Example output image:

imageops: introduce tile function

---

src/farbfeld.rs

Fixes the following warning:
warning: unused import: `EncodingError`
--> src/farbfeld.rs:26:20
|
26 | use crate::error::{EncodingError, DecodingError, ImageError, ImageResult, UnsupportedError, UnsupportedErrorKind};
|                    ^^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default

fix unused import warning in farbfeld.rs

---

benches/encode.rs
src/bmp/encoder.rs
src/bmp/mod.rs
src/dds.rs
src/dxt.rs
src/dynimage.rs
src/gif.rs
src/hdr/decoder.rs
src/hdr/encoder.rs
src/ico/encoder.rs
src/ico/mod.rs
src/image.rs
src/io/free_functions.rs
src/jpeg/encoder.rs
src/jpeg/mod.rs
src/png.rs
src/pnm/decoder.rs
src/pnm/encoder.rs
src/pnm/header.rs
src/pnm/mod.rs

fixes #1258 
I created a type definition for each previous struct name and marked them as deprecated. In order to export these typedefs, I needed to use `#[allow(deprecated)]` in some of the `mod.rs` files. Instead, typedef definitions could be in the `mod.rs` files to not have to do this. Or they could be not marked as deprecated. Although, I think the `#[allow(deprecated)]` tags are fine given that the typedefs will be removed in the next version (I assume). 
All the names that were changed:
- `PNGReader` -> `PngReader`
- `PNGEncoder` -> `PngEncoder`
- `BMPEncoder` -> `BmpEncoder`
- `DXTReader` -> `PngReader`
- `DXTEncoder` -> `DxtEncoder`
- `DXTVariant` -> `DxtVariant`
- `gif::Encoder` -> `gif::GifEncoder`
- `ICOEncoder` -> `IcoEncoder`
- `HDRAdapter` -> `HdrAdapter`
- `HDREncoder` -> …

Fixed Inconsistent capitalization of Encoder/Decoder structs.

---

src/io/reader.rs

`not unable` should be just `unable`.
The sentence otherwise reads as if the current format remains unchanged when a format is guessed.
The inverse is then also true when no format is guessed the current format is updated, but no value to update it to is guessed.

Typo in reader.rs

---

src/bmp/encoder.rs
src/flat.rs
src/gif.rs
src/image.rs
src/io/free_functions.rs
src/jpeg/encoder.rs
src/math/nq.rs
src/png.rs
src/pnm/decoder.rs
src/pnm/header.rs

Good day!
I've fixed some clippy warnings. There are still three warnings like the following.
clippy 0.0.21
```sh
warning: All variants have the same postfix: `Invalid`
--> src/dds.rs:22:1
|
22 | / enum DecoderError {
23 | |     /// Wrong DDS channel width
24 | |     PixelFormatSizeInvalid(u32),
25 | |     /// Wrong DDS header size
...  |
31 | |     DdsSignatureInvalid,
32 | | }
| |_^
|
= note: `#[warn(clippy::enum_variant_names)]` on by default
= help: remove the postfixes and use full paths to the variants instead of glob imports
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#enum_variant_names
warning: needless `fn main` in doctest
--> src/imageops/mod.rs:171:4
|
171 | /// use image::{RgbaImage};
|    ^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: …
```

Fix clippy warnings

---

src/buffer.rs

fixes #1298 , fixes #1299 
In order to allow for auto-vectorization optimizations the uses of `Chunk`/`ChunkMut` have been replaced with `ChunkExact`/`ChunkExactMut`. 
The best guess for why `Chunk` and `ChunkMut` don't result in auto-vectorization is that as far as the compiler is concerned they iterate over dynamically sized slices (and therefor the compiler might not know where the end is which would result in no auto-vectorization). While it could be inferred that each chunk is less than or equal to known const size, I don't know rust well enough to know if that is done.
Regardless this is the resulting disassembly for the following rust code (both with `opt-level = 3`):
```rust
fn test_func() -> RgbaImage
{
ImageBuffer::from_pixel(7500, 7500, Rgba([0,0,0,255]))
}
```
asm before this …

Added auto-vectorization optimizations to `ImageBuffer` methods.

---

src/buffer.rs
src/image.rs

Relaxes or adds impls for `Debug` and `Clone` to applicable iterators. Note that deriving the impls on the `ImageBuffer` iterators does not lead to the wanted outcome as it would introduce a bound of `Debug` on the pixel type and not on the channel type. This is more restrictive and not representative of the underlying representation.
Closes: #1266

Iterator impls

---

examples/gradient/main.rs
src/imageops/mod.rs
src/traits.rs

This is a very basic linear gradient implementation for both vertical and horizontal directions. The implementation does not support the concept of multiple gradient stops, but it could be implemented quite easily using this contribution as a starting point.
Included examples that can be run to check correct behavior of a RGBA gradient on PNG image output.
Example usage:
```rust
use image::{Rgba, RgbaImage, Pixel};
fn main() {
let mut img = RgbaImage::new(100, 100);
let start = Rgba::from_slice(&[0, 128, 0, 0]);
let end = Rgba::from_slice(&[255, 255, 255, 255]);
image::imageops::vertical_gradient(&mut img, start, end);
img.save("vertical_gradient.png").unwrap();
image::imageops::horizontal_gradient(&mut img, start, end);
img.save("horizontal_gradient.png").unwrap();
}
```
Result of the …

introduce gradients in imageops

---

src/buffer.rs

I license past and future contributions under the dual MIT/Apache-2.0 license.
I needed a way in my game engine to share raw image data across multiple iterations of infinite loop (because obviously I don't want to load it every time or copy it) so I added one.

Add non-consumable equivalent of into_raw to ImageBuffer

---

.travis.yml
Cargo.toml
Cargo.toml.public-private-dependencies
examples/convert.rs
src/avif/mod.rs
src/image.rs
src/io/free_functions.rs
src/lib.rs

Converts the data to the `Img` buffer and encodes it into an intermediate vector, then writes this into the output writer. It tries to avoid actually allocating for that conversion. It considers that `RGBA8` can be converted from any byte slice and uses the applicable conversion. Any non-rgba8 image is converted using an intermediate buffer. (cc: @fintelia) Some of this code may be used for the conversion feature as well.
However it does not support limits.
Closes: #1152

Rough draft including ravif for AVIF encoding

---

README.md

Document AVIF support in README

---

Cargo.toml
src/gif.rs

Well this is slightly awkward. In an effort to avoid denial-of-service, the `gif` crate now checks each frame descriptor to be inbounds. Apparently this is not quite expected and there's a test [preventing out-of-bound action](https://github.com/image-rs/image/commit/503690269091d47444e9c94ffbd8f394de897b0b) in case one of the descriptors is actually out of bounds. We'll revert this and do another try.

Update gif crate

---

src/dynimage.rs
src/image.rs

PR #1314 added encoding support for the AVIF image format. The PR however did not yet include `ImageOutputFormat` support. An `ImageOutputFormat` entry is required when encoding and writing images through `DynamicImage::write_to`. This commit adds an `Avif` entry to the `ImageOutputFormat` enum, and also includes a conversion from an `ImageFormat` to an `ImageOutputFormat`.
---

Add ImageOutputFormat support for AVIF

---

src/jpeg/encoder.rs
src/jpeg/entropy.rs

This PR replaces the use of write_u8 and write_all on Vec's to push and extend_from_slice respectively, which resolves a few TODO's and removes the need to do `let _ =` to handle the errors that `write_u8` and `write_all` may throw.

Make functions in jpeg/encoder.rs more idiomatic, clean up todos

---

src/jpeg/encoder.rs
src/jpeg/entropy.rs

This PR adds a const implementation of derive_codes_and_sizes and build_huff_lut - as these functions are typically used on const data - this speeds up JpegEncoder::new / JpegEncoder::new_with_quality by 4x (2250ns -> 500ns), but this is only really significant if you're making many, many small images and creating new encoders for each.
This isn't currently compatible without using nightly on 1.34, but it does compile without nightly on 1.46, so merging this PR would require a bump in the minimum version required.

Add const implementation for build_huff_lut

---

src/jpeg/encoder.rs
src/jpeg/transform.rs

*EDIT: I've expanded the scope of this PR to introduce other optimizations which are related
This PR adds size information to jpeg::fdct, and JpegEncoder::write_block, which always take arrays of size 64, but don't specify this in the function signature.  Specifying that the size of the input slices is 64 allows for aggresive SIMD generation and removal of all bounds checking in these functions - this actually allows the fdct to heavily take advantage of SIMD -though the generated assembly goes from 205 lines to 447, which might be problematic - you can see this for yourself at https://godbolt.org/z/PWG7b9.
Additionally, this BitWriter method, `write_segment(&mut self, marker: u8, data: Option<&[u8]>)` is very odd, and should really be two seperate functions `write_marker(&mut self, …

Add size information to function signatures, optimize BitWriter in jpeg

---

src/io/free_functions.rs

Line 147 of `io/free_functions.rs` (`fn save_buffer_impl`) already uses this technique to make the syntax simpler. I apply this technique to line 231 (`fn guess_format_from_path_impl`)

consistent syntax with line 147

---

src/jpeg/decoder.rs

Add a `scale(&mut self, requested_width, requested_height)` to `JpegDecoder`, exposing same functionality in `jpeg_decoder::Decoder`.
Question: As it is allowed for this function to do nothing, maybe it should be added to trait `ImageDecoder`?  If would be possibe to add a meaningfull implementation to any "progressive" format, such as png and gif, and there could be a do-nothing default implementation in the trait.

Provide scale method of JpegDecoder.

---

src/png.rs
src/traits.rs

Most of the time we read data into an empty vector. So intead of always copying by `extend_from_slice` and emptying `self.buffer`, just `mem::swap()` them when `buf` is empty (which is the common case).

Reduce copying in src/png.rs

---

src/codecs/jpeg/encoder.rs
src/codecs/webp/vp8.rs
src/imageops/colorops.rs
src/imageops/sample.rs
src/math/utils.rs
src/utils/mod.rs

The _clamp_ function can easily be implemented with an `if` statement. There is no need for it to be part of image's public API. Since the function is internally used by the crate, I added an implementation to our internal utils module and converted all instances to use that instead.

Deprecate clamp function

---

src/dynimage.rs
src/io/free_functions.rs
src/lib.rs

This is unfortunately more verbose / error-prone than I would like, but this way users will actually see warnings when using the old paths for the codec modules.

Generate warnings when using old paths for codec module items

---

.travis.yml
Cargo.toml
src/codecs/tiff.rs

I'm not sure if we should forbid the floating point color types `Rgb{,a}{F32,F64}` more explicitly for now but `bytemuck` makes it painless to defined the buffer conversion, even though our own `ColorType` does not support those buffers yet.

Upgrade tiff to 0.6

---

src/codecs/png.rs
src/color.rs
src/dynimage.rs

---
This PR introduces additional color conversion when the source and destination bit-depth differs. The `DynamicImage` `to_` and `into_` methods have been made consistent by specifying the bit-depth in the name and deprecating the originals. Notably, some of the `Bgr[a]16` conversion methods are missing due to `DynamicImage` having no variant for them.
This addresses the primary concern from #1347, but does not address the return type inconsistency. Some of the type aliases used in the method signatures are private, which results in the documentation being inconsistent. I've decided to leave that change for a separate PR.

Add bit-depth specific `into_` and `to_` DynamicImage conversion methods

---

src/dynimage.rs

Adds `DynamicImage::into_bytes(self)` and `DynamicImage::as_bytes(&self)`. 
The primary motivation for this was needing the underlying storage buffer as a `byte` vector without having to create a copy using `to_bytes`. I added `as_bytes` as an extra convenience.

Add copyless DynamicImage to byte slice/vec conversion

---

src/dynimage.rs
src/math/mod.rs
src/math/utils.rs

Note that math::utils::resize_dimensions() is crate public.
We don't want to expose it outside of this crate in its current form.
Relates to https://github.com/image-rs/image/issues/1354

Move the dynimage::resize_dimensions function to math::utils

---

src/color.rs

The pointer from which a mutable reference is created must have
provenance for accessing the underlying elements of the struct and its
fields (a single array here) mutably. A pointer acquired by
slice::as_ptr does not have that provenance, it only allows shared read
access. The `slice::as_ptr` method says:
> The caller must also ensure that the memory the pointer
(non-transitively) points to is never written to (except inside an
UnsafeCell) using this pointer or any pointer derived from it. If you
need to mutate the contents of the slice, use as_mut_ptr.
This fails MIRI which checks for this assertion but I'm not aware of
mis-compilation resulting from it. In fact, consider:
pub fn as_ptr(slice: &mut [u8]) -> *const u8 {
slice.as_ptr()
}
pub fn as_mut_ptr(slice: &mut [u8]) -> *mut u8 { …

Fix assembling mutable slice from const reference

---

src/image.rs
src/io/free_functions.rs

I also moved the inner non-generic function form `io::free_functions` and removed the intermediate `PathError` enum.

Add `ImageFormat::from_extension`

---

src/imageops/mod.rs
src/imageops/sample.rs

Fixes #983 
Adds a test with the reproduction steps provided in the issue.

Fixes #983. blur 0.0 panic

---

tests/reference_images.rs
tests/truncate_images.rs

The second patch might be better served as just unignoring these tests, since I don't really see why they *are* ignored, it's not like they take an exorbitant amount of time to build or run (`time cargo test -- --ignored` says real 0m5.351s, user 0m14.907s, sys 0m1.250s for me on a pre-compiled run), and being missed in an API transition indicates that they will likely be missed again, later, with potentially more consequences.

Fix warnings in reference_images tests and unignore them

---

CHANGES.md
Cargo.toml

A little bit out of schedule, as in not on a weekend, but considering this fixes a theoretical soundness concern and a SemVer break I'd rather get it out the door soonish.

Update release notes and meta data for 0.23.12

---

src/buffer.rs

Solution for the problem that lead to #1370 
This implements `Default` for any `ImageBuffer` that has a container type that also implements `Default`

Implement Default for ImageBuffer if Container implements Default

---

src/math/utils.rs

Fixes https://github.com/image-rs/image/issues/1109
Adds a test case for resizing function.

Fixes #1109. Adds a default 1 when resizing dims.

---

src/codecs/avif/mod.rs

A draft change to add an additional method to avif to allow writing an image while specifying the quality and speed. It's a bit messy with the number of arguments, but shouldn't break any existing apis.

Add write_image_with_speed_quality function.

---

src/codecs/jpeg/encoder.rs
src/codecs/jpeg/entropy.rs

Since huff_lut always has to be 256 items long, we can get rid of bounds checks by returning [(u8, 16); 256] from build_huff_lut, and storing Box<[(u8, 16); 256]> instead of Vec, which does not have a length known at compile-time.
Improvements as below, after 3 runs of `cargo +nightly bench --features "benchmarks"` to ensure steady state times for both.
```
L8-rawvec/64: -0.035us = -0.106%
L8-bufvec/64: -0.666us = -1.817%
L8-file/64: -3.075us = -7.898%
L8-rawvec/128: 0.340us = 0.277%
L8-bufvec/128: -3.600us = -2.581%
L8-file/128: -6.200us = -4.572%
L8-rawvec/256: 1.110us = 0.229%
L8-bufvec/256: -5.100us = -0.941%
L8-file/256: 5.070us = 1.017%
Rgb8-rawvec/64: -2.159us = -2.176%
Rgb8-bufvec/64: -1.590us = -1.466%
Rgb8-file/64: 0.070us = 0.069%
Rgb8-rawvec/128: -6.770us = -1.739% …
```

Add size hint for build_huff_lut

---

src/animation.rs

This allows getting a mutable `RgbaImage` from a mutable `Frame` to easily edit a frame sequence (e.g. a GIF image).

frame: Add buffer_mut function

---

src/codecs/gif.rs

This is straight up forwarded to the underlying gif library, and allows setting the encoding quality to be able to get faster encodes.
This is especially useful for debug builds, where the absence of optimization from the compiler makes this awfully slow. For a simple test gif (260x160, 36 frames), it took more than 1 minute to encode it on a core i7 laptop. On release builds, the difference is much less perceptible, but this still gives the option to the user.

codecs/gif: Add speed argument

---

src/codecs/gif.rs
src/lib.rs

This option allows controlling the GIF repetition options, like setting the GIF to loop indefinitely.

gif: Add set_repeat to GifEncoder

---

src/dynimage.rs

All variants of `DynamicImage` (which are all `ImageBuffer` types) derive `Debug, Hash, PartialEq, Eq`.
`DynamicImage` not implementing them seems like an undesirable restriction, this makes it usable where those traits are required.

Derive Debug, Hash, PartialEq, Eq for DynamicImage

---

src/codecs/jpeg/decoder.rs

The decoder unwrapped the info struct from the jpeg decoder. This is not
guaranteed to return Some, e.g. when not even the header of the jpeg
was parsed correctly.

Fix wrong expectation of image info

---

Cargo.toml
benches/copy_from.rs
src/image.rs

Copying by row instead of by column makes this function 5x to 10x faster for typical image types (like `ImageBuffer`) that store pixels by row.

Optimize default implementation of copy_from

---

README.md
src/buffer.rs
src/image.rs
src/imageops/mod.rs

It was unclear where the coordinate space in an image started from. I have added notes about it in a few key places.

Improved documentation of pixel enumeration and coordinate access.

---

src/imageops/sample.rs

Round float numbers before conversion in sampling

---

src/codecs/avif/encoder.rs
src/codecs/avif/mod.rs

This change makes it possible to use the ravif YCbCr encoding option, which converts RGB to YCbCr, getting higher compression ratios in AVIF.

Allow setting the AvifEncoder ColorSpace

---

.github/workflows/rust.yml
Cargo.toml
src/codecs/avif/mod.rs
src/io/free_functions.rs
src/lib.rs

Note that this splits avif-feature into encoder and decoder.
They require different native dependencies in their build systems, one
of the available on Ubuntu-20.04 (the latest Github build environment)
while the other one is not.
Unblocks: #1418

Avif and default tests

---

CHANGES.md
Cargo.toml
src/lib.rs

It's been a while since the last release but we have some major new features—notably `AVIF` support—as well as fixes.

Update readme, release notes, metadata for 0.23.13

---

src/codecs/gif.rs

Fixes #1238 
Reading a gif that contained frames exceeding its "Logical Screen" dimensions would panic. 
This PR simply enables the check that is provided by the underlying decoder.
Feel free to reject or comment if you want to handle out of bounds frames differently.

Enabled bounds check for gif frames

---

src/codecs/webp/vp8.rs
tests/reference_images.rs

The panic macro will change in edition2021 such that it is consistent
between core and std. Currently, only one permits a single formattable
value as the only argument. Instead, it will work more like write and
format itself. This also means that format itself is unnecessary.
Fixed like it should be suggested for: https://github.com/rust-lang/rust/issues/82110

Fix forward compatibility of panicking

---

src/codecs/gif.rs

I've been working with the animated image encoders and decoders in `image`, and discovered that the `Repeat` enum used by the gif encoder, does not implement the `Debug` trait. This PR adds a derive for Debug, so it can be used directly by anything that requires the Debug trait to be implemented.

Derive Debug for gif Repeat

---

CHANGES.md
Cargo.toml

The TGA fixes are pretty useful on their own, this also bumps the minimum required version of `jpeg` in preparation for what will be required anyways once we start looking at ICC&EXIF—which is necessary to fix issues such as #1440 in the long run.

Update meta data for 0.23.14

---

Cargo.toml

----
This might need special care if num-rational is used in any public API.

Update to num-rational 0.4

---

src/buffer.rs
src/dynimage.rs
src/image.rs
src/io/free_functions.rs
src/lib.rs

Addresses #834 by implementing a method called `write_to` in ImageBuffer.

creates a method to encode ImageBuffers to a specified writer

---

src/buffer.rs
src/dynimage.rs
src/image.rs
src/io/free_functions.rs

Resolves #1446 by adding a TIFF variant to the [`ImageOutputFormat`](https://docs.rs/image/*/image/enum.ImageOutputFormat.html). Also merges [`DynamicImage::write_to`](https://docs.rs/image/0.23.14/image/enum.DynamicImage.html#method.write_to) with `free_functions::write_buffer_impl`.

Add TIFF variant to ImageOutputFormat

---

Cargo.toml
src/codecs/avif/encoder.rs

Works around a breaking change done by the latest version of `ravif`, which added a new field to `Config`.

Fix compiling with avif-encoder

---

Cargo.toml

The version which introduced the breaking change fixed in #1456 has been yanked and republished as 0.7

Update to ravif 0.7

---

src/codecs/avif/encoder.rs

Uses the new [`ravif::encode_rgb`](https://docs.rs/ravif/0.7.0/ravif/fn.encode_rgb.html) method for encoding `Rgb8` images, instead of copying them into a `Rgba8` image just to have `ravif` ignore the alpha channel.

Use the new ravif::encode_rgb function for encoding Rgb8 images

---

src/image.rs

This change downgrades the trait bound on `to_image` from `GenericImage` to `GenericImageView`, because it only requires immutable access to the inner image. `GenericImage: GenericImageView`, so this change should be fully backwards compatible.
Fixes https://github.com/image-rs/image/issues/1469

`to_image` now only requires `I::Target: GenericImageView`

---

src/color.rs

Add F32 RGB/RGBA variants to both color type enumerations. 
Internally requires only 4 bytes of storage, but looking up a pixel should yield an `Rgba<f32>` color. It should not be necessary to allocate a complete `RGBA32F` buffer just to to offer the `Rgba<f32>` value, but it would be possible now. I can probably implement that change in this PR if desired.

Add minimal F32 support to ColorType

---

src/dynimage.rs

This adds some convenience `From` implementations from each `DynamicImage` variant to the enum itself.
You can already convert any variant to the enum by just constructing the variant itself, but this can help cut down repetition and allow for some generic bounds such as `T: Into<DynamicImage>`.

Implement From on DynamicImage

---

src/dynimage.rs
src/io/free_functions.rs
src/lib.rs
tests/save_jpeg.rs

This PR changes the API, now requiring all writers to be seekable. 
Non-Seekable writers are pretty rare, and can still be used by allocating a temporary seekable byte vector. This allows us to allocate less in the common case, which is writing to an already seekable destination. At this moment, no encoder utilizes this advantage yet (TiffEncoder only writes to files?). The individual encoders could be revisited to see whether they can already profit from this new requirement.
@fintelia @HeroicKatora  I looked at the avif encoder. The `fallback` buffer is required for reasons other than seeking. It is necessary because of the design of the avif library, which allocates a vector in any case. I was not yet able to remove that temporary buffer even when requiring `Seek` from the writer.

Require Seekable Writer

---

src/dynimage.rs

All variants implement width()/height() naturally and there are situations where you want to know the size of the image without first
converting it and without having to manually handle all variants.

Add width()/height() to DynamicImage

---

src/buffer.rs
src/dynimage.rs

This pull request removes unnecessary qualification in dynimage.rs and buffer.rs files
For dynimage.rs file, there is a redefinition of  `use std::io::Write;` in the `write_buffer_with_format` function.
For buffer.rs file, there is redefinition of `use crate::{ImageOutputFormat, color::{FromColor, Luma, LumaA, Rgb, Rgba, Bgr, Bgra}};` in `mut_iter` test

Refactor: remove unnecessary qualification 

---

src/color.rs
tests/conversions.rs

The previous version of this function simply multiplied u8 values by
256. This is incorrect, because it means that the largest a converted
u8 value can be is 255 * 256 = 65280, instead of the actual largest
u16 value of 65535. This commit fixes this by changing the function to
multiply by 257 instead (`x | (x << 8)`). This allows the largest
converted u8 value to be 255 * 257 = 65535.
Fixes #1505.

Make `upcast_channel` use the whole range of u16 values.

---

src/image.rs

Avoids a possible panic from allocating more than isize::MAX bytes for a single Vec, but otherwise doesn't prevent attempts to do unreasonably large allocations.

Better handling of image size overflows

---

src/buffer.rs

This relands part of #1229 which added methods to `ImageBuffer` that return
`Option<&P>` and `Option<&mut P>` from `get_pixel[_mut]`-like methods. It does
not include adding methods to the `GenericImage` and `GenericImageView` traits.
Naming is still a concern #1243.

Add non-panicking get_pixel/mut methods to ImageBuffer

---

src/io/free_functions.rs

Switched order of lines so that file path is checked before file is created during `save()`.
Closes #1513 .
This change passes all tests in `cargo test`.
I'm a new contributor:

File path is now checked before creating file on save

---

README.md
src/buffer.rs
src/codecs/avif/decoder.rs
src/codecs/avif/encoder.rs
src/codecs/jpeg/encoder.rs
src/codecs/tga/encoder.rs
src/codecs/tga/header.rs
src/color.rs
src/dynimage.rs
src/lib.rs
src/traits.rs

Remove all handling of BGR and BGRA images, except for in ExtendedColorType. Users can trivially convert images just by swapping the red and blue components, but it is unclear whether they're even being used at all now.
Started as an experiment to see what it would take to remove ColorType::{Bgr8, Bgra8}, but it turns out that that the pixel structs are sufficiently entangled that you can't really remove one without the other.

Remove Bgr and Bgra color types

---

fuzz/fuzzers/fuzzer_script_exr.rs
src/codecs/farbfeld.rs
src/codecs/hdr/decoder.rs
src/codecs/openexr.rs
src/codecs/pnm/decoder.rs
src/dynimage.rs
src/io/free_functions.rs
src/io/reader.rs

While scrolling through the code, I noticed that `BufReader` and `BufWriter` are used more than expected. 
1. Sometimes, an already buffered reader or writer is buffered again. Where this is desired, we should add documentation that explains why this is useful. If not, we should remove the unnecessary buffering.
2. `BufRead` is an overly strict trait bound. Most of the time, we should use `Read` instead, with proper documentation. The `BufRead` trait has super specialized methods like `fn fill_buf(&mut self) -> Result<&[u8]>;`. Where these methods are not used, the trait bound is not required.
3. Whether a reader should be buffered or not is sometimes not documented

Lets talk about buffering

---

src/codecs/gif.rs

Resolves #1531.
This changes causes alpha=0 pixels in a GIF frame to be transparent in the output image instead of having them use the color from the previous frame. This behavior could be controlled via an option, but I think the new approach is what most users want/expect.

Fix GIF transparency

---

fuzz/fuzzers/fuzzer_script_exr.rs
src/buffer.rs
src/codecs/jpeg/encoder.rs
src/codecs/openexr.rs
src/dynimage.rs
src/io/free_functions.rs

Use the seekable writer to improve performance and to simplify code. Also, cleaned up some imports in the openexr module.
__The writers were not seekable, even though we had already merged seekable writers into `next`. I had to re-add seekable trait bounds to all methods.__ Maybe those changes got lost?
Modules that benefit from seekable writers, because they had to write to an intermediate `Cursor<Vec<u8>>` previously:
Closes #1489

Use seekable writer

---

.github/workflows/rust.yml

This should prevent CI failures and allow us to merge other pull requests

Don't run CI on rustc older than 1.46

---

src/image.rs

i used mime type assigned by [iana](https://www.iana.org/assignments/media-types/media-types.xhtml#image) for:
- avif
- jpeg
- png
- gif
- webp
- tiff
- bmp
- hdr
i used mime type value found on wikipedia for:
- tga,
- dds,
- ico,
- OpenExr,
- pnm,
i didn't find any mime type of farbfeld
close #1528 

create an `ImageFormat` from a MIME type

---

src/codecs/bmp/decoder.rs
src/codecs/tga/decoder.rs

Just a few random improvements I noticed could be made.

Improve usage of `Vec::extend`

---

src/lib.rs

I found that ImageReader::new(Cursor::new(...)) fails to determine the type of an image unless I also call `with_guessed_format()`.  This is clearer in the ImageReader docs, but not in the top-level examples.

Clarify use of ImageReader in top-level doc

---

src/imageops/sample.rs

A lot of time in resizing is spend on the float conversions. This is partially because `.round()` is slow but also because the type used for the rounding caused unnecessary overhead. This simplifies this, and adds some other performance improvements.
The first commit is a format (oops, I left one comment in. ), I dont know what your policy is on this in PRs. I kept this as a separate commit to make sure it would be easy to review.

optimise resize

---

src/codecs/tga/decoder.rs

Previously the `pixel_data` buffer was assumed to be the same length as the parameter buffer
passed to `ImageDecoder::read_image`. This PR puts a check in place to make sure that both 
buffers are the same length before attempting to copy one into the other, this prevents triggering
a panic when calling `slice::copy_from_slice`.
Note: All the other changes are due to `rustfmt` running when I saved the file. 
Fixes #1526

Add check on tga::decoder to prevent crash

---

src/dynimage.rs
src/error.rs
src/image.rs
src/io/free_functions.rs
src/io/mod.rs
src/io/reader.rs

I have given decoding limits another try based on the latest discussion from #938. 
The current design uses a non-exhaustive `Limits` struct with public fields to provide an interface for setting decoding limits. It also defines a `LimitSupport` that decoders can use together with `Limits::check_support` in order to check if they support all of the limits that are set in a backwards-compatible way.
In the documentation of `Limits` I have written a little bit about the difference between *strict* and *non-strict* limits. The idea being that with non-strict limits decoders that support them should set them but without excluding decoders that do not support limits. For strict limits only decoders that can uphold the limits should be used.
This PR does intentionally not provide any …

Decoding limits try 2

---

src/codecs/png.rs

- Add `Adaptive` to `codecs::png::FilterType` enum
- Make `Adaptive` the default `FilterType`
- Use `CompressionType::default` and `FilterType::default` in `codecs::png::PngEncoder::new`
png 0.17 includes the Adaptive filtering method for encoding which helps reduce file size.
I've updated the doc comments in `codecs::png::FilterType` and `codecs::png::PngEncoder::new_with_quality` which mentioned changing the filter type to adaptive filtering when it became available.

Add adaptive filter option to png encoder

---

src/codecs/dxt.rs
src/codecs/tga/decoder.rs
src/codecs/tga/encoder.rs
src/codecs/webp/vp8.rs
src/image.rs
src/lib.rs

In the same style as #1537 - a few random improvements I noticed could be made.
I haven't run a benchmark on these but:
* `encode_dxt_colors` gets called in a for loop so it's probably worth it to remove the `.to_vec()`
* The `Vec::split_to` optimization removes 2 allocations and 2 `memcpy`s
* [comparing](https://rust.godbolt.org/z/37aj341dn) `crate::copy_memory` with `slice::copy_from_slice` shows that they generate the same assembly
---

Reduce allocations and `memcpy`s

---

Cargo.toml
src/codecs/avif/encoder.rs

Bump ravif version from 0.7.0 to 0.8.0

---

src/codecs/webp/decoder.rs

webp: Do not panic on overflow if size is maximum

---

.github/workflows/rust.yml
fuzz-afl/.cargo/config
fuzz-afl/Cargo.toml
fuzz-afl/README.md
fuzz-afl/fuzzers/fuzz_pnm.rs
fuzz-afl/fuzzers/fuzz_webp.rs

Work around an issue due to new pass-manager, as mentioned here:
<https://github.com/rust-fuzz/afl.rs/issues/192#issuecomment-931803722>
This affords us some time (until LLVM 14 or 15 iirc) for a more
permanent fix to appear upstream.

Update afl to 0.10, fix run issue

---

src/codecs/pnm/decoder.rs
src/codecs/tga/header.rs

Closes: #1333 
> Fix clippy warnings, but these changes are not compatible with the current minimal rust version. See: [#1331 (comment)](https://github.com/image-rs/image/pull/1331#issuecomment-706098502)
Since now MSRV was bumped, thanks again for the original PR.

use matches!

---

Cargo.toml
Cargo.toml.public-private-dependencies
src/codecs/tiff.rs
src/utils/mod.rs

Among other things, adds support for TIFF images with Deflate tag (commonly produced by tools like imagemagick) and improves memory consumption.

Upgrade TIFF to 0.7

---

src/math/utils.rs

Fix resize_dimensions to round values instead of truncating them.

---

src/buffer.rs
src/color.rs
src/traits.rs

The 'from traits' part is the breaking change. Downstream consumers
could have previously made use of this additional bound.
This is not required, we never utilize types `&'static [Subpixel]` or
similar and if we would then it could be a local bound. But the bound is
infectious in that it requires placing several additional bounds in
every place where the `Pixel` trait is being used.
This does not clean up all usage sites (in `imageops`).

Remove 'static bound from traits and impls

---

src/dynimage.rs
src/imageops/colorops.rs
src/imageops/mod.rs

Fix for DynamicImage::grayscale not preserving the alpha channel for input images that have an alpha channel. Fixes issue #1466 
[src/imageops/colorops.rs]
Made new functions grayscale_alpha and grayscale_with_type_alpha which do the same as their non-alpha counterparts except they preserve the alpha channel
Uses LumaA rather than Luma for the pixel type
Uses .to_luma_alpha() rather than .to_luma()
[src/imageops/mod.rs]
Expose the new functions from the imageops module so we can access them in src/dynimage.rs
[src/dynimage.rs]
Updated DynamicImage::grayscale method to use grayscale_alpha/grayscale_with_type_alpha instead of the non-alpha counterparts when the input format has an alpha channel
Added tests to ensure that the alpha channel is discarded/preserved appropriately based on the …

Issue 1466

---

src/imageops/mod.rs

Make imageops::{overlay, replace} take coordinates as i64's

---

src/lib.rs

This is required for end user implementions of e.g. generic PNG encoding using `P::COLOR_TYPE`.

Export PixelWithColorType

---

src/codecs/jpeg/encoder.rs

Makes JpegEncoder more consistent with other encoders. Should hopefully cause minimal breakage, because Write is implemented for mutable references to writers:
```
impl<'a, W: Write + ?Sized> Write for &'a mut W
```
Fixes #1605

Have JpegEncoder::new take an owned writer

---

src/dynimage.rs

Fixes issue #1552 
Allows structures that contain a DynamicImage to auto-derive the Default trait. DynamicImage will default to a zero sized Rgba8 image.
Not sure if the pixel format actually chosen as the default has any effect though, since the user would have to actually create a new DynamicImage and perform the allocation when they wanted to use it anyway.
Added a simple test to ensure that this case can be performed (auto-deriving Default on a wrapping struct)

Added Default implementation to DynamicImage

---

README.md
examples/concat/main.rs
examples/decode.rs
examples/scaledown/main.rs
examples/scaleup/main.rs
src/buffer.rs
src/dynimage.rs
src/flat.rs
src/image.rs
src/lib.rs

Splits `view` and `sub_image` from the main image traits to a different set of traits, removing the need for `InnerImage` associated types. Also bounds the relevant method that prevented the current implementation from being used as a `dyn` trait object.
Related: #1118, #1406

Dyn generic image

---

Cargo.toml

fixed a fuzzing panic by validating the tile size earlier
and removed an unused field

update exr version to 1.4.1

---

src/dynimage.rs

As suggested by [@5225225](https://github.com/image-rs/image/issues/1433#issuecomment-963592987). Downstream code exhaustive matching on the current variants should use or petition for methods that extract into one types instead. Of particular note and example I'd like to point out [`as_bytes`] which essentially promises that all future variants will only contain matrices of trivial and padding-free channel types.
Overall, it's expected that this allows `0.24` to be more stable while we may discuss how to introduce half-float, or non-rgb combinations.

Make DynamicImage non-exhaustive

---

tests/regression.rs

Fixing the issue that I just noticed in the regression test, #1633
My first inclination was to just force it to load the images as `ImageFormat::Bmp`, which is what I've done here, but it would also be valid to just make a subdirectory in `tests/images/bmp/images/bad` and put the bad images there, with a proper `.bmp` extension.
This feels cleaner than creating a five-layer-deep directory soup where each folder has a special, different meaning though.
---
Also, because this is my first contribution :)

tests/regression.rs: force bad_bmps test to load files as Bmp, fix #1633

---

src/codecs/ico/decoder.rs
src/codecs/ico/encoder.rs
src/codecs/png.rs

As mentioned in the second step of https://github.com/image-rs/image/issues/884#issuecomment-985755468.
Makes it possible to use a pre-encoded .png or .bmp file without having to first decode it. Also opens the ability to use something like oxipng to those who want to have fun with extremely small favicons :smiley: 
I haven't added any tests yet.
---

Make it possible to provide a pre-encoded image to the .ico encoder

---

src/codecs/bmp/decoder.rs

BMP has a bunch of flexibility in how the components are arranged within a pixel. Reversing this encoding is rather expensive, but if the chosen arrangement happens to match the default then we can decode much faster.
The `round_trip_single_pixel_rgba` confirms that the component order is still correct.

Optimize decoding of certain RGBA BMP files

---

src/io/free_functions.rs

Add compatibility with .avif files created via libheif

Add new magic byte

---

src/color.rs
src/traits.rs

This is an attempt to fix #1214, using the `Enlargeable` trait to
select a suitable type for the calculation in `rgb_to_luma` and
`bgr_to_luma`.
Integer pixel types will use suitable integer pixel types for the
calculation, while floating point pixel types will use floating point
types.
This PR also provides the `Enlargeable` trait for all `Primitive`
types (luckily, `Primitive` is not implemented for 128 bit numeric
types).
The `Color` implementation of all library-defined structs is then
restricted to a subset of Primitive channel types. This is necessary to
allow its conversion operations to utilize the private `Enlargeable`.
Notably however we _relax_ the type itself to not utilize any trait
bound. It's a simple wrapper around an array now.
Rebase of #1215 which was auto-closed due to …

Use enlargeable types in to_luma functions.

---

src/codecs/dds.rs
src/lib.rs

https://github.com/image-rs/image/issues/1623 describes the motivation:
> > Right now our GPU compressed texture handling is really not all that great. For decoding we don't support any of the newer formats like BC6, BC7 or ASTC, And for encoding, our code is slow, low quality, and doesn't support any of the newer formats.
> 
> As a result, pretty much any use of the module would be better served by squish-rs which implements faster and higher quality encoding (though be sure to use 2.0.0-beta1 or later to get the recent bugfixes).
> 
> Additionally, unlike the other codecs, DXT is not actually an image file format but rather a compression format. This distinction matters for instance because it means that the DxtDecoder::new() has to be passed the image metadata unlike all our other …

Deprecate DXT support

---

Cargo.toml
Cargo.toml.public-private-dependencies
src/math/utils.rs

Extract and rebase all the version upgrades for 0.24. This ensures we have patch notes in one single commit chain, not interrupted by fixes and upgrades.

Upgrade and fixes for 0.24

---

CHANGES.md
Cargo.toml

Changelog for v0.24

---

CHANGES.md
Cargo.toml

We should probably release a version incorporating https://github.com/image-rs/image/pull/1674 sooner rather than later.

0.24.1 bugfix release

---

.github/workflows/rust.yml

Run tests with jpeg's "platform_independent" feature to get deterministic results.

Fix CI failure

---

src/codecs/dds.rs

Allows the DDS decoder to load DXT-format files with the additional DX10 header, as described in <https://docs.microsoft.com/en-us/windows/win32/direct3ddds/dx-graphics-dds-pguide#dds-variants>.
The DX10 header struct was taken from [Microsoft's DX10 docs](https://docs.microsoft.com/en-us/windows/win32/direct3ddds/dds-header-dxt10), and the equivalent DXT1/3/5 DXGI types were taken from [here](https://docs.microsoft.com/en-us/windows/win32/direct3d11/texture-block-compression-in-direct3d-11) and [here](https://docs.microsoft.com/en-us/windows/win32/api/dxgiformat/ne-dxgiformat-dxgi_format).

Add DX10 extended header support for DDS

---

src/codecs/png.rs
src/dynimage.rs

While both are correct (depending on which side of the pond one lives), most documentation uses gray instead of grey, and, the imageops also uses the method name grayscale().
I became aware of the two different spellings used when reading the DynamicImage::grayscale() docs, where both variants were used within the same documentation item :).

Use consistent spelling of the word 'gray' in the docs

---

CHANGES.md
src/buffer.rs
src/dynimage.rs

Output formats, but mainly PNG, may expect the byte buffer to be
precisely sized according to the image descriptor. The `ImageBuffer`
implementation permits its underlying container to be larger than this
for multiple reasons, and won't check this property in `from_raw`.
Hence, the actual size may be too large. This mismatch can cause
encoding to fail for a curious reason:
failed to save: IoError(Custom { kind: Other, error: "wrong data size, expected 1288872 got 1289808" })
Too much data should never be harmful here.
We avoid this by pre-selecting only the relevant portion of the
underlying container.

Compensate for overfull buffer in write

---

.github/workflows/rust.yml
Cargo.toml

This removes the need for `--features jpeg/platform_independent` when
using cargo test
This was a point of confusion when developing locally. I still need to test that it actually doesn't get enabled when using this as a normal dependency, but it shouldn't, with the resolver 2.

Enable the platform_independent feature under test

---

.github/workflows/rust.yml
deny.toml

[cargo-deny](https://github.com/EmbarkStudios/cargo-deny) is an amazing tool that protects from:
* duplicated crates (code bloat)
* copy-left licenses in the dependency tree
* RUSTSEC advisories
In this case it discovered the duplication of `jpeg-decoder` and `miniz_oxide`, caused by the `tiff` and `flate2` crates. ~Until new releases of `tiff` and `flate2` are published I opted to ignore these duplicated crates in the `deny.toml` file.~ **EDIT:** new versions of `tiff` and `flate2` have been published, removing the duplication.
Adding cargo-deny to the CI will prevent more dependency duplication, hence this unsolicited PR.
--- 

cargo-deny

---

src/codecs/avif/decoder.rs

e3f81a4d4826af82d623d48cf1c6fd72c688df06 introduced a byte swap conversion from BGRA to RGBA, which can be eliminated if we ask dcp to convert directly to RGBA.

avif-decoder: Convert directly to RGBA

---

src/codecs/tiff.rs

The tiff crate imposes default limits on decoding, so if the user attempts to override them it is important that we pass that on to the backend. This PR implements `TiffReader::set_limits` to do that.
As an example of things going wrong, if we currently try to load [this TIFF file](https://github.com/image-rs/image/files/8628415/large.zip):
```rust
#[test]
fn large_tiff() {
let mut reader =
crate::io::Reader::open("/home/jonathan/tmp/large.tiff").unwrap();
reader.no_limits();
reader.decode().unwrap();
}
```
We get this error.
```
---- image::tests::large_tiff stdout ----
thread 'image::tests::large_tiff' panicked at 'called `Result::unwrap()` on an `Err` value: Limits(LimitError { kind: InsufficientMemory })', src/image.rs:1845:25
```
(I'm not adding this as a new testcase because neither …

Implement TiffReader::set_limits

---

src/color.rs

This optimizes the blend method of Rgba<T> by checking for two very common cases. I didn't benchmark this function specifically, but I got my program that makes heavy use of it to be around twice as fast with this change.
Something I'm not sure about is the `other.0[3].to_i32().unwrap() == 255`, since it looks like 255 might not always be the maximum alpha?
---

Optimize Rgba blend

---

src/codecs/bmp/encoder.rs

Origin: <https://salsa.debian.org/rust-team/debcargo-conf/-/blob/master/src/image/debian/patches/avoid-test-overflow-32-bit.patch>
Reviewed-By: Andreas Molzer <HeroicKatora@users.noreply.github.com>
Last-Update: 2022-05-26
Closes: #1707, Thanks for the patch.
---
~~I had some trouble with `git am` because apparently it _must_ be ran interactively if it every tries to access gpg, and will fail with an error that indicates it doesn't find committer credentials otherwise. A bit confusing.~~ No, still sometimes works and sometimes doesn't. Im super confused.

Dont run huge_files_return_error test on 32-bit to avoid overflow

---

Cargo.toml
src/codecs/openexr.rs
src/image.rs
src/io/free_functions.rs
src/lib.rs

Supposed to fix: #1715 
Not certain if this works correctly, at least it appears to not make a difference for little endian architectures. We would do well to test on a big-endian platform in CI in any case.
cc: @botovq

Restrict openexr to little endian platforms

---

src/codecs/webp/extended.rs

There were two errors with the implementation with the extended WebP images that affected lossy(VP8) WebP images without alpha
1. Tried to read the VP8 chunk header twice
2. Tried to fill a rgbaimage buffer with rgbimage size
This PR fixes those issues, so the image in #1712 is decoded successfully.

Fixes some lossy extended WebP issues

---

src/codecs/gif.rs

Closes https://github.com/image-rs/image/issues/1724
Corrects the link which goes nowhere to latest image-gif doc.
Verified the link by generating the docs via `cargo doc` and clicking on it
---

Fix broken speed explanation link in doc for GifEncode::new_with_speed function

---

src/codecs/pnm/decoder.rs
src/imageops/colorops.rs

Greetings of the day @fintelia,
I've fixed the issue as suggested, kindly review the pull and suggest changes if any.
Thanks & Regards
@shikharvashistha
Fixes : #1616

Added overflow handling to multiplication of width and components

---

src/dynimage.rs

Returning width/height is what feels like the norm to me, but it's not specified [in the public docs](https://docs.rs/image/0.24.2/image/fn.image_dimensions.html) – making it explicit avoids somebody having to guess or experiment.
If you trace it through the codebase, this eventually ends up calling `dimensions()` on an ImageDecoder, which [the README says is a (width, height)](https://github.com/image-rs/image/blob/144ea599fcda523956604b3733751beee6b8d5cb/README.md#the-imagedecoder-and-imagedecoderrect-traits) tuple.

docs: Specify the width/height order from image_dimensions

---

src/buffer.rs

Hello, I'm new to Rust and decided to try hacking on some other projects I intend to use as part of my own. This stemmed from a failed attempt to optimize the resize() function by using generic parameters for kernels instead of a boxed function which turned out to have no impact at all, however I noticed from a profile run that the code was spending a lot of time in get_pixel, and inlining it has a >2x speedup on resize(), and no doubt more speedups elsewhere in the code
before (on an M1 Max):
```
Scaled by near in 7 ms
Scaled by tri in 97 ms
Scaled by cmr in 178 ms
Scaled by gauss in 265 ms
Scaled by lcz2 in 265 ms
Thumbnailed to 20 in 22 ms
Thumbnailed to 40 in 22 ms
Thumbnailed to 100 in 24 ms
Thumbnailed to 200 in 25 ms
Thumbnailed to 400 in 22 ms
```
After:
```
Scaled by near in 5 ms …
```

inline get_pixel and get_pixel_mut for >2x speedup

---

src/imageops/sample.rs

Addresses #1738 by checking if resizing is to the same size the image already is. 
there's a lot more optimizations that could be made here, such as detecting integer scaling or a Pillow-style ["reduce gap"](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.resize) method (maybe as an additional filter mode, since it only makes sense for bilinear). However from #1718 it looks like you may be planning a refactor of the backing data structures for pixels?

Check if resizing to the same size

---

.github/workflows/rust.yml
Cargo.toml
src/codecs/openexr.rs
src/image.rs
src/io/free_functions.rs
src/lib.rs

Add big-endian CI

---

src/traits.rs

There's no Rgba::new method. Fixes #1782

Fix a deprecation message

---

fuzz/fuzzers/fuzzer_script_exr.rs

Fix unbound allocation in fuzzer_script_exr

---

src/codecs/png.rs
src/lib.rs

Fixing clippy warnings:
- Allowed unused doc comments (not working on extern)
- Fixing deprecated enum usage in PNG compression

Fixing clippy warnings

---

src/buffer.rs

fix: implement size_hint for ImageBuffer iterators

---

.github/workflows/rust.yml
Cargo.toml
README.md
src/codecs/webp/encoder.rs
src/codecs/webp/mod.rs
src/image.rs
src/io/free_functions.rs
src/lib.rs

This PR adds `WebPEncoder`, which wraps the [Simple Encoding API](https://developers.google.com/speed/webp/docs/api#simple_encoding_api) from the native libwebp library using the [webp](https://crates.io/crates/webp) crate.
The encoding functionality is gated behind a new `webp-encoder` feature, which is not enabled by default and completely separate from the `webp` feature. This follows the convention of the current `avif`/`avif-encoder`/`avif-decoder` features which are separate due to the native depedency.
With `webp-encoder` enabled, the following just works now:
```rust
let im = image::open("Lenna.png").unwrap();
im.save("Lenna.webp").unwrap();
```
The above defaults to a lossy encoding value of 80. The value was chosen since `image` defaults to 75 for JPEG encoding, and [this blog …

Add WebP encoding support

---

src/codecs/bmp/encoder.rs

Fixes  #1708
From @plugwash in #1708, file_size calculations when writing BMP did not check for overflow. This would cause images with slightly less than 2^32 bytes of data to either panic in debug mode or have a bogus file_size in release mode.
This PR makes the addition checked and errors on overflow.

use checked_adds in the bmp writer when calculating `file_size`

---

.github/workflows/rust.yml
deny.toml
src/dynimage.rs

Fix warnings and CI issues

---

src/dynimage.rs

Should fix the issue: https://github.com/image-rs/image/issues/1738
Not super happy with it since I'm cloning self but I didn't want to change the return type to &DynamicImage e.g.
Let me know if you have a better idea on how to make this more efficient :)

Check dimensions of dynamic image before resizing it

---

Cargo.toml
src/codecs/png.rs
src/io/free_functions.rs

This isn't the most elegant solution given that other decoders use `ImageDecoder::set_limits`, but idiosyncrasies of the PNG format make that interface non-ideal. Specifically, finding out whether the image is animated (contains an acTL chunk) or has a "simple alpha channel" (contains a tRNS chunk) potentially requires scanning a nearly unbounded number of chunks. Worse, we currently don't have a Seek bound on the reader, so we have to _store_ all the chunks we read in case we need them later.
Fixes #1788

Add PngDecoder::with_limits

---

Cargo.toml

Per @HeroicKatora 
> It seems like jpeg had some incompatible changes in this version bump.
Reviewing separately from https://github.com/image-rs/image/pull/1819/

Bump the 'jpeg' version requirement to 0.3.0

---

CHANGES.md
Cargo.toml

I hope this isn't too forward.  I am eager to get panic fixes in the tiff and jpeg crates, as well as the unpublished fixes in this crate. 
Based on these lines in CHANGES.md, I bumped the minor/patch version instead of the major version:
https://github.com/image-rs/image/blob/d026f701b603b9781cd33954fe05b1b6da5ee785/CHANGES.md?plain=1#L75-L76 
So, 0.24.5 instead of 0.25.0.
Also increase the version requirement for
- `tiff` to 0.8.0
- `jpeg` to 0.3.0
I believe I may be a first time contributor for this crate and from my personal email/computer, so:

Changes and release notes for 0.24.5

---

deny.toml

The skip-tree entry should no longer be needed.

Remove exception for old flate2 version

---

Cargo.toml
src/codecs/avif/encoder.rs

As noted in #1760, AVIF encoding is very slow. In looking at _why_, I noticed that the default encoder settings are very different from what the `cavif` CLI provided by upstream uses - in particular, upstream documentation suggests that a quality setting of 100 is not a useful configuration.
The majority of the changes here are to upgrade the `ravif` dependency. The images I was using for testing appear to compress _significantly_ better using the new version.
The project requests this statement to be made:
> I license past and future contributions under the dual MIT/Apache-2.0 license,
> allowing licensees to choose either at their option.
I would like to add that I do not believe the changes in question to be significant enough to warrant copyright.

AVIF encoder changes.

---

README.md

Proposing a change to make `Rgba` type definition similar to how `LumaA` is defined. It makes it easier to distinguish the difference with `Rgb` type.

Consistent definition of Rgba

---

src/image.rs

Hey, this is my first contribution here!
It took me some trial and error to realise that the JPEG output quality is clamped at 100 and not scaled from the u8 max of 255. Thought that expanding on the documentation here might be useful. Any suggestions for better wording would be great.
Cheers!
---

expand on documentation for ImageOutputFormat::Jpeg quality

---

src/flat.rs

Just require Pixel and not PixelWithColorType to create views etc.
At first glance - the PixelWithColorType seems overly restrictive and the trait is merely used here to populate the Error::WrongColor return on failure. 
Test seems to pass:
```
running 36 tests
test src/buffer.rs - buffer_::ImageBuffer (line 648) - compile ... ok
test src/buffer.rs - buffer_::ImageBuffer<FromType,Container>::convert (line 1358) - compile ... ok
test src/codecs/gif.rs - codecs::gif (line 9) - compile ... ok
test src/flat.rs - flat (line 9) - compile ... ok
test src/buffer.rs - buffer_::ImageBuffer (line 631) - compile ... ok
test src/animation.rs - animation::Delay::from_saturating_duration (line 129) ... ok
test src/animation.rs - animation::Delay::from_numer_denom_ms (line 112) ... ok
test src/image.rs - …
```

feat: less restrictive FlatSamples layout - 

---

src/dynimage.rs

This ensures that `ColorType` and `DynamicImage` variants don't accidentally get out of sync

Exhaustively match in ColorType -> DynamicImage conversion

---

src/codecs/ico/decoder.rs

[Wikipedia claims](https://en.wikipedia.org/wiki/ICO_(file_format)#Structure_of_image_directory) that a value of 0 for the width or height in an image directory means 256 _or more_. This crate previously assumed it meant exactly 256. If anyone knows of a more definitive spec reference, that would be nice to include.
Fixes #1836

Support ICO files with dimensions larger than 256

---

src/codecs/avif/decoder.rs
src/codecs/jpeg/decoder.rs
src/codecs/png.rs
src/image.rs

---
Giving this a go. Not sure why `&mut self` was suggested in the issue
Closes #1832

Add ICC profile to ImageDecoder

---

Cargo.toml
Cargo.toml.public-private-dependencies
src/codecs/hdr/decoder.rs

As discussed in https://github.com/image-rs/image/issues/772#issuecomment-1382406241. This also makes it work on WASM.
---

Remove multithreading in HDR decoding

---

.github/workflows/rust.yml

https://github.com/mcountryman/simd-adler32/pull/9 has been resolved, so we can remove the workaround.

Remove workaround for CI issue

---

src/codecs/webp/decoder.rs
src/codecs/webp/extended.rs

Add webp has_animation predicate

---

src/codecs/webp/decoder.rs
src/codecs/webp/extended.rs

Fixes #1906.
I'm not sure I chose the right error type, tell me if there's one that suits this type of error better, maybe `UnsuportedError` ?
---

Add option to set the background color of animated webp images

---

src/codecs/avif/encoder.rs

Basically to allow some control over used system resources dedicated to encoding images.
---

AvifEncoder: Add with_num_threads()

---

src/buffer.rs

References: #1922
This is essentially the same thing as `ImageBuffer::write_to()`, but it accepts an encoder. This is safer and more ergonomic than calling `ImageEncoder::write_image()` directly because it removes the guesswork of deconstructing the ImageBuffer manually.
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

ImageBuffer: add write_with_encoder() method

---

src/image.rs

This adds `to_mime_type` as suggested in #1722.
I attempted to imitate the style of other comments, including having an example.
Since I found a MIME type for all of the formats, I made the method not return an `Option`, but I can change that if you prefer.
Fixes #1722.

Add to_mime_type for ImageFormat

---

Cargo.toml
src/codecs/avif/decoder.rs

```bash
cargo build --release --features avif-decoder
```
with
```bash
$ cargo --version && rustc --version           
cargo 1.71.0-nightly (13413c64f 2023-05-10)
rustc 1.71.0-nightly (ce5919fce 2023-05-15)
```
yields 
```bash
$ cargo build --release --features avif-decoder
Blocking waiting for file lock on package cache
Updating crates.io index
Blocking waiting for file lock on package cache
Compiling mp4parse v0.12.0
error[E0277]: cannot multiply `u64` by `NonZeroU8`
--> /home/john/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mp4parse-0.12.0/src/lib.rs:2547:62
|
2547 |                 static_assertions::const_assert!(<$lhs>::MAX * <$rhs>::MAX <= <$output>::MAX);
|                                                              ^ no implementation for `u64 * NonZeroU8`
...
2557 | …
```

fix: repair for rustc rustc 1.71.0-nightly (ce5919fce 2023-05-15)

---

src/codecs/dxt.rs

Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=56032&q=label%3AProj-image-rs

Fix panic on empty dxt

---

src/codecs/webp/decoder.rs
src/codecs/webp/extended.rs

Issue #1873 shows a number of real-world WebP images fail during decoding. For almost all of these, this is because they contain ["unknown chunks"](https://developers.google.com/speed/webp/docs/riff_container#unknown_chunks) at the end of the file. Those unknown chunks were reported as errors, while the specification says they should be ignored at the end of the file. This PR changes the decoder's behavior accordingly.
One of the images provided in #1873 still fails to decode after this PR. This is an animation file, so it might be related to that the standard also specifies that unknown chunks should be ignored at the end of animation "ANMF" chunks, which I don't think is currently implemented. However, running `webpmux -info` on this file resulted in `Failed to create mux object from …

webp: Allow unknown chunks at the end of the file

---

src/codecs/hdr/decoder.rs

Some types weren’t in backquotes, making `rustdoc` interpret them as unclosed HTML tags.
Also unify the backquote format to a single one for single words.

Escape types more correctly in hdr docstrings

---

src/codecs/webp/extended.rs

In case of an animated WEBP image, which contains frames of a smaller size than an image's canvas, the buffer of a whole image is bigger than the buffer of the first frame. This results in a panic while trying to copy a frame buffer to an image buffer. This is applicable to a case when a user wants to create an image from a file or an in memory buffer like this:
```rust
let path = "/some/path/to/animated_transparent.webp
let mut buffer = Vec::new();
let _ = std::fs::File::open(path)?.read_to_end(&mut buffer);
let img = image::load_from_memory(&buffer)?;
let size = img.dimensions();
let buffer = img.to_rgb8().into_raw();
```
This fix checks if the first frame is of a smaller size, and in this case draws a subimage to a canvas.
I have this issue in my personal case, but I believe it also …

Fix for a wrong buffer size with an animated WEBP

---

src/codecs/webp/extended.rs

If the frame's width or height are larger than the canvas size, or even if they are smaller, but they have an x or y offset + width/height, that gets larger than the canvas width/height, than the code will panic on [extended.rs#268](https://github.com/image-rs/image/blob/master/src/codecs/webp/extended.rs#L268), because of how Index is implemented for ImageBuffer.
The fix for #1960. The logic basically crops a frame which is beyond a canvas.

Fixes potential panic on out-of-bounds if a frame is larger than a canvas

---

src/imageops/mod.rs
src/imageops/sample.rs

***WIP***
Not sure whether this should directly go on `GenericImageView`, and where the enums should go.
Also need to add tests but put the general idea up for review.
---
Adds a way to sample images in [0,1], which is a common use case in graphics.
Currently adds non-exhaustive enums based on OpenGL's that allow for simple sampling of nearby coordinates.
Nearest sampling can produce artifacts depending on the sampling resolution of the UV whereas bilinear will smoothly interpolate.
Addresses #1905

Add sampling using [0,1] for `GenericImageView`

---

src/dynimage.rs

Fixed broken doc link to `ImageOutputFormat` in for `write_buffer_with_format` doc page.

Fix doc link for ImageOutputFormat

---

src/imageops/mod.rs
src/imageops/sample.rs

This looks very similar to the prior PR, but I'm not sure if the two sample modes should be merged into one?
That was originally why I had included an enum to indicate which to perform, but it's fine to keep them separate as well.

Add sample/interpolate nearest

---

.github/workflows/rust.yml

A couple tweaks to the CI workflow.
Most notably, it now runs way fewer feature permutations. The nightly/beta/MSRV toolchains are only run once each with all the default features and (almost) all other features enabled.

CI improvements

---

CHANGES.md

Small typo in CHANGES.md

---

src/buffer.rs

I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

fix: typo in buffer.rs

---

Cargo.toml
src/codecs/webp/encoder.rs
src/codecs/webp/mod.rs
src/image.rs
src/io/free_functions.rs
src/lib.rs

The goal of this PR is to have "good enough" pure-Rust webp encoding to enable it by default and remove our dependency on libwebp.
My plan is to completely ignore lossy webp encoding (we already have pure-Rust lossy jpeg and avif encoders) and only focus on lossless mode. ~~Right now, the code is able to produce valid lossless webp's, but they're completely uncompressed. Actually compressing the input will require building huffman trees based on symbol frequency.~~
I have however implemented hard-coded "subtract green" and "predictor" transforms which should make the data at least somewhat compressible. That's in contrast to libwebp which tries a whole bunch of different transform configurations to see what produces the best compression. Nonetheless, it might be enough to get compression …

Webp encode

---

Cargo.toml
src/animation.rs
src/codecs/gif.rs
src/codecs/png.rs

This removes `num-rational` as a dependency. As it turns out, `num-rational`, based on which features are active, can very easily end up on the critical path during compilation, meaning that it is the crate that determines how long it takes to compile the `image` crate. This is because `cargo` can parallelize compilation of many crates, but crates with a long dependency chains (rather than wide), are the ones that in the end determine the compilation speed. This is one of the learnings of the `serde` drama, where it has been noticed that allowing `serde` and `serde_derive` to compile in parallel reduces its long dependency chain, resulting in faster compile times. This introduces the same kind of optimization here, where for all the following features, `num-rational` turns out to be the …

Remove `num-rational`

---

.github/workflows/rust.yml

The MIPS targets are broken and partially don't come prebuilt anymore for those reasons. PowerPC is a more stable architecture for big endian.

Replace MIPS targets with PowerPC

---

src/dynimage.rs

---
Use case: I have a `DynamicImage` and I want to make a new one of the same type as the existing one but with a different width and height.
Currently this requires a large match.
Alternate solutions: Create another declarative macro for this specific use case.
However, I think `DynamicImage::new(w, h, old_image.color())` looks better and is more ergonomic than another macro.
I am open to modifying this PR to fit any needs or invariants I was blind to.

Feature: Add a new constructor that takes a ColorType

---

Cargo.toml
src/dynimage.rs

Upgrade to the 2021 edition. Also switch to an include-list of files to upload to crates.io, rather than the reverse.

Upgrade to 2021 edition

---

src/codecs/dds.rs
src/codecs/dxt.rs
src/codecs/png.rs
src/codecs/tga/decoder.rs
src/image.rs

In preparation for removal of the methods in https://github.com/image-rs/image/pull/1869.
Associated tracking issue: #1989

Deprecate incremental decoding

---

src/flat.rs

Clarify that `SampleLayout::in_bounds_index` has unspecified behavior for invalid indices

---

src/codecs/avif/encoder.rs
src/codecs/bmp/encoder.rs
src/codecs/farbfeld.rs
src/codecs/ico/encoder.rs
src/codecs/jpeg/encoder.rs
src/codecs/openexr.rs
src/codecs/png.rs
src/codecs/pnm/encoder.rs
src/codecs/qoi.rs
src/codecs/tga/encoder.rs
src/codecs/tiff.rs
src/codecs/webp/encoder.rs
src/image.rs

Fixes #2002
Fixes #2003
Fixes #2004 
Fixes #2006

Make ImageEncoder::write_image assert that dimensions are valid

---

src/codecs/png.rs

The `Result` return type was chosen so that the method can return I/O errors once the PNG decoder no longer reads all metadata in the `new()` method. And an `f64` was used so that all gamma values can be exactly represented (PNG encodes the value as a fixed precision decimal stored as a u32 which doesn't directly map to a f32).
cc: @anforowicz 
Fixes #2001

Add PngDecoder::gamma_value method

---

src/codecs/openexr.rs

use more high-level function `pod_read_unaligned` to read [f32;3] array instead of manually constructing it component by component
should be completely backwards compatible

reduce low-level byte fiddling in openexr encoder

---

src/codecs/png.rs

Add missing 'of' in PngEncoder::new_with_quality docs

---

src/image.rs

Add functions to enumerate all ImageFormat, and determine availability based on configured feature flags.
Example Usage:
```
let available_extensions = ImageFormat::all()
.filter(ImageFormat::reading_enabled)
.flat_map(ImageFormat::extensions_str)
.collect();

#1994 - Support for iterating enabled image formats

---

src/buffer.rs
src/image.rs
src/imageops/sample.rs

cc @thdusdl1219
Closes #2017, #2016, #2015
If you found these overflows using a compiler tool, maybe it's worth linking to it so they can be found easily in the future by crate authors.

Fix overflows

---

Cargo.toml
src/codecs/avif/decoder.rs

Note: `dcp::initialize` no longer needs to be called, as its global state is [initialized automatically when required](https://github.com/aws/dcv-color-primitives/pull/78).

Bump dcv-color-primitives to 0.6.1

---

src/codecs/avif/decoder.rs

Issue location:
`src/codecs/avif/decoder.rs` line 43 and 50
Currently, when `send_data` is called, its non-fatal error variant `Again` is treated as a fatal one, where this may be treated by `send_pending_data`, as mentioned by the [dav1d-rs docs](https://imgur.com/a/itNVERV) (dav1d-rs docs [fail to build](https://github.com/rust-av/dav1d-rs/issues/45) so i used this screenshot from my local build).
https://github.com/image-rs/image/pull/2023 addresses this issue as well, but does not handle the case of Alpha channels and only calls `send_pending_data` once.

Handle non-fatal error dav1d::Error::Again

---

src/codecs/webp/extended.rs

Previously, animated WebPs could take some time
until they started playing and would consume more memory.

webp: Decode animations frame by frame

---

src/codecs/pnm/decoder.rs

Some formats allow to specify a maximum value for samples. Before, samples were not scaled respective to this white point, decoding some images incorrectly dimmed.
I think the tests were wrong before. But I'm not 100% confident since I haven't found something to test this format in practice.
Comparison of `image-rs` and correct rendering.
```
P3 3 3 20
20 0 0
0 20 0
0 0 20
20 20 0
0 20 20
20 0 20
20 20 20
0 0 0
0 0 0
```

pnm: Scale samples according to specified maximum

---

Cargo.toml
src/buffer.rs
src/buffer_par.rs
src/lib.rs

This adds variants of the `Pixels`/`PixelsMut`/`EnumeratePixels`/`EnumeratePixelsMut` iterators that implement `ParallelIterator`/`IndexedParallelIterator` from rayon, as well as a `from_par_fn` function on `ImageBuffer`. This will allow large image buffers to be manipulated with multi-threading easily. Everything is also under a new optional `rayon` feature flag. This PR doesn't currently do it, but it might be worth considering re-exporting rayon somewhere.

Add `rayon` parallel iterators

---

src/codecs/farbfeld.rs

I noticed that you are using the `byteorder` crate to convert the bytes between different representations, Which a thing can be done with the built-in methods like `to_le_bytes` and `from_le_bytes` since Rust 1.32.
So I updated the Farbfeld encoder and decoder to use them. However, we still have to depend on `byteolder` 
crate since other encoders/decoders like `webp`, `tga`, `pnm` and `ico` using its methods, but I can work on that if this PR gets accepted.

refactor(farbfeld): use the built-in methods to convert the bytes between different representations

---

src/imageops/sample.rs

This PR fixes the crate's current implementation of the unsharpen filter, which currently does not work in the intended way. Normally, in order to calculate the unsharpen filter, the following steps are taken:
- a blurred version of the image is generated
- that version is subtracted from the original, giving us their difference, that can be either negative or positive.
- the difference is filtered by a minimum `threshold` parameter, so that *absolute* difference values that lie below a certain limit are not used in the filter
- the filtered difference is multiplied by an `amount` parameter, which controls the strength of the filter (this PR does not add that parameter)
- the result of that is added to the original image
The current way this is done doesn't take into account that the …

Fix wrong implementation of unsharpen filter

---

src/buffer.rs

Allows for generically converting from a dynamicImage. This is something that would be handy to have in another project, and I realized it would be easy to add myself.

implement From<DynamicImage> for all image types

---

src/imageops/sample.rs

- Remove usage of `Array::map`,
- make some math more clearly independent of other lines
- change `assert` to `debug_assert`
- change some flops to integer ops
- Flip order of storage for samples from [RGBA; 4] to [4R, 4G, 4B, 4A].
new:
https://rust.godbolt.org/z/GzMsefhPY
old:
https://rust.godbolt.org/z/M67Kx3hWd

Optimize interpolate_bilinear

---

src/codecs/gif.rs

Fix `GifDecoder::with_limits` to raise an error when limits are exceeded

---

src/error.rs

Based on the feedback from https://github.com/image-rs/image/issues/2092#issuecomment-1888417160:
> The error message could be improved, since it makes the user think they have a RAM problem. My team ran into this same issue this week.

Clearer error messages for limit errors

---

tests/limits.rs

TIFF decoding actually allocates three times the image's size:
* a buffer for the raw (potentially compressed) chunk
* an intermediate buffer to return from the tiff crate to the image crate
* the buffer buffer allocated within the image crate

Correct limits test for TIFF

---

src/codecs/avif/encoder.rs

Fix incorrect documentation of AvifEncoder::new_with_speed_quality

---

src/codecs/png.rs

`chunks_mut` can return chunks with sizes 1 or 2, while `chunks_exact_mut` always returns chunks of size 2. This should result in better codegen.
This certainly could be vectorized further, but this codepath is only taken for 16-bit images which are uncommon, so I'm not going to invest a lot of my time into optimizing it.
In the current code a chunk of size 1 being returned would result in a panic, so this should not break anything.

Use `chunks_exact_mut` in PNG decoder

---

src/codecs/gif.rs
src/codecs/png.rs
src/io/mod.rs

Implements memory limit for animation decoding and dimensions limits for individual animation frames, similar to how 
it's done for GIF.
Notable changes:
- Added a helper function `reserve_buffer` on `Limits` to be reused in PNG and GIF animation decoders
- Implemented allocation tracking in `ApngDecoder`
- Changed the PNG decoder's `new()` to default to no limits (consistently with other decoders) now that the limits are actually enforced
Out of scope of this PR:
- Passing through the limits to the `png` crate for it to limit its own allocations in animation decoding because the required APIs for that are missing from `png`
- `png` crate actually enforcing the limits it's passed: https://github.com/image-rs/image-png/issues/286 (rendering the previous bullet point moot)
- #1748 still …

Support limits in PNG animation decoding

---

.github/workflows/rust.yml

This should reduce the warning spam under the workflow runs about Node.js versions, while hopefully not breaking anything.

chore: Bump GitHub Actions versions

---

src/codecs/avif/encoder.rs
src/codecs/bmp/encoder.rs
src/codecs/farbfeld.rs
src/codecs/ico/encoder.rs
src/codecs/jpeg/encoder.rs
src/codecs/openexr.rs
src/codecs/png.rs
src/codecs/pnm/encoder.rs
src/codecs/qoi.rs
src/codecs/tga/encoder.rs
src/codecs/tiff.rs
src/codecs/webp/encoder.rs

Replaces the cryptic `assertion failed` into a more useful panic message when writing a PNG image with invalid buffer/dimensions.

Improve panic messages when providing invalid buffer sizes to `ImageEncoder`s

---

.github/workflows/rust.yml
Cargo.toml
src/codecs/png.rs
src/codecs/pnm/decoder.rs
src/codecs/webp/encoder.rs
src/codecs/webp/vp8.rs

Update MSRV and fix clippy issues

---

.github/workflows/rust.yml
Cargo.toml
src/codecs/avif/decoder.rs
src/codecs/bmp/decoder.rs
src/codecs/dds.rs
src/codecs/dxt.rs
src/codecs/farbfeld.rs
src/codecs/gif.rs
src/codecs/hdr/decoder.rs
src/codecs/ico/decoder.rs
src/codecs/jpeg/decoder.rs
src/codecs/openexr.rs
src/codecs/png.rs
src/codecs/pnm/decoder.rs
src/codecs/qoi.rs
src/codecs/tga/decoder.rs
src/codecs/tiff.rs
src/codecs/webp/decoder.rs
src/codecs/webp/extended.rs
src/dynimage.rs
src/image.rs
src/io/free_functions.rs
src/io/mod.rs
src/io/reader.rs
src/lib.rs
tests/reference_images.rs

This sketches out possible changes we may want to make to the ImageDecoder trait in the next major release:
* Makes the trait object safe
* ~~Adds a constructor (all non-deprecated implementations had one, but it wasn't part of the trait).~~
* ~~Combines `ImageDecoder` and `ImageDecoderRect`~~
* Removes the `into_reader`, `*_with_progress`, and `scanline_bytes` methods. This is the aspect I'm least sure about, but few backends had meaningful implementations of these and it cuts down on the number of methods on the trait. Some decoders will still be able to support incremental decoding by doing multiple `read_rect` calls 
The object safety change in particular makes our internal usage of the trait much nicer. Instead of having to work with a DecoderVisitor trait, we can rely on dynamic …

Improve ImageDecoder trait

---

Cargo.toml
src/imageops/colorops.rs

This eliminates one dependency when running with `default-features = false`. It is unlikely to have much impact on most users, but is technically a breaking change.

Make color_quant optional

---

src/codecs/avif/decoder.rs

Return error instead of using asssertion for Avif decoder unsupported or invalid bit depth

---

fuzz/fuzzers/fuzzer_script_exr.rs
src/codecs/bmp/decoder.rs
src/codecs/gif.rs
src/codecs/ico/decoder.rs
src/codecs/jpeg/decoder.rs
src/codecs/openexr.rs
src/codecs/png.rs
src/codecs/tga/decoder.rs
src/codecs/tiff.rs
src/codecs/webp/decoder.rs
src/io/reader.rs
src/lib.rs
tests/limits_anim.rs

The purpose of this change is to allow future decoder improvements:
* [Experiments with the PNG crate](https://github.com/image-rs/image-png/pull/427) have shown that working with a `BufRead` implementation rather than just a `Read` implementation can be faster.
* The `Seek` bound is useful for decreasing the memory usage of the decoder. Instead of storing all image metadata as it is seen, a decoder can record the location in the file of specific chunks and then seek to them if/when they are queried.
At the same time, not all decoders are likely to need either of these and having looser trait bounds is nicer for users. Thus I left the existing `Read` bound for some decoders (and actually _removed_ the `Seek` bound on TGA). After this change, the trait bounds are:

Add BufRead + Seek bound on many decoders

---

CHANGES.md
Cargo.toml

Release 0.24.9

---

Cargo.toml
README.md
src/lib.rs

Update readme and Cargo.toml

---

src/color.rs

Make pixel types repr(transparent) rather than repr(C)

---

src/codecs/jpeg/decoder.rs

Remove JPEG size limits while parsing header

---

src/buffer.rs
src/dynimage.rs

Remove lingering references to ImageOutputFormat

---

Cargo.toml

Add nasm to optionally enable faster AVIF encoding

---

src/image.rs

The feature flag is now called "ff" instead of "farbfeld" in image '0.25'

fix: Correct the Farbfeld feature flag for ImageFormat::{reading_enabled, writing_enabled}

---

src/codecs/jpeg/decoder.rs

Fixes #2180.
Would be great if we can get a release that includes this.

Disable strict mode for JPEG decoder

---

src/image.rs

Now only accepts .ff as path extension for Farbfeld
This is consistent with ImageFormat::extensions_str, and usage by other image libraries and tools.

Only accept .ff as path extension for Farbfeld

---

src/error.rs

Fix error string for unsupported color type

---

src/image.rs

Adjust two doc comments on ImageFormat in order to unite the format.

Adjust two doc comments

---

src/codecs/bmp/encoder.rs

Hi `image-rs` team,
This Pull Request focuses on enhancing the performance of the encode_gray function within BmpEncoder.
It optimizes the buffer writing process, thereby improving the overall execution speed of the function.
This modification has significantly improved the encoding speed for large-resolution BMP files.

Improve encode_gray performance in BmpEncoder

---

Cargo.toml
src/codecs/avif/decoder.rs

Read color spaces other than Bt601Limited (preferably)

av1 decoder colorspace from dav1d

---

fuzz/Cargo.toml
fuzz/fuzzers/roundtrip_webp.rs

This will detect issues such as #2171, as well as instances of incorrect encoding or decoding.
It is currently limited to RGBA, since I didn't find an easy way to use RGB format conditionally. The decoding always returns RGBA, which makes comparisons of the data a little tricky.

Add WebP roundtrip fuzzing target

---

src/buffer.rs

this PR was made according to the discussion  #2217
This PR seeks to update the doc of `ImageBuffer::new()` to garantee that the returned buffer is always filled with `zero()`s of the corresponding type, and to add tests to prevent regression regarding this behavior.

garantee that `ImageBuffer::new()` returns a buffer filled with `zero()`s of the corresponding type

---

src/io/mod.rs

fix typos and links for io::Limits docs

---

src/codecs/webp/decoder.rs
tests/regression.rs

Fixes #2226 
The iterator returns `None` as soon as a `DecodingError::NoMoreFrames` is found.
The current implementation returns every `Frame` only once regardless of the specified `LoopCount`. I believe this is what most people would expect, especially since `LoopCount::Forever` is the most used variant.
It would be a bit more performant to return the iterator at the start since the allocation of one `RgbaImage`/`RgbImage` can be saved. 
(Thank you for this awesome project btw :))

webp frames iterator is now ending iteration if no more frames are decodable

---

src/animation.rs
src/buffer.rs
src/dynimage.rs

Override `clone_from` implementations for a few types

---

README.md
fuzz/fuzzers/fuzzer_script_exr.rs
src/dynimage.rs
src/io/free_functions.rs
src/io/image_reader.rs
src/io/mod.rs
src/io/reader.rs
src/lib.rs
tests/limits.rs
tests/limits_anim.rs
tests/reference_images.rs

Following the discussion from #1327

Rename `Reader`  to `ImageReader`

---

src/codecs/hdr/encoder.rs
src/image.rs
src/io/free_functions.rs

I've re-based #2013 as it seemed in need of someone to re-base the changes. I think there were a few review comments on the PR which I'll have a go at fixing as well.

Add ImageEncoder implementation for Hdr (rebase of #2013)

---

src/image.rs

> I license past and future contributions under the dual MIT/Apache-2.0 license,
> allowing licensees to choose either at their option.
`.apng` is a common file extension used for animated PNGs.

Map `.apng` files to `ImageFormat::Png`

---

src/dynimage.rs

Hello! Thanks for maintaining such a helpful crate. This PR is a small API improvement to make it clear to users that most of the methods on `DynamicImage` are non-mutating. #1736 along with my own usage of this crate suggest that it would be helpful to make these methods `#[must_use]`.
Let me know if there's some reason that we're not using `#[must_use]` already, and if there are some methods that warrant or don't warrant being marked with this attribute.

Add `#[must_use]` attribute to some `DynamicImage` methods

---

src/codecs/webp/decoder.rs
tests/regression.rs

There's one problem: the original regression test swallowed errors because it just counted results without checking for `Ok`. I fixed that, but the WebP decoding fails on 
> Error decoding "tests/images/webp/extended_images/advertises_rgba_but_frames_are_rgb.webp" frame 3: IoError(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })  
---
Closes #2263 
---

WebP's `into_frames` iterator returns `None` upon encountering `DecodingError::NoMoreFrames`

---

Cargo.toml

v0.4.13 is a bugfix release. It fixes the panics that people kept complaining about. 
More info: https://github.com/etemesi254/zune-image/issues/215
This PR makes Cargo.toml require it, to make it impossible to use the older version that on 0.1% of images.

Bump zune-jpeg to 0.4.13

---

.github/workflows/rust.yml
src/buffer.rs
src/codecs/jpeg/encoder.rs
src/codecs/openexr.rs
src/codecs/pnm/decoder.rs
src/flat.rs
src/image.rs
tests/reference_images.rs

Tests on the main branch fail. It seems that rayon is intentionally exposed.
https://github.com/image-rs/image/blob/e176cd414ac6cc73909ff162e5d0b677f9d4fb08/src/lib.rs#L187-L188

Mark rayon as a public dependency

---

src/lib.rs

The docs link to README.md still linked to the master branch, which leads to a warning by GitHub about the branch being renamed to main when opening it.
---

chore: fix link to README.md

---

src/codecs/jpeg/decoder.rs
src/image.rs

Carbon copy of the ICC chunk handling, but for Exif.
Required for [`wondermagick`](https://github.com/Shnatsel/wondermagick) so that we could rotate the JPEGs correctly based on metadata.
In the long term we probably want to integrate `kamadak-exif`, since it doesn't have any unsafe code and seems to be in quite a good shape. But this PR seems like a simple and uncontroversial start.

Expose zune-jpeg's Exif chunk extraction

---

src/codecs/webp/encoder.rs

Explain the trade-offs involved and link to example code for encoding with libwebp.

Document WebP encoder limitations

---

src/lib.rs

The `ImageReader` link in the docs is broken and returns a resources not found error.
This PR fixes the link.
Despite the warning by `cargo docs` an explicit link was required for the fix.

Fix broken ImageReader link

---

Cargo.toml
src/dynimage.rs

Eventually we'll want to do this transparently behind the scenes, but for now document how to use the function because automatic rotation would be an API break.
Adds `kamadak_exif` as a dev-dependency.

Add Exif orientation example in a doc comment

---

src/codecs/png.rs
src/imageops/colorops.rs
src/lib.rs

related: #2265 
Fixed the update range of dispose_op for Previous and Background in APngDecoder, which was applied to the entire image, to now be within the update range of the previous frame. 
I referred to the following URL https://wiki.mozilla.org/APNG_Specification
I have checked in my environment and it works fine for the image in #2265.
The following is the data saved as an image of the frame.
[frames.zip](https://github.com/user-attachments/files/17002986/frames.zip)

Fixed the problem of Animated PNGs being decoded incorrectly

---

deny.toml

The CI has been failing since [20 August 2024](https://github.com/image-rs/image/pull/2302). Since it's been failing, I suspect commits following that PR have added things that have broken the `cargo deny check` command even more. This PR should make the CI green again.
This PR fixes the errors. Things this PR addresses:
- Add `targets` property under [`[graph]` field](https://embarkstudios.github.io/cargo-deny/checks/cfg.html?highlight=graph#the-graph-field-optional)
- Remove `vulnerability` and `unmaintained` properties since they've been removed from `cargo-deny` and now [emit errors](https://embarkstudios.github.io/cargo-deny/checks/advisories/cfg.html#the-version-field-optional).
- Remove unnecessary `deny.toml` properties like `skip-tree`. Maybe this was needed at some point, but …

Fix cargo deny warnings and errors

---

src/codecs/dxt.rs
src/codecs/webp/decoder.rs

We've had full WebP decoding support for a while. Update the docs to reflect that...
(There may still be bugs. If you find any WebP images that don't decode properly, please file a bug against the `image-webp` repository!)

Update WebPDecoder doc comments

---

src/animation.rs
src/codecs/bmp/encoder.rs
src/codecs/hdr/encoder.rs
src/codecs/pnm/encoder.rs
src/codecs/pnm/header.rs
src/image.rs

Clippy fixes

---

Cargo.toml
src/codecs/webp/decoder.rs

The `BufRead` trait bound changes should be non-breaking because it isn't possible to construct a `AnimationDecoder` without first calling `WebPDecoder::new` which already requires `BufRead`.

Upgrade image-webp

---

src/imageops/sample.rs

--
I'm not sure if there is a reason it's not implemented but we could use that for Zola.

Impl Hash for FilterType

---

src/imageops/sample.rs

This is a tip of an iceberg of better sampling, but the most critical case. Up-sampling in general may in the implementation allocate a larger temporary buffer than its input. Of course this makes little semantic sense here: after all, the actual information can not increase by this.
If one dimension increases while the other decreases the unfortunate consequence is that callers may somewhat reasonably expect a small buffer but internally will get a very large buffer. The approach of swapping sampling orders accordingly (first down, then up) might address the memory issue but is lossy.
So instead let's fix the most pressing issue: if no information was present in the input, nothing can be lost and we can pretend to perform everything by a very small intermediate image.
closes: #2340

Optimize sampling for empty images

---

Cargo.toml
src/dynimage.rs
src/metadata.rs

Now that we provide a first-party facility for it, direct people to use it.

Update apply_orientation doc comment to use `.orientation()`

---

src/codecs/jpeg/decoder.rs
src/codecs/tiff.rs
src/codecs/webp/decoder.rs
src/dynimage.rs
src/image.rs
src/lib.rs
src/metadata.rs

Move Orientation to metadata module

---

CHANGES.md
Cargo.toml

Let's get the work we did on image orientation into the hands of users!

Fill in changelog and bump version for 0.25.3

---

CHANGES.md
Cargo.toml

Closes: #2353 
I've re-written the change to essentially transfer `0.25.3` to `0.25.4`.
The proposed publishing action, in sequence since this is an unusual circumstance:
1. Wait for CI to clear everything apart from the SemVer checks
2. Verify that the Orientation interface is the only linted error in CI
3. Approve the PR
4. Checkout the commit to-be-published
5. Verify the PR is based on the current main branch (otherwise, go back to 1.)
6. Yank the version `0.25.3`: `cargo yank --version 0.25.3`
7. Publish: `cargo publish`
Please review both the changelog and the list.

Propose wording for republishing as 0.25.4

---

src/image.rs

Closes #2361.
*I license past and future contributions under the dual MIT/Apache-2.0 license,
allowing licensees to choose either at their option.*

Recognize '.jfif' extension as JPEG file

---

src/codecs/gif.rs
src/codecs/pnm/decoder.rs
src/flat.rs
tests/reference_images.rs

See <https://rust-lang.github.io/rust-clippy/stable/index.html#/manual_let_else>.

refactor: Rewrite manual `let-else`

---

Cargo.toml
src/image.rs

This change fixes #2254 by adding the non-default `serde` feature to `image::ImageForamt`.
Fixes #2254

Add optional serde feature for image::ImageFormat

---

Cargo.toml
src/codecs/avif/decoder.rs
src/codecs/avif/mod.rs
src/codecs/avif/yuv.rs

This should close #2130, #2232, #1504, #1647.
Here is also bugfix because actually YUV400 just tried to copy Y plane data straight to RGBA what is always fails.
YUV decoding is intentionally was made only to RGBA color format without Rgb, Gray, GrayAlpha and others to not break current `ColorType` resolution strategy and to not make PR even larger.
YUV decoder made as per ITU-R standard. Here is [info](https://www.itu.int/rec/T-REC-H.273/en).
Closes #2130, Closes #2232, Closes #1504, Closes #1647, Closes #1930

Avif YUV decoder, drop dcv, high bit depth

---

.github/workflows/rust.yml
Cargo.toml
README.md
src/lib.rs

As discussed in #2378, temporarily disable PCX support so that we could ship bugfixes without being blocked on decisions about support for an obsolete format.
In my tests, Cargo shows warnings about nonexistent features even to people who use the crate as a dependency, so I had to add `#![allow(unexpected_cfgs)]` as well.
I'll revert this PR once 0.25.5 is released.

Temporarily disable PCX format

---

src/codecs/avif/yuv.rs

`cargo +1.70 build --no-default-features -F avif-native` doesn't build (0.25.5). The fixes for this are trivial and only language-related, so I hope these can be included so we don't have to bump the MSRV to `1.80` when using avif-native.
- Add `use std::mem::size_of`
- Remove `pub` visibility where unnecessary
Note: Real MSRV could be lower than 1.70, haven't tested <1.70

Make avif-native 1.70-compatible

---

src/color.rs

Linked issue: https://github.com/image-rs/image/issues/2275

Clamp NaN to white when converting to integer

---

src/codecs/avif/yuv.rs

If the stride is larger than the plane size, it might contain junk data beyond the actual valid region.
To avoid processing artifacts when working with odd-sized images, the buffers is reshaped to their actual size.

Fix YUV 4:2:0, 4:2:2 large strides

---

Cargo.toml
src/codecs/jpeg/encoder.rs
src/codecs/png.rs

Notes:
- `png` crate doesn't actually write ICC profiles at all in latest published version as of writing (0.17.14), however it seems that 0.17.15 will be released soon: <https://github.com/image-rs/image-png/commit/10644dbff4d5b5614199cbc81145838abdafd98c>

Implement writing ICC profiles for JPEG and PNG images.

---

src/imageops/sample.rs

In a similar fashion to https://github.com/image-rs/image/pull/2343, it would be useful if `FilterType` impl'd `Eq`.

impl Eq for FilterType

---

src/animation.rs
src/buffer.rs
src/codecs/avif/yuv.rs
src/codecs/bmp/decoder.rs
src/codecs/bmp/mod.rs
src/codecs/gif.rs
src/codecs/hdr/encoder.rs
src/codecs/hdr/mod.rs
src/codecs/jpeg/encoder.rs
src/codecs/jpeg/mod.rs
src/codecs/png.rs
src/codecs/pnm/decoder.rs
src/codecs/tga/decoder.rs
src/flat.rs
src/image.rs
src/imageops/colorops.rs
src/imageops/fast_blur.rs
src/imageops/mod.rs
src/imageops/sample.rs
src/math/utils.rs
src/metadata.rs
src/utils/mod.rs

The combination of using nightly Clippy and failing CI on any Clippy lint makes it keep breaking PRs ;(

Another batch of Clippy

---

src/image_reader/free_functions.rs

Allows formats to specify a mask of which bytes to compare against the signature. Particularly useful for WebP and AVIF which place size fields prior to their signatures.
Fixes #2409

Improve format detection

---

src/codecs/pnm/decoder.rs

Per commit message:
> This function now rejects numbers that start with a leading +, although to match netpbm behavior it does not reject leading zeros. It also avoids allocating on the non-error path, reducing the time needed to read a large plain PPM test image to 50%. As the function no longer keeps the entire token in memory at once, the error messages no longer specify the bad token.
1. I don't think losing error message specificity here is a big problem, because PNM images are essentially never written by hand so the errors will rarely occur; if parsing does fail, one can easily find non-digit non-whitespace characters in a file with a regexp (e.g. `grep -P '[^0-9 \t]'`)
2. To create a large "plain" (P3) image to test this with, use e.g. `pngtopnm -plain large.png > ~/output.ppm`. …

pnm: Optimize and improve validation for read_separated_ascii

---

src/imageops/fast_blur.rs
src/imageops/sample.rs

Updated doc for `blur` and `resize`.
Clippy error seems to be the error in the clippy itself.

Update resize and blurs doc

---

src/codecs/jpeg/decoder.rs

Parsing metadata (ICC profile, EXIF data) should not have any image data limits set. This change is similar to #2175.

Remove limits when parsing JPEG metadata

---

src/codecs/jpeg/decoder.rs

Fixes this: `Format error decoding Jpeg: Length of the decoded data 201283584doesn't match the advertised dimensions of the imagethat imply length 150962688`

Fix missing spaces in JpegDecoder error message

---

src/image.rs

I just added 'image/vnd.microsoft.icon' as mime for the ImageFormat::Ico format. I think it's a valid mime for this image type ([iana](https://www.iana.org/assignments/media-types/image/vnd.microsoft.icon))
Returning 'icon/x-icon' seems valid during the opposite operation (retrieving a mime from the [ImageFormat](https://github.com/image-rs/image/blob/85f2412d552ddd2f576e16d023fd352589f4c605/src/image.rs#L228)), no change needed here IMO
Context:
I'm using egui_extra to load a bunch of favicons in a UI, there is a loader that forwards image loading to this crate, using the ImageFormat to detect which format to use. Some favicons weren't loading since the mime was 'image/vnd.microsoft.icon'. For the full chain to work properly, a change is also needed in egui_extra though …

Detect image/vnd.microsoft.icon mime types as ImageFormat::Ico

---

README.md

Quick and simple PR to add links to method
Some methode like `flip_horizontal` or `constrast` isn't the real function name
These links can be useful to see the real documentation

Add some link to docs in README

---

Cargo.toml
src/codecs/avif/encoder.rs

The latest version of `ravif` was published 2 days ago, and it deprecated certain APIs. Since `image` uses `#![deny(deprecated)]`, this causes CI to fail, as can be seen in recent PRs.
This PR fixes this by updating `ravif` to the latest version and using the new APIs.
---
If updating `ravif` is **not** wanted, I can also make a PR that just `#[allow]`s the now deprecated APIs to pass CI.

Update `ravif` to v0.11.12

---

fuzz/Cargo.toml
src/codecs/pnm/decoder.rs

Without this, trying to parse a claimed-large image will just fill it with zeros, but not actually *fail*.
I guess this is *technically* a compat break in the sense that truncated images won't parse now, but I don't think that's really a problem.

Error if we don't actually see any data in read_separated_ascii

---

src/image.rs

Changes:
- I rephrased certain sections to make it a bit clearer that there are no alignment requirements for `buf`.
- Example code now gets syntax highlighting.
- I fixed the example for `ImageDecoder::read_image`. It now actually works. (It might be worth taking zerocopy as a dev dependency just to run doc tests for example like this. Thoughts?)

Minor improvements to documentation

---

src/codecs/avif/decoder.rs
src/codecs/avif/yuv.rs

Here is YCgCo decoder implementation.
ITU-R CICP spec [link](https://www.itu.int/rec/T-REC-H.273/en).
This is YCgCo only implementation. YCgCo-R de-facto is not used in AVIFs.
libavif introduced YCgCo-Re and YCgCo-Ro types (matrix coefficients 16 and 17), but dav1d-rs does not support them at the moment. They are more complex due to bit-depth shifts, so their implementation is postponed for the future.
Note: eq. 27-29, colors range in YCgCo handled differently than in YCbCr.
[Here](https://github.com/awxkee/image/tree/ycgco_samples/samples) is valid YCgCo images to try out. I don't know software that could open them correctly, except Chrome and avifdec ( part of libavif ).
I spent few hours trying to figure out why colors didn't match Chrome after simple decoding those images, because I …

AVIF: YCgCo

---

src/buffer.rs
src/dynimage.rs
src/image_reader/free_functions.rs
src/lib.rs

I decided to look into improving compile times inspired by https://github.com/image-rs/image/issues/2244#issuecomment-2544563417
It turns out that a lot of time is spent compiling image format encoders for reasons that are somewhat subtle: Due to how the Rust compiler is implemented, methods with generic arguments get compiled when building a crate that uses them, while methods with concrete types get compiled when building the crate that defines them. 
In particular, the `save` family of methods in this crate take a generic argument (their "path" parameter) but were previously implemented to call a concrete `save_buffer_with_format_impl` version to handle the actual encoding / saving of the data. However at the same time, the various format crates that we depend on expose encoders that …

Avoid monomorphizing encoders if not used

---

src/dynimage.rs
tests/regression.rs

Currently, the `load_from_memory[_with_format]` methods cause rustc to generate code for them when compiling the image crate, even if downstream code never decodes images from in-memory buffers. This PR changes them to be generic so that they only get monomorphized only if they are actually used. 
Reduces time for release builds by ~1.2 seconds on my machine.
See also: #2468, #2469

Make `load_from_memory` generic to improve compile times

---

src/buffer.rs
src/buffer_par.rs
src/codecs/avif/decoder.rs
src/codecs/avif/encoder.rs
src/image.rs
tests/reference_images.rs

This is introduced in nightly matching what the standard library has been doing for years now. The idea is to clearly indicate to the caller in the signature that data is being borrowed even when the name for such lifetimes are elided. The lint only indicates 'non-trivial' or unexpected borrows, e.g. it does not fire when the borrow happens from an output reference type.
With this PR our CI should once again be clean.

Fix lints mismatched_lifetime_syntaxes

---

src/metadata.rs

Tools that not only display images but also encode or convert them may want to apply the Exif orientation to the image up front, so that they don't have to rely on other software being Exif-aware to display the images with the correct orientation.
Such tools need to clear the orientation data from the Exif chunk, otherwise the image will be rotated twice and display incorrectly in Exif-aware software.
Modifying Exif data is exceptionally cursed, and general-purpose transformation code is bound to break some offset-dependent Exif chunks : https://github.com/kamadak/exif-rs/issues/1
However, in this particular special case we can rely on the fact that we are not changing the length of the data to reset orientation to `NoTransforms` and keep the rest of the Exif chunk intact.
I need this …

Alow extracting orientation from an Exif chunk and optionally clearing it in Exif

---

src/codecs/tiff.rs

Avoid panics for tif images with multi planar configuration.
I have just made a fix for usage by a company I work at, lmk if you folks would prefer it fixed in some other way.
It's a draft as it hasn't quite been extensively tested, yet. And might require more changes to target only cases which aren't quite supported correctly.
Lmk if you folks want any other changes.
Fixes https://github.com/image-rs/image/issues/2179

fix: avoid panic multi planar tif images

---

src/imageops/fast_blur.rs
src/imageops/filter_1d.rs

Closes #2511 
It’s possible to push it even further using a ring buffer and fixed point arithmetic, but that would at least double the amount of code, and this version already gives a nice performance boost.
<details>
<summary>Benchmark</summary>
```
fast blur: sigma 3.0    time:   [10.750 ms 10.758 ms 10.766 ms]
change: [-52.185% -52.000% -51.832%] (p = 0.00 < 0.05)
fast blur: sigma 7.0    time:   [10.851 ms 10.873 ms 10.896 ms]
change: [-51.702% -51.598% -51.494%] (p = 0.00 < 0.05)
fast blur: sigma 50.0   time:   [11.371 ms 11.426 ms 11.486 ms]
change: [-50.958% -50.681% -50.399%] (p = 0.00 < 0.05)
gaussian blur: sigma 3.0
time:   [9.4690 ms 9.7881 ms 10.273 ms]
gaussian blur: sigma 7.0
time:   [20.815 ms 20.922 ms 21.042 ms]
gaussian blur: sigma 50.0
time:   [173.84 ms 174.37 ms 174.92 …
```

Improving Fast Blur

---

src/codecs/tga/decoder.rs

This simplifies the TGA decoder and in the process fixes a few bugs and eliminates some allocations.
A few bugs identified:
* Multi-byte color map indices are decoded little-endian rather than big-endian as previously.
* Out-of-bounds color map indices are now a decoding error. They were previously an I/O error, though #2514 accidentally changed them to being a debug_assert! and silently ignored in release builds.
* `fixup_orientation` uses "raw_bytes_per_pixel" (which previously had the more confusing name of "bytes_per_pixel"), so it has been moved to before the application of the color map.
* Calculation of color type used to double-count the alpha channel bits for color mapped images.
I also added a few restrictions which simplify the code:
* Only 8-bit alpha channels are allowed.
* …

Refactor TGA decoder

---

.github/workflows/rust.yml

CI immediately launches a ton of jobs, but may fail due to trivial issues like Clippy. 
Here I'm trying to run some basic tests first before spawning the rest.

Fail CI quicker?

---

src/color.rs
src/traits.rs

While working on a bug fix https://github.com/image-rs/imageproc/pull/719 in the `imageproc` crate, I needed to check `Pixel` type has an alpha channel.
The only way I found to do this was by comparing the `COLOR_MODEL: &str` value in the `Pixel` trait, which feels a bit indirect and error-prone.
I think it would be much clearer and easier to use if the `Pixel` trait had a `HAS_ALPHA: bool` constant to indicate this directly.

add const `HAS_ALPHA` to trait `Pixel`

---

.github/workflows/rust.yml
Cargo.toml
src/codecs/jpeg/encoder.rs
src/codecs/png.rs
src/codecs/webp/encoder.rs
src/io/encoder.rs

This PR replaces the single format API introduced in #2537 with a consistent API that we can implement across a range of formats.

Add `ImageEncoder::set_exif_metadata` and implement for JPEG, PNG, and WebP

---

src/images/generic_image.rs

This adds `GenericImageView::try_view` as a non-panicking alternative to `GenericImageView::view`. It additionally updates the documentation of `GenericImageView::view` to mention its panics.
I am writing a non-panicking binary that captures screenshots of a window. If the user resizes their window unexpectedly, the coordinates/dimensions I pass in to `GenericImageView::view` may become invalid. I would like to be able to get an `Err` so I can handle this behavior myself.
I am unsure if the error I utilized here is correct within this context -- please let me know if there is another I should be using/if I should create a new one!

Add `GenericImageView::try_view`

---

src/animation.rs

Hi, I saw [this comment](https://github.com/image-rs/image/pull/1986#issuecomment-1694402502) and wrote this code on a whim.  If it's completely unnecessary that's fine.

Calculate GCD in Ratio::new

---

src/color.rs
src/error.rs
src/traits.rs

add color type conversion

---

.github/ISSUE_TEMPLATE/upstream.yml

Apparently it is not allowed to set `multiples` for checkboxes, that is implied.

Fix syntax error for upstream template

---

src/io/decoder.rs

Without this PR, calling `ImageDecoder::orientation` on a `Box<dyn ImageDecoder>` would resolve to the default implementation rather than the one on the inner decoder.

Add missing method on ImageDecoder impl for Box

---

src/codecs/png.rs

The png crate supports extracting exif metadata as of recently, so this is wiring this up to the `ImageDecoder`  type.
This is related to #2494.

Extract exif metadata from pngs

---

.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/format_request.yml
.github/ISSUE_TEMPLATE/upstream.yml

As discussed, linking to `image-extras` and a discussion page added. The checkboxes are required to be ticked actively to allow opening an issue, I've also added a field to refer to an existing crate that should implement the format.

Improve the Issue templates for format requests

---

src/imageops/sample.rs

I missed these in #2577. The original URLs still work but this changes them to use the updated branch name.

Update image URLs

---

CHANGES.md

Doesn't list the improvements made to subcrates such as image-webp.

Populate changelog for the upcoming 0.25.7 release

---

README.md
src/lib.rs

This shortens the crate README by removing a big table that was mostly just filled with the word "Yes". Also rewords the section about supported formats.

Move format support table to only be in docs

---

Cargo.toml

Release notes were drafted earlier, this is the only todo. Last couple of fixes were simply bumping png and tiff to upstream their respective improvements, and tests for those.
Closes: #2551

Bump version to 0.25.7

---

src/codecs/bmp/encoder.rs
src/codecs/dxt.rs

Closes: #2604, the error symptom is reproduced by the regression test.

Harden bmp encoder arithmetic against overflows

---

src/codecs/tga/decoder.rs

This fixes a decoding error observed with the TGA image `football_seal.tga`, from https://people.math.sc.edu/Burkardt/data/tga/tga.html, which was mentioned in https://github.com/image-rs/image/issues/2603.  (Note: 2603 is a freshly created issue and it isn't clear whether this patch resolves all the problems described in it.)
On color mapped images, the TGA decoder had placed the raw image data before applying the color maps in a prefix of the the provided buffer. However, `fixup_orientation()` was being called on the entire buffer, making it swap the first half of the raw image data (A) with whatever was in the end region (D) instead of A with B (the second half of the raw image data).
```
Example layout of `buf` at the time `fixup_orientation()` was applied, expanding 1 byte indices to …
```

tga: fix orientation flip for color mapped images

---

src/codecs/tga/decoder.rs
src/codecs/tga/encoder.rs

This is one the approach to resolving https://github.com/image-rs/image/issues/2575. (Alternatively, if one wants to create TGA images which have zero width or height fields, the change is simple, see https://github.com/mstoeckl/image/tree/tga-empty.)
While the TGA spec does not explicitly prohibit images with zero width and height, it also permits a number of other weird images that are de-facto prohibited by implementations (e.g. pixels with bpp not in [8,15,16,24,32] that don't correspond to original hardware patterns; >2 byte color map indices). Since many implementations* do not create and do not accept zero sized TGA images, I would recommend doing the same.
*Specifically, ImageMagick does not decode empty TGA images, printing a `negative or zero image size` warning; `ffmpeg` prints …

tga: reject empty images
