- src/animation.rs
- src/buffer.rs
- src/color.rs
- src/dynimage.rs
- src/gif/decoder.rs
- src/image.rs
- src/imageops/sample.rs
- src/jpeg/decoder.rs
- src/jpeg/encoder.rs
- src/jpeg/entropy.rs
- src/jpeg/transform.rs
- src/lib.rs
- src/png/decoder.rs
- src/png/deflate.rs
- src/png/encoder.rs
- src/png/filter.rs
- src/png/hash.rs
- src/tga/decoder.rs
- src/tiff/decoder.rs
- src/tiff/ifd.rs
- src/traits.rs
- src/webp/vp8.rs
Closes https://github.com/PistonDevelopers/image/issues/226
Travis CI will fail because of broken dependencies.
> Upgraded to latest Rust

- src/animation.rs
- src/buffer.rs
- src/color.rs
- src/image.rs
- src/lib.rs
- src/png/decoder.rs
- src/traits.rs
associated type changes to be exact
> adapted to master changes

- src/imageops/sample.rs
fix black top-left border after resize (issue [#197](https://github.com/PistonDevelopers/image/issues/197))
> fix black top-left border after resize (issue #197)

- src/imageops/colorops.rs
- src/imageops/sample.rs
- src/jpeg/decoder.rs
- src/lib.rs
- src/math/mod.rs
- src/math/utils.rs
- src/webp/vp8.rs
> Extract clamp to math::utils

- Cargo.toml
- src/buffer.rs
- src/color.rs
> Remove Option::None hack (new rustc version).

- examples/fractal.rs
- examples/opening.rs
- src/buffer.rs
- src/color.rs
- src/dynimage.rs
- src/gif/decoder.rs
- src/imageops/sample.rs
- src/jpeg/decoder.rs
- src/jpeg/encoder.rs
- src/lib.rs
- src/png/decoder.rs
- src/png/encoder.rs
- src/ppm/encoder.rs
- src/tga/decoder.rs
- src/tiff/decoder.rs
- src/tiff/ifd.rs
- src/webp/decoder.rs
- tests/tga.rs
Also standardise on the spelling of Gray across the repo. I chose Gray as the TIFF spec has tags with the American spelling.
> Add convenient save method on ImageBuffer

- Cargo.toml
Closes https://github.com/PistonDevelopers/image/issues/278
> Upgraded crates.io

- src/lib.rs
- src/png/hash.rs
Currently doesn't build because rust-lang/glob doesn't compile too, already sent a PR https://github.com/rust-lang/glob/pull/31
> Update to latest Rust.

- Cargo.toml
- examples/fractal.rs
- examples/opening.rs
- src/buffer.rs
- src/dynimage.rs
- src/jpeg/encoder.rs
- src/lib.rs
- src/png/decoder.rs
- src/png/encoder.rs
- src/ppm/encoder.rs
- src/tga/mod.rs
- tests/tga.rs
> Use a reference in DynamicImage::save, and fix some warnings

- Cargo.toml
- src/buffer.rs
- src/image.rs
- src/math/mod.rs
- src/math/utils.rs
Warning-free for the first time since ages…
Closes #251
> Remove warnigs and remove rand-dependency.

- src/color.rs
- src/dynimage.rs
- src/gif/decoder.rs
- src/gif/encoder.rs
- src/gif/mod.rs
- src/utils/bitstream.rs
- src/utils/lzw.rs
Adds a GIF encoder. 
Automatic reduction of colors is not implemented yet. I'll port NeuQuant to Rust for that. 
To compensate for that the encoder supports saving high color GIFs. Unfortunately this is quite slow because an ridiculous number of frames has to be calculated if the image contains a lot of colors.
Closes #282
> GIF encoder

- src/gif/encoder.rs
- src/imageops/colorops.rs
- src/imageops/mod.rs
Proper quantization function for colors is coming soon…
> Add dithering

- src/imageops/colorops.rs
- src/imageops/sample.rs
> Work around the ICE in the latest Rust

- src/png/filter.rs
Fixes #305.  This partially reverts #298, but keeps the correct parts.
> Fix regressions in PNG filter

- src/png/filter.rs
This is a follow-up to #306.  I forgot to keep these loops in reverse order.
This code needs tests; if I have time later I will write some.
> Add some missing rev() calls

- src/jpeg/decoder.rs
- src/jpeg/entropy.rs
- src/jpeg/transform.rs
> Temporary fix of the jpeg decoder

- src/png/encoder.rs
Update for https://github.com/rust-lang/rust/pull/23399
> Update for latest Rust

- src/lib.rs
> Add #![feature(slice_patterns)]

- src/png/decoder.rs
> Remove unsafe blocks in png decoder

- Cargo.toml
> Bump version to 0.3.6

- src/color.rs
- src/imageops/colorops.rs
- src/imageops/sample.rs
- src/lib.rs
- src/traits.rs
Still some issues left, but it is a start.
> Upgrade to Rust nightly

- src/dynimage.rs
- src/imageops/sample.rs
- src/png/decoder.rs
- src/ppm/encoder.rs
Remain: SIMD operations and `slice::copy_memory`.
> More "core" feature removal

- src/lib.rs
> Cleanup lib.rs

- src/dynimage.rs
Needed for https://github.com/PistonDevelopers/texture_packer/issues/26
> Added Clone to DynamicImage

- Cargo.toml
> bump version, update dependendies

- src/jpeg/decoder.rs
> Fix mcucount overflow when decoding large JPEG files

- src/lib.rs
> Publically export ConvertBuffer trait

- src/bmp/decoder.rs
While it makes the code look nicer through less manual indexing, it's not that impressive of an abstraction layer yet.  The real payoff from the row iterator will come with implementing more formats, I think, particularly the RLE compression ones.
This is my first "real" Rust code, so any style comments would be most appreciated.  It's also my first "real" pull request for this project, so any advice on common code that I ought to use would be appreciated as well!  There's some similar-looking code in `src/buffer.rs`, but that code appears to be working at a higher level than the code here.
> add row iteration to the BMP decoder

- src/ico/decoder.rs
> Cast real_width/height to u32

- src/bmp/decoder.rs
- src/dynimage.rs
> Fix panic on empty file

- src/bmp/decoder.rs
> Return errer on invalid bitmap height

- .travis.yml
- Cargo.toml
- examples/fractal.rs
- src/image.rs
- src/imageops/affine.rs
- src/imageops/colorops.rs
- src/imageops/mod.rs
- src/imageops/sample.rs
- src/jpeg/decoder.rs
- src/jpeg/encoder.rs
- src/jpeg/entropy.rs
- src/jpeg/transform.rs
- src/ppm/encoder.rs
- src/tga/decoder.rs
- src/tiff/decoder.rs
- src/utils/lzw.rs
- src/webp/transform.rs
- src/webp/vp8.rs
> Updated dependencies, fixed warnings

- Cargo.toml
CC https://github.com/servo/servo/pull/8446
> Update to byteorder 0.4

- src/jpeg/decoder.rs
- src/jpeg/entropy.rs
Just a few things I noticed while reading the code.
> Misc jpeg fixes

- Cargo.toml
- src/gif.rs
> Updated dependencies

- src/jpeg/encoder.rs
> Fix jpeg encoder panic from shift overflow

- Cargo.toml
- src/image.rs
- src/tiff/decoder/mod.rs
- src/tiff/decoder/stream.rs
If possible, would you release a new version?
> Upgrade byteorder to 0.5.1

- src/dynimage.rs
Use `BufReader` for all formats as it was intended.
> Use buffered read for all formats in dynimage::load.

- Cargo.toml
Release new version as the bmp decoder saw some improvements.
> Bump Version to 0.10.1

- src/dynimage.rs
@joshtriplett Is this ok?
Closes #556
> Improve doc for DynamicImage::resize()

- README.md
Not sure it's really useful, but it could help users who tries example. Feel free to close this PR!
> Avoid warning and error running README example

- src/jpeg/encoder.rs
Right now JPEGEncoder uses the standard quantization tables unscaled, which corresponds to quality=75 in libjpeg. This is a little low.
This pull request implements a `JPEGEncoder::new_with_quality()` function that scales the quantization table using the libjpeg definition of the "quality" parameter.
Note: quality > 95 also changes the DCT method in libjpeg. This PR doesn't address anything outside of quantization matrix scaling.
Quality=10:
Quality=90:
> Add JPEGEncoder constructor with parameter for adjusting quality

- README.md
- src/dynimage.rs
- src/imageops/colorops.rs
- src/imageops/mod.rs
huerotate color just like webkit css filter does:
normal
huerotate(180)
> added huerotate

- .travis.yml
- Replaced old token with a new one
- Redirect stdout and stderr to /dev/null to hide output on error
> Regenerated Github auth token

- Cargo.toml
- src/buffer.rs
- src/hdr/hdr_encoder.rs
- src/imageops/mod.rs
- src/imageops/sample.rs
- Update to latest image-png
- Removed unused imports
> Published 0.12.0

- Cargo.toml
> Bump image to 0.12.1

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pistondevelopers/image/626)
> Turn `glob` into a dev-dependency

- README.md
- src/dynimage.rs
- src/image.rs
- src/ppm/decoder.rs
- src/ppm/encoder.rs
- src/ppm/mod.rs
Adds a basic decoder for 8bit PPM files following the normal setup of the other decoders.
> Add a basic PPM decoder

- Cargo.toml
- src/buffer.rs
Closes https://github.com/PistonDevelopers/image/issues/635
- Bumped to 0.12.4
> Added derive `Debug` to `ImageBuffer`

- Cargo.toml
> Published 0.13.0

- Cargo.toml
- src/imageops/sample.rs
> Published 0.14.0

- fuzz/.gitignore
- fuzz/Cargo.toml
- fuzz/fuzzers/fuzzer_script_bmp.rs
- fuzz/fuzzers/fuzzer_script_gif.rs
- fuzz/fuzzers/fuzzer_script_guess.rs
- fuzz/fuzzers/fuzzer_script_hdr.rs
- fuzz/fuzzers/fuzzer_script_ico.rs
- fuzz/fuzzers/fuzzer_script_jpeg.rs
- fuzz/fuzzers/fuzzer_script_png.rs
- fuzz/fuzzers/fuzzer_script_ppm.rs
- fuzz/fuzzers/fuzzer_script_tga.rs
- fuzz/fuzzers/fuzzer_script_tiff.rs
- fuzz/fuzzers/fuzzer_script_webp.rs
I've added fuzzing scripts to decode each format explicitly and one that runs the generic `load_from_memory` function.
I've got some crashes in incoming issues and PRs.
> Add fuzzing scripts

- src/ppm/decoder.rs
I made a little mess with the commits, please tell me if you want me to squash or correct them.
> Fixes #629 - PPM multiply with overflow

- Cargo.toml
- src/bmp/decoder.rs
- src/buffer.rs
- tests/reference_images.rs
- Updated dependencies
- Fixed `mut` warnings
- Fixed warnings about unused doc comments
> Published 0.16.0

- src/ppm/decoder.rs
- src/ppm/mod.rs
> Add comment handling to PPM decoder

- src/buffer.rs
- src/ppm/encoder.rs
> Fix some comments

- README.md
- examples/fractal.rs
- src/bmp/decoder.rs
- src/buffer.rs
- src/hdr/hdr_decoder.rs
- src/ico/decoder.rs
- src/image.rs
- src/math/nq.rs
- src/tga/decoder.rs
- src/tiff/decoder/mod.rs
- src/utils/lzw.rs
- src/webp/vp8.rs
- tests/reference_images.rs
This is the result of me testing out a WIP source code spell-checker
and your project was the random target this time.
> fix some typos

- src/dynimage.rs
> Add a resize_to_fill method

- src/gif.rs
- src/image.rs
This will resolve #725 by implementing the `into_frames` function for gifs
> Added into_frames implementation for gifs

- Cargo.toml
Which I forgot when creating the pnm en/decoder
> Add HeroicKatora as author

- Cargo.toml
I had a pull request which was merged earlier in the week. Thanks @bvssvni for telling me to do this (#748). I look forward to contributing more to this project.
> Updated Authors in Cargo.toml

- src/dynimage.rs
Use resize_dimensions from PR #667 in thumbnail from PR #720.
> Dry and consistent size calculation.

- src/color.rs
Keep background color when final alpha is zero, instead of panicking.
- Fixed some spelling errors
- Added `test_blend_luma_alpha`
- Added `test_blend_rgba`
> Fix panic on alpha zero

- CHANGES.md
- Cargo.toml
> Publish 0.19.0

- Cargo.toml
I forgot to do this when I wrote the DXT encoder/decoder.
> Add CensoredUsername as author

- Cargo.toml
- src/tiff.rs
> Bump to 0.20.0

- README.md
Updated the README to use `GenericImageView` trait. I'm just trying the examples, and this took a bit to figure out. I'll submit more PR's as I find more issues. :)
> Updated README to use GenericImageView trait

- src/dynimage.rs
See
https://github.com/PistonDevelopers/image/pull/818#issuecomment-425877424
> Replace code to make wasm target work

- release.sh
Check for the following issues before releasing, detecting before packaging and publishing:
1. There must be a version description section in `CHANGES.md`
2. The version is not yet published, redundant with `cargo publish` but saves a bit of time
> Simplistic release test stub

- src/animation.rs
- src/gif.rs
- src/image.rs
This implements a solution to #823.
> The `animation::Frames` struct now loads gif frames one at a time.

- src/imageops/mod.rs
As noted in #848 but fixes all remaining possible overflow related issues. Also adds some more tests that assert these additional guarantees.
> Comprehensively fixes all Overlay issues

- Cargo.toml
- src/hdr/hdr_decoder.rs
- src/lib.rs
- src/tiff.rs
- src/utils/mod.rs
Addresses the issues found in #885 .
> Unsafe pod transmute

- src/imageops/sample.rs
> Derive Debug on FilterType

- Cargo.toml
- README.md
- src/bmp/encoder.rs
- src/buffer.rs
- src/dxt.rs
- src/hdr/hdr_decoder.rs
- src/image.rs
- src/imageops/sample.rs
- src/png.rs
- src/utils/mod.rs
A rebase of the master branch with those commit series that were a fix in some way. Avoids adding or changing any interface. Most importantly, this also updates the metadata in `Cargo.toml` to reflect the change is organization and to link directly to the source tree of that version.
> Backport some further fixes to 0.21

- src/webp/vp8.rs
> Fix vp8 border block indexing

- .github/ISSUE_TEMPLATE/bug_template.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE.md
Provides some more issue templates as well. You can try them out here:
https://github.com/HeroicKatora/image/issues
>  Add templates for issues and pull request, try 3 

- src/math/nq.rs
> nq: update link

- Cargo.toml
> chore: Update glob to 0.3

- README.md
- src/bmp/decoder.rs
- src/bmp/encoder.rs
- src/color.rs
- src/dxt.rs
- src/dynimage.rs
- src/gif.rs
- src/hdr/decoder.rs
- src/ico/decoder.rs
- src/image.rs
- src/jpeg/decoder.rs
- src/jpeg/encoder.rs
- src/lib.rs
- src/png.rs
- src/pnm/decoder.rs
- src/pnm/encoder.rs
- src/pnm/mod.rs
- src/tga/decoder.rs
- src/tiff.rs
- src/webp/decoder.rs
> Refactor the ColorType enum

- .travis.yml
- Cargo.toml
- src/dynimage.rs
> Fixed broken build with no default features

- .travis.yml
Suggested in #1024 
Add Clippy to Travis (allows failure)
And I formatted indents so sorry about large diff!
> Add Clippy to Travis

- src/bmp/decoder.rs
- src/bmp/encoder.rs
- src/dynimage.rs
- src/hdr/decoder.rs
- src/ico/encoder.rs
- src/tga/decoder.rs
Format code that I recently touched by rustfmt.
(Should we run rustfmt to all the code?)
> Format code by rustfmt

- src/gif.rs
- src/image.rs
- src/png.rs
Simplify while condition that introduced in recent bugfix, etc.
> Fix few clippy warnings

- src/bmp/decoder.rs
- src/hdr/encoder.rs
> Use `match` instead of `if-else` chain

- examples/opening.rs
- examples/scaledown/main.rs
- examples/scaleup/main.rs
- src/dynimage.rs
- src/image.rs
- src/io/free_functions.rs
- src/io/reader.rs
- src/lib.rs
- src/webp/decoder.rs
- src/webp/mod.rs
- src/webp/vp8.rs
- tests/save_jpeg.rs
Relates to: #974 (but doesn't completely fix it)
> Convert ImageFormat variants to CamelCase

- src/gif.rs
- src/png.rs
- src/tiff.rs
The latter is part of the a publicly visible crate interface. This makes
it impossible to upgrade the image format crates used for these specific
format over major versions. Using this pattern is problematic in several
aspects:
* less mature formats are harder to adopt as they are a huge commitment
* bugs and issues that require breaking changes require a coordinate
effort across the whole dependency chain and ecosystem
* dependent crates we control do not evolve as independently as I would
wish
It should arguably be avoided to have an unecessary public interface
dependency *unless a format reaches a stable 1.0 interface itself* where
it is no large liability. For consistency this should be uniform across
formats without regards to whether they are internally implemented, a
crate in …
> Convert error with private methods, not From

- src/bmp/encoder.rs
- src/buffer.rs
- src/dynimage.rs
- src/hdr/encoder.rs
- src/ico/encoder.rs
- src/image.rs
- src/io/free_functions.rs
- src/jpeg/encoder.rs
- src/png.rs
- src/pnm/encoder.rs
Fixes #1058.
A ton of changes are from cargo fmt, which I'm not sure if I ran wrong or something, otherwise we should merge a fmt commit into master so the this diff is way easier to read.
> Fixes #1058. Migrated to ImageError from std::io::Error

- src/pnm/encoder.rs
> Fix overlapping patterns

- .travis.yml
- benches/encode_jpeg.rs
- benches/load.rs
- src/buffer.rs
- src/imageops/sample.rs
> Fix benchmarks and ensure compilation on Travis

- CHANGES.md
- Cargo.toml
> Update release and notes for 0.23 preview

- src/bmp/encoder.rs
Fixes #1090.
Adds checked_mul when computing img size.
Not really that happy about the solution I implemented. Open for feedback :)
> Fixes #1090.

- src/bmp/encoder.rs
> Fixes #1090. Checks for overflowing dimensions.

- src/png.rs
This is a small Pull Request resolving #1112 
> Fix documentation of PNGReader

- CHANGES.md
- Cargo.toml
While the error changes for `0.23` are still a work in progress (soon!) the master branch has accumulated enough bug fixes and other improvements to warrant another minor release.
> Update release notes and meta data for 0.22.4

- src/buffer.rs
- src/dynimage.rs
- src/imageops/sample.rs
> Fix benchmarks to edition 2018

- CHANGES.md
- Cargo.toml
- README.md
- src/lib.rs
We'll have a release of version `0.23` when this PR is merged. Nice-to-have list:
This closes #1073
> Update readme, change notes, meta data

- src/bmp/decoder.rs
- src/bmp/encoder.rs
This is part of #1134, rework for `bmp` module.
Most of the errors were `FormatError` and can be converted simply to `DecodingError`.
However, I'm not sure how `ImageError::UnsupportedError` should be translated:
* Which should be used for "Unsupported Bitmap Header", `DecoderError` or `UnsupportedError`?
+ This is emitted when BMP header type (more precisely, its size) is unknown.
* Which should be used for "Unsupported image type", `DecoderError` or `UnsupportedError`?
+ This is emitted when the BMP image uses PNG or JPEG compression, or other unknown image types.
Additionally, if `UnsupportedError` should be used for them, what error kind (variants of `UnsupportedErrorKind`) should be used for them?
* `Color` is not appropriate for them.
* `Format` would be better, but I'm not sure the …
> Use detailed errors for BMP encoder and decoder

- src/dds.rs
This is part of #1134, rework for `dds` module.
> Use detailed errors for DDS decoder

- src/tiff.rs
This is part of #1134, rework for `tiff` module.
> Use detailed errors for TIFF encoder and decoder

- CHANGES.md
- Cargo.toml
Mainly motivated by rolling out the png fixes.
> Release 0.23.1

- CHANGES.md
- Cargo.toml
- Cargo.toml.public-private-dependencies
> Update release notes for 0.23.2

- src/image.rs
> ImageDecoderExt documentation

- src/jpeg/encoder.rs
The jpeg encoder did not check the size of the image it was given in input,
so an integer overflow happened when trying to encode large images
> Fix incorrect jpeg images being created due to an unchecked type conversion in the encoder 

- src/error.rs
- src/image.rs
- src/png.rs
Removal of the `InsufficientMemory` constructor listed in #1134.
> Remove InsufficientMemory constructor

- src/gif.rs
Follow-up to #1191.
Rewrites `GifFrameIterator::next` to reduce the number of allocations and compute the frame in a single pass.
I measured a 33% performance improvement when reading the `tests/images/gif/anim/mixed-disposal.gif` file, and a 8% improvement when reading a more "typical" file (620x400 px, full-sized frames with `DisposalMethod::Keep`).
-----
Benchmark code used:
```rust
use std::io::Read;
use image::AnimationDecoder;
fn load_all(c: &mut Criterion) {
let mut file = std::fs::File::open("path/to/file").unwrap();
let gif_data = Vec::new();
file.read_to_end(&mut gif_data).unwrap();
c.bench_function("gif-frames", |b| b.iter(|| {
let cursor = std::io::Cursor::new(&gif_data);
let dec = image::gif::GifDecoder::new(cursor).unwrap();
dec.into_frames()
.map(|f| f.unwrap()) …
```
> gif: improve performance of `GifFrameIterator`

- src/bmp/decoder.rs
Opening the WIP because ~~(a) I'd like to rebase on #1193 when that's merged and (b)~~ I started doing this when i started drinking and I'd like to write some of this down before I pass out and forget.
Are `BitfieldMasksMissing` and `BitfieldMaskMissing` different or the same error conditions, considering the similar but differing original strings (i.e. can I merge the former into the latter)?
Also fixes https://github.com/image-rs/image/commit/183aab34ccb57374b0acac732ac7f681a17df842#r38436431
Vaguely ref: #1134
Part of: #1195
> Destringtypify the BMP decoder

- src/gif.rs
- src/hdr/decoder.rs
I'm also a tad unsure of the import of the `limit_string_len()` function in HDR.
Ref: #1134
> Remove legacy constructors from GIF and HDR decoders

- src/error.rs
> Remove ImageError::UnsupportedError()

- CHANGES.md
- Cargo.toml
> Update meta data for release 0.23.4

- src/pnm/decoder.rs
- src/pnm/mod.rs
> Fix PBM ascii decoding

- .travis.yml
- fuzz/fuzzers/fuzzer_script_bmp.rs
- fuzz/fuzzers/fuzzer_script_gif.rs
- fuzz/fuzzers/fuzzer_script_hdr.rs
- fuzz/fuzzers/fuzzer_script_ico.rs
- fuzz/fuzzers/fuzzer_script_jpeg.rs
- fuzz/fuzzers/fuzzer_script_png.rs
- fuzz/fuzzers/fuzzer_script_pnm.rs
- fuzz/fuzzers/fuzzer_script_tga.rs
- fuzz/fuzzers/fuzzer_script_tiff.rs
- fuzz/fuzzers/fuzzer_script_webp.rs
Re-enables the `cargo-fuzz` fuzzers as part of our CI.
> Enable fuzzers

- src/image.rs
This is added specifically to list extension that are surely recognized when used with `from_path`. This same guarantee would not be given if using some external list of names. You can open another issue/PR if you feel that some extensions are missing from the list of a format.
@PurpleMyst, @tripulse, @Nemo157
Closes: #1239
> Add a reverse mapping of ImageFormat::from_path

- CHANGES.md
- Cargo.toml
- src/jpeg/encoder.rs
- src/lib.rs
- src/png.rs
It's time for another release. Multiple bug fixes are available just by updating dependencies to more recent compatible versions but we still have enough features and a couple of fixes here. Adss some more documentation to the modified files and interfaces as well.
> Release 0.23.5

- src/jpeg/encoder.rs
> Fix loss of brightness in the JPEG encoder

- src/imageops/sample.rs
> Add PartialEq trait to FilterType

- CHANGES.md
- Cargo.toml
> Update meta data for release 0.22.9

- CHANGES.md
- Cargo.toml
Sometimes in the next few days (potentially integrating `tiff` but also, not depending on it).
> Release notes for 0.23.10

- src/lib.rs
Not super polished, but hopefully an improvement over the current text.
> Streamline docs.rs documentation and move some content to README

- CHANGES.md
- Cargo.toml
- Cargo.toml.public-private-dependencies
> Update meta data for 0.23.11

- src/lib.rs
> Add back png::{CompressionType, FilterType} to fix regression

- src/dynimage.rs
When looking at the `DynamicImage::write_to`, I noticed that there is a bit more cloning/allocation happening than necessary. In particular, the `bytes` variable created in the beginning is not used in some cases and `self.to_rgba().iter().cloned().collect()` converts and then iterates and collects again. The changed version borrows the bytes instead and only allocates when a conversion is required. I also shortened `a.iter().cloned().collect()` to `a.as_raw().clone()` in `image_to_bytes`.
> Less allocations in DynImage::write_to.

- src/image.rs
Progresses #1373
Adds can_read.
> Adds can_read on ImageFormat

- src/io/free_functions.rs
A few other odd things I noticed when doing this.
* `hdr::HdrEncoder` doenst adhere to the same convention as the other encoders, having only a `encode` function that takes `&[Rgb<f32>]` instead of `&[u8]` + `ColorType` as the 4th param as well as taking the dimensions as `usize`
* `ImageFormat::Pnm` needs to match again on the extension to determine the subtype it uses, this is not really a problem but makes it so the error that I return not to be that usefull, I guess we can add another (ImageFormatHint) and be more helpful.
> Fixes #1390: Refactors save_buffer_impl to call save_buffer_with_format_impl

- src/imageops/colorops.rs
On Stack Overflow a [question] asked in relation to the efficiency of the `colorops` module. I [answered][answer] implementing `*_in_place` variants of the functions, to avoid the needless cloning and heap allocations for temporary images.
I wasn't able to find any discussions of why the `colorops` module didn't have `*_in_place` variants of its functions, while the `imageops` module does. So if that is desired, then this PR implements those.
More information can be found in my Stack Overflow [answer], along with some benchmarking details.
[question]: https://stackoverflow.com/questions/65517715/fastest-way-to-perform-multiple-imageimageops-on-a-single-image-rust
[answer]: https://stackoverflow.com/a/65524735/2470818
-----
I license past and future contributions under the dual …
> Added in_place variants of colorops

- .github/workflows/rust.yml
> Add a test for avif-decoding in controlled environment

- README.md
Also added some periods for consistency
> Added note to README.md that resize is slow in debug mode

- src/codecs/tga/decoder.rs
- src/color.rs
> Allow loading alpha-only TGAs as L8

- README.md
> Replace Travis badge with GitHub Actions

- src/codecs/pnm/decoder.rs
> Avoid unneeded allocations in PNM decoder

- Cargo.toml
- Cargo.toml.public-private-dependencies
- src/codecs/png.rs
Previous #1541 
Ref: https://github.com/image-rs/image-png/issues/272
> Bump png to 0.17.0

- src/buffer.rs
> Use `slice::copy_within`

- src/imageops/sample.rs
Seems to be caused by a bad merge between https://github.com/image-rs/image/commit/d46578d6d171309143f820c9e9c8cabc6fce0ba4 and https://github.com/image-rs/image/commit/4eed468f852c80eca718abe679877be377488fb9
> Fix issue #1600

- src/imageops/sample.rs
This maintains precision and avoids a lot of unnecessary rounding to integers for intermediate values. This improves precision and performance.
On a 2950x:
Before: test imageops::sample::tests::bench_resize                     ... bench:   3,179,804 ns/iter (+/- 129,332) = 641 MB/s
After: test imageops::sample::tests::bench_resize                     ... bench:   1,563,759 ns/iter (+/- 87,143) = 1304 MB/s
Since there's no real generic [f32; 4] pixel type I just used Rgba32FImage as the intermediate type. The image is never converted to Rgba and the channel order is passed through, which is a bit weird but should be sound.
Fixes #1603
> Use a 4-channel f32 pixel intermediate type for resizing.

- src/codecs/ico/encoder.rs
- src/codecs/png.rs
It seems to be the only function that expects input in big endian, so getting
rid of it will make the rest of the library more consistent.
> Deprecate PngEncoder::encode and IcoEncoder::encode

- src/codecs/webp/vp8.rs
> Quick fix to overflow issue in loop filtering.

- Cargo.toml
- src/codecs/openexr.rs
- use newer version with bugfixes
- use simpler channel lookup in new version
> Update exr 1.4.0

- src/codecs/png.rs
We must properly recognize that no longer all color types are support
for PNG encoding (somewhat amazingly we made it thus far without a
barrage of reports). To make this more future proof, the list of matched
color types is explicit.
Closes: #1663
> Fix PNG encoding not recognizing unsupported color

- src/buffer.rs
Add missing pixel channel count multiplication to indexing
Add additional tests to compare methods to `ImageBuffer::get_pixel`
---
This aligns the checked logic with `ImageBuffer::pixel_indices_unchecked` which calculates the minimum index with the following:
```rust
fn pixel_indices_unchecked(&self, x: u32, y: u32) -> Range<usize> {
let no_channels = <P as Pixel>::CHANNEL_COUNT as usize;
// If in bounds, this can't overflow as we have tested that at construction!
let min_index = (y as usize * self.width as usize + x as usize) * no_channels;
min_index..min_index + no_channels
}
```
Open to suggestions for other/better tests.
Closes #1672
> Fix incorrect `get_pixel_[mut_]checked` indexing

- src/buffer.rs
- src/codecs/openexr.rs
- update exr write function (it accepts any alignment)
- update supported formats for image buffer save function
> Update outdated function docs

- src/imageops/colorops.rs
This pull request fixes the todo in the code and some other loop that can be upgraded by using .pixels()
As this is my first pull request on this project. I'm not sure if this is done right, so please feel free to start a discussion, if i have done something wrong or missed things.
> Fix Todo and loop colorops.rs

- Cargo.toml
exr crate license was updated. improves behaviour with cargo-deny.
> update openexr 

- CHANGES.md
- Cargo.toml
> Change notes and metadata for 0.24.2

- src/dynimage.rs
> Issue 1705 dynimage into bytes

- Cargo.toml
- src/codecs/jpeg/encoder.rs
- src/utils/mod.rs
These dependencies come with build scripts, this makes our builds faster.
> Replace range_step with standard iterators

- .github/workflows/rust.yml
- src/codecs/tiff.rs
> Fix arithmetic overflow in TIFF error reporting

- CHANGES.md
- Cargo.toml
> Bump version to 0.24.3

- CHANGES.md
- Cargo.toml
> Changes and release notes for 0.24.4

- src/buffer.rs
Fix some links
- https://docs.rs/image/latest/image/struct.ImageBuffer.html
- https://docs.rs/image/latest/image/struct.ImageBuffer.html#method.write_to
> Fix some links in doc

- src/codecs/gif.rs
I got tripped up on this and would like future developers to know about it.
> Improve documentation for gif encoder constructor

- deny.toml
Should fix the CI failures we've been seeing.
> Fix cargo deny issues

- src/codecs/bmp/decoder.rs
Add a `BmpDecoder::new_without_file_header(reader)` constructor to parse BMP images that don't have a `BITMAPFILEHEADER`. This format is used by Windows for the `CF_DIB` [clipboard format](https://learn.microsoft.com/en-us/windows/win32/dataxchg/standard-clipboard-formats). `CF_DIB` just starts with a `BITMAPINFO` structure and no file header.
I've tested this constructor can decode a `CF_DIB` from the Windows clipboard.
To write a `CF_DIB` back _to_ the clipboard, you can encode a bitmap normally, then skip `sizeof(BITMAPFILEHEADER)` when writing it. So we don't really need a special encoder for that.
I license past and future contributions to image-rs under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.
Closes #1880.
> add bmp new_without_file_header() constructor

- src/buffer.rs
> inline put_pixel

- src/codecs/webp/decoder.rs
- src/codecs/webp/extended.rs
> webp: Support ICC profiles

- src/codecs/tiff.rs
Should I upstream the TIFF tag maybe?
> tiff: Support ICC profiles

- deny.toml
> Fix cargo deny failures

- src/codecs/webp/encoder.rs
> Fix panic attempting to encode zero sized webp

- src/dynimage.rs
- src/lib.rs
> Add DynamicImage::write_with_encoder

- Cargo.toml
- Cargo.toml.public-private-dependencies
- src/codecs/tiff.rs
> Upgrade tiff

- CHANGES.md
- Cargo.toml
- src/imageops/sample.rs
~~Should wait for #1972~~. This PR should now be ready. I'll leave it open for a few days in case anyone raises concerns/spots something that's missing
> Release 0.24.7

- benches/decode.rs
Update the directory name to the current existing folder
Remove files that are no longer in the path
> Fix webp benches

- .github/workflows/rust.yml
> Fix cargo-afl installation

- src/image.rs
> Deprecate GenericImageView::bounds

- Cargo.toml
> Bump dav1d to 0.10.1

- src/codecs/avif/decoder.rs
PR for #2049.
I am not quite sure if this is the correct format for the error message of this kind.
> Replace assert with proper Unsupported error

- src/codecs/webp/lossless.rs
> Fix clippy issue

- tests/reference_images.rs
> Fix reference tests on big endian

- src/codecs/gif.rs
This PR avoids calling gif's `buffer_size` method because we cannot easily know in advance whether it will overflow
Fixes #2097
> Avoid overflow in gif::Decoder::buffer_size

- .github/workflows/rust.yml
- src/codecs/avif/encoder.rs
> Fix AVIF limits test

- .github/workflows/rust.yml
> Run CI for next branch

- .github/workflows/rust.yml
- Cargo.toml
- README.md
- src/buffer.rs
- src/codecs/gif.rs
- src/codecs/ico/encoder.rs
- src/codecs/png.rs
- src/codecs/webp/encoder.rs
- src/codecs/webp/mod.rs
- src/dynimage.rs
- src/flat.rs
- src/image.rs
- src/lib.rs
- tests/limits.rs
> Remove deprecated items

- src/buffer.rs
- src/codecs/png.rs
- src/dynimage.rs
- src/image.rs
- src/io/free_functions.rs
- src/lib.rs
- tests/limits.rs
- tests/save_jpeg.rs
> Remove ImageOutputFormat

- src/io/mod.rs
> Make Limits `#[non_exhaustive]`

- Cargo.toml.public-private-dependencies
- src/animation.rs
- src/codecs/avif/decoder.rs
- src/codecs/bmp/decoder.rs
- src/codecs/dxt.rs
- src/codecs/farbfeld.rs
- src/codecs/gif.rs
- src/codecs/hdr/decoder.rs
- src/codecs/ico/decoder.rs
- src/codecs/jpeg/decoder.rs
- src/codecs/jpeg/encoder.rs
- src/codecs/png.rs
- src/codecs/pnm/decoder.rs
- src/codecs/tga/decoder.rs
- src/codecs/tga/encoder.rs
- src/codecs/tiff.rs
- src/codecs/webp/decoder.rs
- src/codecs/webp/encoder.rs
- src/codecs/webp/extended.rs
- src/codecs/webp/huffman.rs
- src/codecs/webp/lossless.rs
- src/codecs/webp/lossless_transform.rs
- src/codecs/webp/vp8.rs
- src/image.rs
- src/imageops/colorops.rs
- src/io/mod.rs
- tests/reference_images.rs
> Fix new compiler warnings

- CHANGES.md
- Cargo.toml
- src/codecs/avif/decoder.rs
- src/image.rs
> Merge main branch into next

- .github/workflows/rust.yml
> Cache cargo-fuzz install

- .github/workflows/rust.yml
- tests/truncate_images.rs
> Fix caching for cargo cross CI tests

- .github/workflows/rust.yml
> Cache registry cache in cargo-afl CI job

- .github/workflows/rust.yml
> Force install to fix cache issue in CI

- src/codecs/avif/encoder.rs
- src/codecs/bmp/decoder.rs
- src/codecs/gif.rs
- src/codecs/hdr/decoder.rs
- src/codecs/hdr/encoder.rs
- src/codecs/openexr.rs
- src/dynimage.rs
- src/math/utils.rs
- src/traits.rs
> Fix clippy warnings

- CHANGES.md
> Mention DXT removal in changelog

- CHANGES.md
- Cargo.toml
> Release 0.25.1

- README.md
> Fix clippy warnings in readme

- .github/workflows/rust.yml
- Cargo.toml
> Run cargo-semver-checks with release-type minor

- CHANGES.md
- Cargo.toml
> Release notes and metadata for 0.25.2

- examples/scaledown/main.rs
- examples/scaleup/main.rs
The one lint that's been bugging our CI tests as of recently.
> Fix clippy lint in test suite

- Cargo.toml
The RGB crate is preparing for a semver-major update, and I'd like everyone to update to a future-proofed verison.
> Bump ravif/rgb

- src/codecs/webp/decoder.rs
Follows up on the reviewer comment in #2291
> Implement Exif metadata extraction for WebP

- CHANGES.md
#2348 didn't make it, so don't mention it in the changelog
> Drop incorrect changelog entry

- src/imageops/sample.rs
A follow-up to https://github.com/image-rs/image/pull/2397, this time gated behind the `serde` feature.
> Impl Serialize/Deserialize for FilterType

- .github/workflows/rust.yml
CI failing notifications are so annoying
> CI: add num-traits to public

- CHANGES.md
- Cargo.toml
Preparing release changelog and bump version
Closes #2440
> Preparing release

- src/dynimage.rs
Hi a little PR to use the turbofish syntax for conversion
> Add Turbofish convert

- src/color.rs
- src/image.rs
- src/imageops/sample.rs
- src/math/rect.rs
- src/metadata.rs
add serde derive to (some) struct and enum
> add serde derive to struct and enum

- src/dynimage.rs
- src/imageops/fast_blur.rs
- src/imageops/mod.rs
- src/imageops/sample.rs
Documentation about scene linear light assumption
Closes #2458
> Linear light documentation

- src/codecs/avif/decoder.rs
- src/codecs/avif/mod.rs
- src/codecs/avif/ycgco.rs
- src/codecs/avif/yuv.rs
Attempt to refactor YUV to reduce complexity.
This is probably not something you see every day. However, from my perspective, this approach allows methods to be added in a cleaner and more standartized way.
Feel free to reject it, if this is not something you want to see.
> YCgCo refactor

- src/codecs/gif.rs
> Use speed parameter in GifEncoder::encode

- src/codecs/gif.rs
Fix `GifDecoder` infinite loop when encountering non-recoverable error like io::ErrorKind::UnexpectedEOF.
This PR fix: https://github.com/image-rs/image/issues/2442
> fix gif decoder infinite looping when getting unexpectedEOF error

- src/codecs/jpeg/encoder.rs
Hey all,
Following up on the great work in the TIFF repo I am making a quick PR to add support for EXIF data in the JPEG codec. This uses the `APP1` marker and I reused the same template as the ICC profile setting. Let me know if you want me to rework some parts !
> Add EXIF block support

- src/codecs/bmp/decoder.rs
You'd think it would help codegen, ~~but on my machine it makes no difference on benchmarks whatsoever.~~  
I was measuring it wrong, it brings down the decoding time of an indexed RLE-encoded BMP from 4 ms to 3.6ms, so a 10% perf improvement.
Reduces binary size by 1.5KB (stripped), which is completely inconsequential.
I just like knowing that each row is genuinely row-sized and pixels are genuinely pixel-sized when thinking through the rest of the code.
All of the affected functions and types are private so this is not a semver hazard.
> BMP: use ChunksExactMut instead of ChunksMut

- src/metadata/cicp.rs
As detected https://github.com/image-rs/image/pull/2531#issuecomment-3226615934 we got a huge compilation slowdown from the CICP support. Not all of it caused by `moxcms` but the cause is the same: unecessary const-monomorphization.
This removes the biggest cause in `image` itself:
```
347249                7059                (TOTAL)
58440 (16.8%, 16.8%)  120 (1.7%,  1.7%)  image::metadata::cicp::CicpRgb::cast_pixels
16176 (4.7%, 21.5%)    12 (0.2%,  1.9%)  image::imageops::filter_1d::filter_symmetric_column
```
```
302612                7068                (TOTAL)
16176 (5.3%,  5.3%)    12 (0.2%,  0.2%)  image::imageops::filter_1d::filter_symmetric_column
13959 (4.6%, 10.0%)    27 (0.4%,  0.6%)  <core::iter::adapters::flatten::FlattenCompat<I,U> as …
```
> Avoid unecessary monomorphization in cicp

- src/hooks.rs
Following my confusion in #2569
> Expand docs on decoding hooks

- src/images/buffer.rs
- src/images/dynimage.rs
- src/metadata/cicp.rs
@fintelia Should we put that in the re-release or do another `0.25.9` right after?
> Luma to rgb transform is broadcast

- CHANGES.md
Probably worth mentioning (I would have appreciated an up-front warning :)).
Thank you for image <3
> Mention MSRV change in 0.25.7 changelog entry
